# -*- coding: utf-8 -*-
# hyd-iot-edu 데이터 리니지 (현재 작업 트리 코드 기준, 2026-10-07 조사, 읽기 전용)
# 실행 설정 근거: compose.yaml 기본값 TIME_SCALE=20 · DAQ_PROFILE=lite · PROCESS_MODE=legacy · ENTERPRISE_BACKEND=memory,
#               .env 는 TIME_SCALE=20 · DAQ_PROFILE=lite · PROCESS_MODE=instance · AGENT_BRIDGE=legacy · ENTERPRISE_BACKEND=supabase
# Kafka 토픽은 모두 파티션 1개(it/redpanda/topics.sh:6), 키는 설비 키 hyd01 형식(hydcommon/topics.py:17-19).
# 경로 표기: ot/plant-sim/plantsim → plantsim, dmz/connect-ingest/app → ingest, dmz/cmd-gateway/gw → gw,
#           it/detector/det → det, it/connect-sink/app → sink, it/agent/agentsvc → agentsvc, it/process/procsvc → procsvc,
#           it/agent-worker/worker → worker, it/enterprise-sim/entsim → entsim, common/hydcommon → hydcommon

LINEAGE = {}

LINEAGE["tag"] = dict(
  title="계측값(예: TS1) · 1초 태그",
  origin="plantsim thermal.step()이 UnitState.ts1(유일한 미분 상태)과 파생 채널을 시뮬레이션 1초마다 갱신, Plant.tick이 벽시계 1초당 TIME_SCALE번 반복 (plantsim/thermal.py:88-117, plantsim/plant.py:54-65)",
  hops=[
    dict(branch="본선", step="1", where="plant-sim · thermal.UnitState", how="프로세스 메모리, Plant.lock 아래 tick(벽시계 1 s = TIME_SCALE 시뮬레이션 s)",
         fmt="파이썬 dataclass",
         fields="ts1 ts2 ts3 ts4 ps1~ps6 eps1 fs1 fs2 vs1 ce cp se fan_pct load_pct cooler_health leak bearing_wear pump t_amb sim_t",
         change="TS1만 적분, 나머지는 TS1·load·fan·교란(cooler_health·leak·bearing_wear)에서 계산 + 공통 가우스 잡음 n; 정지/트립이면 load·fan 0으로 계산",
         keep="메모리만(재시작 시 ts1=48.0 초기값)", ref="plantsim/thermal.py:43-117"),
    dict(branch="본선", step="2", where="plant-sim · Plant.tags(asset)", how="edge._run 루프가 1 s마다 호출, lock 없이 읽음",
         fmt="dict[str,float]",
         fields="TS1 TS2 TS3 TS4 PS1 PS2 PS3 PS4 PS5 PS6 EPS1 FS1 FS2 VS1 CE CP SE FanSpeedSP LoadSP",
         change="소문자 속성 → 대문자 태그 이름(fan_pct→FanSpeedSP, load_pct→LoadSP); 반올림 TS1~4·PS1·PS2 2자리, PS3~6·EPS1·FS1·FS2·VS1·CP 3자리, CE·SE 1자리, SP 원값; cooler_health·leak·bearing_wear·pump·t_amb 버림",
         keep="없음", ref="plantsim/plant.py:115-124; plantsim/edge.py:123-137"),
    dict(branch="본선", step="3", where="plant-sim · DaqFilter.select (DAQ_PROFILE, 기본 lite)", how="edge._publish_tags 안, time.monotonic 기준",
         fmt="dict 부분집합", fields="2단계와 같은 이름의 부분집합",
         change="full: 전부 통과 / lite: ALWAYS{TS1,CE,PS1,FS1,VS1,LoadSP} 매초, 핵심 태그는 데드밴드(TS3·TS4 0.2, EPS1 0.05, CP 0.1, SE 0.5, FanSpeedSP 0.5, 기본 0.5) 이상 변화 또는 10 s 하트비트, AUX{TS2,PS2~PS6,FS2}는 값과 무관하게 30 s 하트비트만 → 필터",
         keep="_last[(asset,tag)]=(값, 보낸 시각) 메모리", ref="plantsim/daq.py:22-39; hydcommon/daq_contract.py:4-9"),
    dict(branch="본선", step="4", where="plant-sim edge → emqx(OT)", how="MQTT plant/{hyd01}/tag/{name}, QoS 0, retain 없음, self.connected가 True일 때만 발행",
         fmt="JSON", fields="t · v · q",
         change="설비는 토픽 키로만 전달; t = 발행 순간의 벽시계 now_iso(ms, Z — 시뮬레이션 시각 아님) 추가; q='good' 상수",
         keep="브로커 보관 없음(비보존 QoS0)", ref="plantsim/edge.py:108-113; hydcommon/topics.py:31-32; hydcommon/timeutil.py:8-13"),
    dict(branch="FUXA", step="4a", where="fuxa · MQTTclient 디바이스 emqx", how="json 태그 address plant/{k}/tag/{name}, memaddress v, subs [v]",
         fmt="FUXA 태그 값", fields="{k}_TS1 {k}_CE {k}_CP {k}_SE {k}_FanSpeedSP {k}_LoadSP {k}_VS1 {k}_PS1",
         change="v만 읽음, t·q 버림; 나머지 11개 태그는 구독하지 않음",
         keep="FUXA 런타임 메모리(프로젝트에 히스토리·차트 없음)", ref="ot/fuxa/build_project.py:33-39; ot/fuxa/project.json(생성물 일치 확인)"),
    dict(branch="FUXA", step="4b", where="fuxa · alarms '{a} TS1'", how="checkdelay 1, ackmode 0",
         fmt="FUXA 알람", fields="variableId {k}_TS1 · high(60~65) · highhigh(65~200) · text · group",
         change="임계 비교로 알람 상태 생성", keep="FUXA 런타임", ref="ot/fuxa/build_project.py:219-229"),
    dict(branch="본선", step="5", where="connect-ingest · _on_message → to_kafka → asyncio.Queue → pump()",
         how="구독 plant/+/tag/+ QoS 0; paho 스레드 → loop.call_soon_threadsafe → Queue(maxsize 20000) → aiokafka send → Kafka plant.tag, key=hyd01",
         fmt="JSON(value_serializer json.dumps)", fields="asset · name · t · v · q",
         change="토픽에서 asset(HYD-01)·name 복원해 본문에 더함, q 없으면 'good'; JSON 해석 실패는 버림; 큐가 가득 차면 버리고 dropped만 셈",
         keep="큐 메모리; Kafka plant.tag 파티션 1, retention.ms 1일",
         ref="ingest/main.py:34-51,54-57,60-88; it/redpanda/topics.sh:7"),
    dict(branch="detector", step="6", where="detector · run() group detector(from_latest, auto_commit 끔) → on_tag",
         how="레코드마다 SQLite offsets로 중복 확인 → mutation_lock 안에서 처리 → checkpoint(key) → drain_alerts → cons.commit(offset+1)",
         fmt="파이썬 dict", fields="asset · name · v · t · q",
         change="PatternRuntime.observe: 미래(+grace 2 s)·역순·같은 시각 다른 값은 무효/무시, 수집 한도(1 s+2 s, 하트비트 태그 10/30 s+2 s) 초과 간격이면 hold 중단·경사창 비움; main.observe로 latest[name] 갱신; VS1·TS1 경사창에 시뮬레이션 시각((t-첫 t0)×TIME_SCALE)으로 push; TS1이면 패턴 평가·feat 생성(feat·alert 리니지로 이어짐)",
         keep="AssetState·PatternRuntime 메모리 + /data/detector.sqlite3(checkpoint 본문, offsets, outbox)",
         ref="det/main.py:114-186,278-324; det/pattern_runtime.py:102-171; det/observations.py:22-51; det/store.py:7-43"),
    dict(branch="connect-sink", step="7", where="connect-sink · run() group connect-sink(첫 시작 earliest, auto_commit 끔, getmany 최대 2000건/500 ms)",
         how="store_records: 한 DB 트랜잭션에 tag_1s INSERT(executemany) + sink_offsets(next_offset) 기록 → 그 뒤 Kafka commit",
         fmt="SQL 행", fields="tag_1s(time, asset, name, value)",
         change="t → timestamptz(파싱 실패 시 Kafka 레코드 시각, 그것도 없으면 now()); v → float; q 버림; sink_offsets보다 작은 offset 건너뜀; 형식 오류 레코드는 건너뛰고 errors 증가",
         keep="TimescaleDB hypertable(6시간 청크), 2시간 뒤 압축, 3일 보존",
         ref="sink/main.py:39-47,65-69,119-152,155-183; it/timescaledb/init.sql:5-12,72,77,79"),
    dict(branch="connect-sink", step="8", where="timescaledb · tag_1m 연속 집계", how="time_bucket 1분, 정책: 1분마다 [now-1h, now-1min] 갱신, WITH NO DATA",
         fmt="SQL 행(물질화 뷰)", fields="bucket · asset · name · avg · min · max",
         change="1분 평균·최소·최대로 집계", keep="30일 보존",
         ref="it/timescaledb/init.sql:65-71,74; it/timescaledb/reader.sql:11"),
    dict(branch="Grafana", step="9", where="grafana · 데이터소스 uid tsdb(계정 grafana, SELECT 권한)", how="refresh 5s, 기본 now-10m; tag_1s를 직접 SELECT(tag_1m은 어느 패널도 읽지 않음)",
         fmt="Grafana stat/timeseries",
         fields="stat: value(TS1·CE·FanSpeedSP·LoadSP 최신 1행, 시간 필터 없음) / timeseries: time, value AS TS1·CE·SE·CP·FanSpeedSP·LoadSP",
         change="표시명 별칭(냉각 효율 CE 등), spanNulls=true로 빈 구간 연결, 60/65 ℃ 임계선",
         keep="없음(조회 시 계산)", ref="it/grafana/build_dashboard.py:30-32,71-99; it/grafana/provisioning/datasources/ds.yaml"),
    dict(branch="agent 증거 SQL", step="10", where="agent · mcp_tsdb.TimeSeriesDB.evaluate (계정 hyd_timeseries_reader, 읽기 전용, statement_timeout 5 s)",
         how="Neo4j Evidence.sql(%(asset)s)를 sql_read.guard(tag_1s·feat_1s·tag_1m만) 통과 후 실행 → 스칼라 1개; tag·windowSeconds 있으면 같은 tag_1s 시각 배열로 관측 공백 검사(한도 = 수집 주기+2 s)",
         fmt="파이썬 dict", fields="Evidence id → value · passed · status(PASS/FAIL/UNKNOWN) · reason · sql · coverage{samples, max_gap_s, limit_s, covered, tag, window_s}",
         change="벽시계 30 s~5 min 창의 avg 또는 max-min 집계, lt/lte/gt/gte/eq 비교; 행 없음·NULL·공백·쿼리 오류는 UNKNOWN(거짓 아님)",
         keep="agent run 기록 메모리(최대 200건)",
         ref="agentsvc/tools/mcp_tsdb.py:23-37,74-125; it/neo4j/v2/instances.cypher:242-252; agentsvc/card.py:21-61"),
    dict(branch="agent 신선도·사실", step="10a", where="agent · mcp_prom.freshness / decide.gather_facts / fan100_hours",
         how="tag_1s TS1 최신 행 나이(-2~60 s) + connect-ingest /healthz; DMN 사실 = tag_1s 최신값(승인 재검사 strict는 나이 -2~15 s)",
         fmt="파이썬 dict",
         fields="freshness{ok, age_s, max_age_s, max_skew_s, latest_ts1, ingest, reason} · facts{ts1, ce, ps1, fs1, vs1, load} · fan100_hours",
         change="태그 → 소문자 사실 이름(LoadSP→load), 값 round 3; FanSpeedSP>=99 연속 구간을 시간 단위로 환산",
         keep="decision 기록 메모리(200건) → process book으로 제출 시 facts·provenance 복사",
         ref="agentsvc/tools/mcp_prom.py:18-36; agentsvc/decide.py:23-24,105-133; agentsvc/tools/mcp_tsdb.py:127-150"),
    dict(branch="process 회복 판정", step="11", where="process · fire_timer('reobs') → latest_tag(asset, inc.recovery[0])",
         how="psycopg(PG_DSN 계정 hyd) SELECT value FROM tag_1s ORDER BY time DESC LIMIT 1; 타이머 900 시뮬레이션 s ÷ TIME_SCALE(20 → 45 s), 값이 기준 안인데 CLEAR 전이면 1/3씩 최대 3회 연장",
         fmt="float", fields="value(패턴별 회복 태그 TS1 · PS1 · VS1)",
         change="회복 기준 비교(TS1<55 · PS1>=165 · VS1<1.2) AND inc.cleared → RESOLVED / ESCALATED(MITIGATION_FAILED)",
         keep="Incident.history·audit(REOBSERVATION) → /data/process.sqlite3 스냅샷",
         ref="procsvc/main.py:89-113; procsvc/machine.py:221-261; procsvc/definition.py:25-38"),
  ],
  ends=["FUXA 화면 값·TS1 알람(현장 운전원)",
        "TimescaleDB tag_1s(3일) · tag_1m(30일) → Grafana 추세·stat(tag_1s만), mcp_tsdb/dmn-mcp timeseries_query(tag_1m 포함)",
        "detector 패턴 판정(alert) · feat.1s(feat)",
        "agent 신선도 판정 · 원인 증거 PASS/FAIL · DMN 사실 → 가이드 카드·조치 카드 순위",
        "process 재관측 회복 판정 → RESOLVED/ESCALATED → 작업지시"],
  loss=["lite 프로파일: 데드밴드 미만 변화는 최대 10 s, AUX 태그(TS2·PS2~6·FS2)는 30 s마다만 발행 → tag_1s 공백; Grafana는 spanNulls로 선을 이어 공백이 보이지 않음",
        "plant-sim에 on_disconnect가 없어 connected가 한번 True면 계속 True; 끊긴 동안 QoS0 발행은 유실되지만 DaqFilter._last는 보낸 것으로 갱신 → 데드밴드 태그는 다음 변화/하트비트까지 빠짐",
        "MQTT QoS 0(발행·구독 모두) → 브로커·ingest 부하 시 무통보 유실",
        "connect-ingest: 큐 20000 초과분 버림; prod.send 예외 시 해당 항목 재시도 없이 버림; await send는 배치 적재까지만 기다려 브로커 전달 확인 아님",
        "Kafka plant.tag 보존 1일: sink가 1일 넘게 멈추면 유실",
        "detector group 첫 시작은 latest → 그 전 레코드 무시; 시각 역순·미래·충돌 값 무시/무효",
        "sink: float 변환 실패·필드 누락 레코드 건너뜀(errors만 증가); q 버림",
        "tag_1m: 정책 주기 1분 + end_offset 1분 → 최소 1~2분 지연; start_offset 1시간 → 1시간 넘게 늦게 적재된 행은 집계되지 않음; materialized_only 미지정이라 실시간 집계 여부는 TimescaleDB 2.17 기본값 의존(미확인)",
        "tag_1s·feat_1s 3일 뒤 삭제",
        "Grafana stat은 시간 필터 없는 최신 1행 → 수집이 끊겨도 마지막 값을 현재처럼 표시",
        "process latest_tag는 행 나이를 보지 않음 → 파이프라인이 멈추면 오래된 값으로 회복 판정; 조회 예외는 None → MITIGATION_FAILED",
        "Evidence 창(30 s·2 min·5 min)은 벽시계, detector hold는 시뮬레이션 초 → 같은 '분'이 20배 다름"],
)

LINEAGE["wave"] = dict(
  title="파형(full 프로필, PS1·EPS1 100 Hz · FS1 10 Hz 1초 묶음)",
  origin="plantsim thermal.wave_ps1/wave_eps1/wave_fs1 — 발행 순간의 상태값에서 사인+잡음으로 1초분을 즉석 합성(실제 1초 이력 아님) (plantsim/thermal.py:120-131)",
  hops=[
    dict(branch="본선", step="1", where="plant-sim · edge._publish_waves", how="publish_wave가 참일 때만: DAQ_PROFILE=full 또는 PUBLISH_WAVE=1(compose 기본 lite라 꺼짐), 1 s 루프",
         fmt="파이썬 list[float]", fields="PS1 100개 · EPS1 100개 · FS1 10개",
         change="PS1 round 3, EPS1 round 4, FS1 round 3; PS1 기준값 = 155+0.3×load-130×유효누설", keep="없음",
         ref="plantsim/edge.py:33,115-121,131-132; plantsim/main.py:19; plantsim/daq.py:19"),
    dict(branch="본선", step="2", where="plant-sim edge → emqx", how="MQTT plant/{hyd01}/wave/{PS1|EPS1|FS1}, QoS 0, retain 없음",
         fmt="JSON", fields="t0 · hz · v[]", change="t0 = 발행 순간 벽시계 now_iso", keep="없음", ref="plantsim/edge.py:118-120; hydcommon/topics.py:35-36"),
    dict(branch="본선", step="3", where="connect-ingest · to_kafka", how="구독 plant/+/wave/+ QoS 0 → Queue → Kafka plant.wave key=hyd01",
         fmt="JSON", fields="asset · sensor · t0 · hz · v",
         change="asset·sensor를 토픽에서 복원, v 없으면 []", keep="Kafka plant.wave retention 6시간(DAY/4)",
         ref="ingest/main.py:46-47,56; it/redpanda/topics.sh:8"),
    dict(branch="본선", step="4", where="detector · on_wave", how="plant.wave 레코드(asset·sensor 필수) → features.wave_features → prod.send(feat.1s), 아웃박스 없음",
         fmt="JSON", fields="asset · t · sensor · mean · rms · slope · score",
         change="t0 → t로 이름 바뀜; hz 버림; v 배열 → mean·rms·샘플 인덱스당 선형회귀 경사(초당 아님); score=None; 반올림 없음",
         keep="Kafka feat.1s retention 3일", ref="det/main.py:189-192,317-319; det/features.py:6-18; it/redpanda/topics.sh:10"),
    dict(branch="본선", step="5", where="connect-sink · store_records", how="feat.1s → feat_1s executemany, offsets 같은 트랜잭션",
         fmt="SQL 행", fields="feat_1s(time, asset, sensor, mean, rms, slope, score)",
         change="mean·rms·slope float, score NULL; time = t0 파싱(실패 시 Kafka 시각)",
         keep="3일 보존, 2시간 뒤 압축", ref="sink/main.py:70-74,139-141; it/timescaledb/init.sql:15-25,73,78,80"),
  ],
  ends=["feat_1s의 sensor PS1·EPS1·FS1 행 — Grafana는 sensor='TS1'만 읽어 화면에 없음",
        "mcp_tsdb / dmn-mcp timeseries_query로만 조회 가능(seeded Evidence는 tag_1s만 사용)",
        "원파형 v[]는 Kafka plant.wave 6시간에만 존재, 어떤 저장소에도 적재되지 않음"],
  loss=["기본(lite) 설정에서는 전혀 생성되지 않음",
        "MQTT QoS 0, ingest 큐 초과·send 예외 시 유실(tag와 동일)",
        "detector는 feat를 prod.send(배치 적재)만 하고 곧바로 checkpoint로 offset을 처리 완료 기록 → 전송 전 프로세스가 죽으면 재처리 없이 유실",
        "slope 단위가 TS1 feat(시뮬레이션 초당)와 파형 feat(샘플당)로 같은 열에 섞임"],
)

LINEAGE["status"] = dict(
  title="설비 상태와 명령 ACK (plant/{a}/status)",
  origin="plantsim plc.status_payload(PlcState + UnitState) (plantsim/plc.py:152-173) → Plant.status가 sim_t·time_scale·disturbance_ramps 추가 (plantsim/plant.py:126-132) → edge._publish_status가 표시 필드 추가 (plantsim/edge.py:93-106). PlcState는 apply_command · check_interlock · set_mode · /api/reset이 바꾼다",
  hops=[
    dict(branch="본선", step="1", where="plant-sim · soft-PLC PlcState", how="Plant.lock 안: check_interlock 매 시뮬레이션 초, apply_command(cmd/auto·cmd/manual·/api/manual), set_mode(FUXA·LOCAL만)",
         fmt="파이썬 dataclass", fields="mode · state(RUN/TRIP/STOP) · trip · recent_cmd_ids(최근 32) · last_cmd_id · last_result · last_reason · last_source",
         change="인터록 TS1>65 OVERTEMP · PS1<130 LOW_PRESSURE · VS1>=2.0 HIGH_VIBRATION(자동 리셋 없음); FUXA 명령이 REMOTE_AUTO에서 오면 REMOTE_MANUAL로 전환",
         keep="메모리만", ref="plantsim/plc.py:29-60,67-141; plantsim/plant.py:54-65,100-112"),
    dict(branch="본선", step="2", where="plant-sim edge → emqx", how="MQTT plant/{hyd01}/status, QoS 1, retain=True; 설비마다 매 tick(1 s) + cmd/mode 메시지 처리 직후 + /api/mode·/api/manual·/api/reset",
         fmt="JSON",
         fields="asset · t · mode · state · forecast_model · ts1 · t_amb · trip · fan_pct · load_pct · cooler_health · leak · bearing_wear · pump · cmdId · result · reason · source · interlock · sim_t · time_scale · disturbance_ramps · reason_display · mode_text · state_text · result_text · reason_text",
         change="last_cmd_id→cmdId, last_result→result, last_reason→reason, last_source→source(마지막 명령 값이 매 하트비트에 반복); ts1 반올림 없음; interlock=TRIP/PASS 파생; 교란 값 round 3; *_text 한국어 라벨, reason_display=reason 또는 '–'",
         keep="브로커 retained 마지막 1건", ref="plantsim/edge.py:93-106,123-137,61-90; plantsim/plc.py:152-173"),
    dict(branch="FUXA", step="2a", where="fuxa · json 태그 plant/{k}/status", how="memaddress mode_text·state_text·result_text·reason_text",
         fmt="FUXA 태그 값", fields="{k}_mode · {k}_state · {k}_result · {k}_reason",
         change="표시 라벨만 사용, 원값·reason_display·교란 값 미사용", keep="FUXA 런타임", ref="ot/fuxa/build_project.py:40-43,168-170,202-205"),
    dict(branch="cmd-gateway", step="2b", where="cmd-gateway · MQTT 구독 plant/+/status QoS 1", how="_on_message → gstate.last_status[asset] = 본문 전체",
         fmt="파이썬 dict", fields="위 status 전체(검증엔 mode만 사용)",
         change="없음(asset 없으면 토픽 키로 설비 ID 복원)", keep="메모리만(재시작 후 retained 메시지로 복구)",
         ref="gw/main.py:34-55; gw/validate.py:51-56"),
    dict(branch="본선", step="3", where="connect-ingest · to_kafka", how="구독 plant/+/status QoS 1 → Kafka plant.status key=hyd01",
         fmt="JSON", fields="status 본문 그대로", change="asset 없으면 setdefault로 채움", keep="Kafka plant.status retention 7일",
         ref="ingest/main.py:48-50,56; it/redpanda/topics.sh:9"),
    dict(branch="process legacy", step="4", where="process · consume() group process(from_latest, auto_commit) → _legacy_record",
         how="plant_status[asset]=v; 종결 안 된 모든 Incident에 machine.on_status(설비 같은 것만)",
         fmt="파이썬 dict", fields="cmdId · result · reason · interlock · t (Incident.ack로 복사)",
         change="AWAITING_ACK이고 cmdId 일치·result DONE/REJECTED일 때만 inc.ack={result, reason, interlock, t} → ACKED→RE_OBSERVING(타이머) 또는 ESCALATED(PLC REJECTED)",
         keep="plant_status 메모리, Incident → /data/process.sqlite3 snapshot",
         ref="procsvc/main.py:225-237,273-309; procsvc/machine.py:188-205"),
    dict(branch="process instance", step="4i", where="process · consume() durable(raw bytes, 수동 commit) → kafka_record → PgSourceInbox.receive_many",
         how="Supabase process_source_inbox에 영수증 1건씩 커밋 후 Kafka offset commit; ACK는 _source_loop가 claim(설비당 1건, lease 60 s) → _apply_source_event",
         fmt="SQL 행(jsonb payload)",
         fields="process_source_inbox(source, delivery_key, topic, partition_no, offset_no, event_key, asset, kind STATUS|ACK|INVALID, payload, payload_sha, semantic_sha, wire_kind, wire_base64, wire_sha, policy, status, parent_id, error, result, history) · process_source_state(asset, source_time, receipt_id, payload)",
         change="cmdId 문자열 + result DONE/REJECTED면 kind ACK, event_key [command-ack, cmdId], semantic = {asset, cmdId, result, reason, interlock}; 같은 의미 반복은 DUPLICATE, interlock 등 달라지면 CONFLICT; STATUS는 즉시 HANDLED; t 없으면 INVALID; source_state는 더 새 t일 때만 갱신 → plant_status",
         keep="Supabase(보존 정책 없음)", ref="procsvc/source_inbox.py:24-77,102-170; procsvc/main.py:238-272,312-345; it/supabase/migrations/20261004000007_source_inbox.sql"),
    dict(branch="detector", step="5", where="detector · on_status", how="plant.status(asset 필수 아님, 없으면 HYD-00) → PLC_STATE 관측 → trip_alert",
         fmt="파이썬 dict", fields="state → PLC_STATE · trip · t",
         change="state가 RUN/STOP/TRIP 아니면 무효; TRIP 진입/해제 시 RAISE/CLEAR 경보 생성(alert 리니지)",
         keep="trip_state → detector.sqlite3 checkpoint", ref="det/main.py:195-209; det/cep.py:129-143"),
    dict(branch="connect-sink", step="6", where="connect-sink · handle_event(plant.status)", how="cmdId와 result가 있을 때만 actions UPSERT, WHERE actions.ack_result IS NULL(첫 ACK 고정)",
         fmt="SQL 행", fields="actions(cmd_id, ack_result, ack_reason, ack_at)",
         change="cmdId→cmd_id, result→ack_result, reason→ack_reason, t→ack_at; 그 밖의 상태 필드는 어디에도 저장 안 함",
         keep="TimescaleDB actions(보존 정책 없음)", ref="sink/main.py:104-110; it/timescaledb/init.sql:40-51"),
    dict(branch="agent 예측·DMN 사실", step="7", where="agent · forecasting.source / decide.gather_facts(plc_mode, plc_state)",
         how="HTTP GET process /api/plant/{asset}/status(process의 plant_status), t 나이 -2~15 s",
         fmt="JSON", fields="asset · t · forecast_model · ts1 · t_amb · fan_pct · load_pct · cooler_health · leak · bearing_wear · mode · state",
         change="mode→plc_mode, state→plc_state 사실; 교란 값(시뮬레이터 내부 진값)이 예측 입력으로 쓰임",
         keep="decision facts·provenance·forecastContext로 복사", ref="agentsvc/forecasting.py:23-77; agentsvc/decide.py:113-125; hydcommon/forecast.py:28-47; procsvc/main.py:617-623"),
  ],
  ends=["FUXA 모드·PLC 상태·최근 명령 결과 표시",
        "cmd-gateway 검사 ⑤(REMOTE_AUTO 여부)",
        "process Incident ACK → 재관측 타이머 / 에스컬레이션, instance 모드 task:command 완료",
        "detector PLC 트립 경보",
        "TimescaleDB actions.ack_* → Grafana 조치 표",
        "agent 예측(조치별 평형 유온)·DMN plc_mode/plc_state 사실"],
  loss=["PLC의 cmdId 중복 판정은 최근 32개·메모리뿐 → plant-sim 재시작 후 이전 cmdId 재수용 가능(만료 120 s가 대신 막음)",
        "status는 마지막 명령 하나만 담음 → 같은 cmdId가 하트비트마다 반복되고, 다음 명령이 오면 이전 ACK 필드는 사라짐",
        "process legacy 소비자는 from_latest·auto_commit → 꺼진 동안의 ACK 유실 → 30 s ACK_TIMEOUT으로 ESCALATED; 재시작 시 비종결 Incident는 PROCESS_RESTART_REVIEW로 ESCALATED",
        "instance 모드: 모든 상태 하트비트(설비당 초당 1건 이상)가 process_source_inbox에 payload·wire_base64와 함께 영구 적재(보존 정책 없음) — 테이블 증가",
        "instance 모드: FUXA 수동 명령의 cmdId(FUXA-…)도 ACK로 분류 → 연결 Incident가 없어 WAITING으로 5 s마다 영구 재시도",
        "instance 모드: ACK 뒤 interlock이 바뀌면(예: 트립) 같은 cmdId 반복분이 CONFLICT 행으로 쌓임",
        "sink: 첫 ACK만 기록; FUXA 명령의 ACK는 asset NULL 행으로 생겨 Grafana(WHERE asset=…)에 안 보임",
        "상태 원본은 TimescaleDB에 저장되지 않음(ACK 4개 열만) — 모드·트립 이력은 Kafka 7일에만"],
)

LINEAGE["feat"] = dict(
  title="탐지 특징값 feat.1s → feat_1s",
  origin="detector on_tag가 TS1 레코드를 받아들일 때마다 생성 (det/main.py:156-180); 파형 feat은 on_wave(wave 리니지)",
  hops=[
    dict(branch="본선", step="1", where="detector · on_tag(TS1)", how="TS1 관측이 유효할 때만, 같은 이벤트 루프",
         fmt="파이썬 dict", fields="asset · t · sensor · mean · rms · slope · score",
         change="mean = TS1 순간값(평균 아님); rms=None; slope = 최근 60 시뮬레이션 s 선형회귀 경사(℃/시뮬레이션 s, round 5); score = RMS(z(TS1),z(CE),z(VS1))/4 상한 1(round 3), 기준은 고정 NORMAL{TS1 48±1, CE 84±3, VS1 0.6±0.05}, TS1·CE·VS1 관측 문제(MISSING·STALE 등) 있으면 None",
         keep="경사창·latest 메모리", ref="det/main.py:58,80-81,163-180; det/features.py:21-80"),
    dict(branch="본선", step="2", where="detector → Kafka feat.1s", how="prod.send(key=hyd01), 아웃박스 없음; 같은 값으로 Prometheus gauge detector_anomaly_score·detector_ts1 갱신",
         fmt="JSON", fields="asset · t · sensor('TS1') · mean · rms · slope · score",
         change="없음", keep="Kafka feat.1s retention 3일; gauge는 /metrics 메모리",
         ref="det/main.py:175-180; it/redpanda/topics.sh:10"),
    dict(branch="본선", step="3", where="connect-sink · store_records", how="feat.1s → feat_1s executemany, offsets 같은 트랜잭션",
         fmt="SQL 행", fields="feat_1s(time, asset, sensor, mean, rms, slope, score)",
         change="None은 NULL, 나머지 float; time = t 파싱", keep="3일 보존, 2시간 뒤 압축",
         ref="sink/main.py:70-74,139-141; it/timescaledb/init.sql:15-25"),
    dict(branch="Grafana", step="4", where="grafana · '이상 점수 · 통계 기반' stat·timeseries", how="WHERE sensor='TS1', stat은 최신 1행(시간 필터 없음)",
         fmt="Grafana 패널", fields="score AS value / time, score",
         change="0.5 경고·0.8 위험 색", keep="없음", ref="it/grafana/build_dashboard.py:76-77,89-92"),
    dict(branch="조회 도구", step="5", where="agent mcp_tsdb · dmn-mcp timeseries_query", how="hyd_timeseries_reader가 feat_1s SELECT 허용",
         fmt="JSON 행", fields="feat_1s 열", change="없음(LLM이 쓴 SQL 결과)", keep="없음",
         ref="agentsvc/tools/mcp_tsdb.py:18,64-72; it/dmn-mcp/dmn_mcp/server.py:60"),
  ],
  ends=["Grafana 이상 점수 패널", "에이전트/워커의 임의 시계열 질의(seeded Evidence는 feat_1s를 쓰지 않음)", "Prometheus 지표"],
  loss=["TS1이 무효·지연·역순이면 그 tick의 feat 없음",
        "feat는 send 후 checkpoint가 offset을 처리 완료로 기록 → 전송 전 크래시 시 재처리 없이 유실(경보는 아웃박스로 보호, feat는 아님)",
        "score 기준값은 고정 상수(features.Baseline 학습 코드는 push가 호출되지 않아 미사용)",
        "Kafka 3일 · TimescaleDB 3일 보존"],
)

LINEAGE["alert"] = dict(
  title="경보 RAISE/CLEAR",
  origin="detector PatternRuntime.observe가 TS1 tick마다 Neo4j 정의(held 패턴)를 평가 → cep._step이 hold 충족 시 cep._alert 생성 (det/pattern_runtime.py:139-171, det/cep.py:47-91); PLC 트립은 on_status의 cep.trip_alert (det/cep.py:129-143)",
  hops=[
    dict(branch="본선", step="1", where="detector · fetch_catalog / poll_catalog(15 s)", how="Neo4j bolt, AnomalyPattern(detectionMode='held', detectorScope=production)+TESTS→InputData 한 트랜잭션",
         fmt="Cypher 결과 → Pattern dataclass",
         fields="id · code · severity · rule · clearRule · holdSeconds · clearHoldSeconds · slopeWindowSeconds · tests[{variable, operator, value}] → revision(sha256)",
         change="TESTS를 AND 식으로 재구성(rule 문장은 실행하지 않음); 1 Hz 아닌 입력·짧은 경사창 거부; 실패 시 기존 카탈로그 유지·후보 hold 중단",
         keep="PatternRuntime 메모리 + detector.sqlite3 checkpoint", ref="det/pattern_source.py:4-18; det/patterns.py:155-212; det/main.py:229-264; it/neo4j/v2/instances.cypher:202-206,392-396; it/neo4j/v2/detector-patterns.cypher"),
    dict(branch="본선", step="2", where="detector · cep._step / trip_alert", how="IDLE→CANDIDATE→(hold 시뮬레이션 s)→RAISED→CLEARING→(clearHold)→IDLE, at×TIME_SCALE 시계",
         fmt="파이썬 dict",
         fields="alertId · asset · pattern · severity · state · t · evidence{definition, values, slopes, condition, clear_condition, observation{hold_clock, time_scale, profile, grace_wall_s, ages_wall_s}, ts1, ce, ps1, fs1, load, vs1, ts1_slope, vs1_slope, score}",
         change="alertId = ALT-{hyd01}-{seq:04d}-{hex4}(트립은 ALT-{key}-TRIP-{seq:03d}-{hex4}); pattern = 정의 code(트립은 OVERHEAT_TRIP·LOW_PRESSURE_TRIP·HIGH_VIBRATION_TRIP·PLC_TRIP); t = TS1 이벤트 시각 isoformat(+00:00), 트립은 status t(Z); 트립 severity CRITICAL·evidence {trip}; evidence에 기존 소비자용 소문자 키를 덧붙임(ts1_slope는 main의 별도 경사창)",
         keep="CepState·TripState 메모리 → checkpoint", ref="det/pattern_runtime.py:144-171; det/cep.py:47-91,129-143; det/main.py:181-186,207-209"),
    dict(branch="본선", step="3", where="detector · emit_alert → Store.save outbox → drain_alerts", how="checkpoint와 같은 SQLite 트랜잭션에 outbox 적재 → send_and_wait 후 delivered(seq) 삭제(at-least-once)",
         fmt="JSON 문자열(SQLite)", fields="경보 dict 그대로", change="없음", keep="/data/detector.sqlite3 outbox(전달 전까지)",
         ref="det/main.py:212-226,267-270; det/store.py:27-40"),
    dict(branch="본선", step="4", where="Kafka alerts", how="key=hyd01, 파티션 1", fmt="JSON", fields="alertId · asset · pattern · severity · state · t · evidence",
         change="없음", keep="retention 365일", ref="it/redpanda/topics.sh:11"),
    dict(branch="cmd-gateway→FUXA", step="5", where="cmd-gateway · handle(alerts) → alert_to_ot", how="group cmd-gateway(from_latest, auto_commit) → MQTT plant/{k}/alert QoS 1 retain=True",
         fmt="JSON", fields="alertId · pattern · severity · state · level · t · text · display_text",
         change="evidence·asset 버림; level = RAISE 2 / CLEAR 0; display_text 한국어 라벨(TEMP_TRIP·OVERHEAT_TRIP 등 일부만 매핑); 오래된 retained 경보는 display_text를 붙여 다시 발행",
         keep="브로커 retained 설비당 마지막 1건; 게이트웨이 카운터 메모리", ref="gw/main.py:41-49,70-82; gw/validate.py:69-86"),
    dict(branch="cmd-gateway→FUXA", step="5a", where="fuxa · {k}_alert(level) · {k}_alert_text(display_text) · alarm '{a} IT ALERT'", how="semaphore 0 초록/2 빨강, highhigh level 2",
         fmt="FUXA 태그·알람", fields="level · display_text", change="알람 문구는 패턴과 무관하게 고정('쿨러 성능 저하 (Flink CEP RAISE)')", keep="FUXA 런타임",
         ref="ot/fuxa/build_project.py:44-47,166,209,230-233"),
    dict(branch="connect-sink", step="6", where="connect-sink · handle_event(alerts)", how="savepoint 안 UPSERT by alert_id",
         fmt="SQL 행", fields="alerts(alert_id, asset, pattern, severity, state, raised_at, cleared_at, evidence)",
         change="RAISE: INSERT 또는 state·raised_at·evidence 갱신 / CLEAR: INSERT 또는 state·cleared_at만 갱신(CLEAR evidence는 행이 있으면 버림); t→raised_at/cleared_at",
         keep="TimescaleDB alerts(보존 정책 없음)", ref="sink/main.py:80-94; it/timescaledb/init.sql:28-37"),
    dict(branch="connect-sink", step="6a", where="grafana · 활성 경보 stat · 경보 이력 표 · RAISE/CLEAR 주석", how="SQL", fmt="Grafana",
         fields="count(state='RAISE') · pattern · severity · state · raised_at · cleared_at · alert_id", change="한국어 값 매핑(일부 패턴만)", keep="없음",
         ref="it/grafana/build_dashboard.py:78-79,101-102,117-130,139-147"),
    dict(branch="agent(legacy 모드)", step="7", where="agent · consume() group agent(from_latest, auto_commit)", how="state=RAISE·alertId 있을 때만; PROCESS_MODE=instance면 건너뜀; RunRegistry로 alertId당 1회 → pipeline(스레드)",
         fmt="파이썬 dict → HTTP JSON", fields="alert 전체 → policy · freshness · t1_causes · evidence · causes · t2_skills · card",
         change="GET process /api/alerts/policy 로 지원 패턴 확인 → Neo4j t1_causes(pattern) → 증거 SQL → 원인 순위 → t2_skills → 가이드 카드(cmd 리니지)",
         keep="run 메모리 200건", ref="agentsvc/main.py:45-169; agentsvc/runs.py:46-62"),
    dict(branch="process legacy", step="8", where="process · _legacy_record(alerts)", how="group process(from_latest, auto_commit)",
         fmt="파이썬 dict", fields="alertId · asset · pattern · state",
         change="RAISE: 회복 기준 없는 패턴이면 ESCALATED Incident(UNSUPPORTED_ALERT_PATTERN) 생성; CLEAR: alertId 같은 비종결 Incident에 cleared=True, AWAITING_APPROVAL이면 RESOLVED_WITHOUT_ACTION, audit ALERT_CLEARED",
         keep="Incident → process.sqlite3", ref="procsvc/main.py:280-309; procsvc/machine.py:208-218"),
    dict(branch="process instance", step="8i", where="process · durable consume → process_source_inbox", how="RAISE는 수신 시점 정책(alert_policy.for_definition) 고정, event_key [alert, alertId, state]; _source_loop claim → RAISE: runtime.receive_alert(inst 리니지) / CLEAR: _apply_source_event → machine.on_alert(인스턴스 잠금) → rt.on_incident_update",
         fmt="SQL 행 → 파이썬 dict", fields="payload(경보 전체) · policy{pattern, route, criterion, definition, version, target}",
         change="연결 Incident 없으면 SourcePending → WAITING(5 s 후 재시도)", keep="Supabase process_source_inbox",
         ref="procsvc/main.py:238-272,312-345; procsvc/alert_policy.py:25-38; procsvc/source_delivery.py:18-49"),
    dict(branch="Neo4j 사건 투영", step="9", where="process · CaseProjector(INCIDENT_Q)", how="스냅샷 저장 시 큐 → 2 s 루프로 Neo4j 쓰기, revision 펜스",
         fmt="Cypher 노드", fields="Incident{id, alertId, openedAt, sourcePattern, sourceTrip, sourceAlert(JSON 문자열), status, reason, closedAt, cleared, command_id, work_order_ref}",
         change="경보 전체를 sourceAlert 문자열로; RAISED_BY AnomalyPattern(code), ON_ASSET Asset(code), DIAGNOSED_AS Cause(card.topCause)", keep="Neo4j",
         ref="procsvc/case_projection.py:16-35,61-69,76-103"),
  ],
  ends=["FUXA 경보 램프·문구(현장)", "TimescaleDB alerts → Grafana 경보 표·주석", "agent 가이드 카드·조치 카드(legacy)", "process Incident 개시·CLEAR 반영 → 재관측 판정", "instance 인스턴스 시작(inst)", "Neo4j Incident(선례 질의 기반)"],
  loss=["held 패턴은 TS1 tick에서만 평가 → TS1이 무효·지연이면 hold 중단·경보 없음; 입력 중 하나라도 STALE이면 그 tick 판정 안 함",
        "Neo4j 카탈로그 장애 시 RAISED가 아닌 후보 hold 중단(새 경보 지연)",
        "detector 재시작 시 hold 경과 시간은 이어지지 않음(interrupt)",
        "cmd-gateway·agent·process(legacy) 그룹은 첫 시작 latest → 이전 경보 무시",
        "FUXA는 설비당 retained 마지막 경보 1건만 보임(다른 패턴 경보가 덮어씀)",
        "sink: CLEAR evidence 버림; 같은 alertId RAISE 재전송(at-least-once)은 raised_at을 덮어씀",
        "process legacy가 꺼진 동안 온 CLEAR는 유실 → cleared=False로 재관측 실패(MITIGATION_FAILED)",
        "LOW_PRESSURE_TRIP·HIGH_VIBRATION_TRIP은 AnomalyPattern 노드·회복 기준이 없어 원인 추론 없이 triage/ESCALATED"],
)

LINEAGE["cmd"] = dict(
  title="조치 카드 → 판단 → 명령 → 결과 → 작업지시",
  origin="agent cardlib.build_card(가이드 카드, agentsvc/card.py:139-153) + decidelib.decide(조치 카드 판단, agentsvc/decide.py:173-254); instance 모드는 task:diagnose~task:rank 출력이 같은 자리를 채움",
  hops=[
    dict(branch="본선", step="1", where="agent → process POST /api/incidents (legacy)", how="HTTP JSON, timeout 10 s, 에이전트의 첫 쓰기",
         fmt="JSON",
         fields="incident(null) · alert · freshness · causes[{id,name,failureModeId,failureMode,prior,score,evidence[]}] · topCause · failureMode · withheld · evidence_status · recommended[{code, actionId, name, kind, relation, description, param, value, paramRange, actuatorId, resource, constraints, skillId, sop{id,name,steps[{id,order,text,manual}]}}] · skills[] · citations[] · summary · summarySource",
         change="최상위 원인의 SOP 스킬 액션을 code별 1건으로 평탄화(먼저 나온 스킬 값 사용), kind command/work_order/purchase; LLM 있으면 summary 대체; guardrail이 writes·cmdId·expiresAt 등 명령 필드 금지",
         keep="run 메모리", ref="agentsvc/main.py:38-42,88-124; agentsvc/card.py:64-153; agentsvc/guardrail.py:5-53"),
    dict(branch="본선", step="2", where="process · create_incident → machine.Incident.from_card → on_card", how="이벤트 루프, 같은 alertId 있으면 duplicate 응답(instance 모드면 빈 카드를 채움)",
         fmt="파이썬 dataclass",
         fields="id(INC-MMDD-NN-hex4) · asset · alert_id · card · state · recovery_policy{pattern, criterion, definition, version} · history · cmd_id · expires_at · approved_by · actions · ack · cleared · work_order · work_order_request",
         change="card.alert에서 asset·alert_id 추출, card.incident=id; 회복 기준 있으면 AWAITING_APPROVAL, 없으면 ESCALATED; audit GUIDE_SUBMITTED{alertId, topCause, citations 개수}",
         keep="incidents 메모리 + /data/process.sqlite3 snapshot(전체 JSON 매번 재기록)", ref="procsvc/main.py:494-534; procsvc/machine.py:32-107; procsvc/store.py:51-60"),
    dict(branch="본선", step="3", where="agent → process POST /api/decisions", how="decide(do_submit=True): DMN(Neo4j t3_dmn) 후보 → 규정 → 예측 → BSC → 선례 → 순위 → guardrail.check_cards 후 제출",
         fmt="JSON",
         fields="id(DEC-MMDD-NNN-hex4) · schema v2 · scenario{id,name,pattern,cause,failureMode} · asset · origin{kind, alertId, incident, pattern, cause, failureMode} · recommended · explanation · options[{id, sopId, name, kind, description, relation, approver{id,name,level}, actions[{id,code,name,kind,param,min,max,value,seq,target,targetName}], steps, forecast[], gains, losses, tradeoffEvaluation, violations, penalties, warnings, feasible, selectedBy, precedent, facts, production, forecastContext, policy_sha256, rankingEvidence, score, scoreParts, rank}] · rankRule · roles{id:{name,level,dept}} · facts · provenance · applicable",
         change="process _store_decision이 Incident(asset·pattern·AWAITING_APPROVAL) 검사 후 decisions.new: state PENDING_APPROVAL · created · chosen · approvedBy · approvedRole · override · executions[] · history[] 추가; audit DECISION_SUBMITTED",
         keep="book 메모리 + process.sqlite3 snapshot(schema v2만 복원)", ref="agentsvc/decide.py:60-64,186-248; agentsvc/cards.py:153-238; procsvc/main.py:746-806; procsvc/decisions.py:19-23"),
    dict(branch="legacy 승인", step="4", where="portal hitl.js → POST /api/incidents/{id}/decide", how="HTTP JSON; 사람의 카드 선택",
         fmt="JSON", fields="decision · option · by · role · reason · fan_pct · load_pct · review_id",
         change="_commands_of: 선택 SOP의 command 액션 → [{code, <param>: value}](fan_pct·load_pct만 사람이 덮어씀); decisions.approve → plan{option, enterprise[{skill, sop, code, name, system(target), value, param}], ot[...]}; machine._validate_actions가 가이드 카드 recommended의 code·paramRange로 재검사; require_reviewed_commands(검토본 없으면 카드 표시값과 같아야 함); current_approval.check → agent /api/agent/approval-check(사실 15 s 이내 재수집·카드 내용·정책 해시·역할 수준 비교); d에 state APPROVED · chosen · approvedBy · approvedRole · override · reason; work_order_request 저장; audit APPROVAL_CURRENT_CHECK·DECISION_APPROVED",
         keep="book·Incident → process.sqlite3", ref="it/portal/www/hitl.js:202-210; procsvc/main.py:1165-1248,372-376; procsvc/decisions.py:31-50; procsvc/approval_hooks.py:8-18; procsvc/current_approval.py:16-38; agentsvc/approval.py:98-182; procsvc/work_orders.py:24-56"),
    dict(branch="instance 승인", step="4i", where="portal instances.js → POST /api/todolist/{wid}/select → InstanceRuntime.select", how="인스턴스 잠금 안, task:select(formHandler:select_card)만",
         fmt="JSON → SQL 행",
         fields="process_approval_outbox(todo_id, proc_inst_id, decision_id, payload{plan{option, enterprise, ot, _snapshot}, decision, option, by, role, reason, commands, asset, incident}, status, attempts, results, error, history) · 변수 commands · chosen_option(kind) · approved_by · approved_role · 출력 chosen_skill · chosen_skill_kind",
         change="같은 approve·validate를 사본에 적용; kind = command 액션 있으면 control 아니면 work_order; 붙은 타이머 취소; deliver_approval이 WO_CREATE 외 기업 항목 실행 → DELIVERED → task:select DONE → gw:control → task:command(SUBMITTED 서비스)",
         keep="Supabase todolist·bpm_proc_inst·process_approval_outbox", ref="procsvc/instances.py:458-523,974-989; procsvc/approval_delivery.py:122-167; procsvc/approval_hooks.py:70-130; it/supabase/migrations/20261004000005_approval_outbox.sql"),
    dict(branch="본선", step="5", where="process · machine.on_approve (legacy 직접 / instance는 _run_command → hooks.approve_commands → main._approve_incident)",
         how="instance는 단일 승인 판단·현재 조건 재검사·검토본 일치 다시 확인",
         fmt="파이썬 dict",
         fields="cmdId · asset · incident · source · actions[{code, fan_pct|load_pct|pump}] · approvedBy · issuedAt · expiresAt",
         change="cmdId = CMD-MMDD-NNNN-hex4, source='HITL', approvedBy = 사람 이름(by), expiresAt = 지금+120 s(벽시계); Incident CMD_ISSUED→AWAITING_ACK, ack 타이머 30 s; audit GUIDE_APPROVED·CMD_PUBLISHED",
         keep="Incident → process.sqlite3(전송 전에 persist)", ref="procsvc/machine.py:110-154; procsvc/main.py:354-369; procsvc/instances.py:704-719; procsvc/definition.py:25-26"),
    dict(branch="본선", step="6", where="process Fx.emit_cmd → Kafka action.cmd", how="persist() 후 run_coroutine_threadsafe(producer.send) — 결과 확인 없음, key=hyd01",
         fmt="JSON", fields="5단계 필드 그대로", change="없음", keep="Kafka action.cmd retention 365일", ref="procsvc/main.py:75-77; it/redpanda/topics.sh:12"),
    dict(branch="connect-sink", step="6a", where="connect-sink · handle_event(action.cmd)", how="UPSERT by cmd_id",
         fmt="SQL 행", fields="actions(cmd_id, incident, asset, actions, approved_by, issued_at, expires_at)",
         change="cmdId→cmd_id, approvedBy→approved_by, issuedAt→issued_at, expiresAt→expires_at; source 버림; 게이트웨이 거부 여부와 무관하게 기록",
         keep="TimescaleDB actions → Grafana 조치 표·'승인 조치' 주석", ref="sink/main.py:95-103; it/grafana/build_dashboard.py:103-105,148-151"),
    dict(branch="본선", step="7", where="cmd-gateway · handle → validate", how="group cmd-gateway(from_latest, auto_commit); 검사 ① 스키마 ② 화이트리스트 ③ 만료(게이트웨이 시계) ④ cmdId 중복(최근 256, 메모리) ⑤ last_status.mode==REMOTE_AUTO + 초당 2건",
         fmt="JSON", fields="cmdId · source · expiresAt · writes[{res, v}]",
         change="actions_to_writes: FAN_SET/FAN_BOOST→FanSpeedSP(fan_pct), LOAD_SET/REDUCE_LOAD→LoadSP(load_pct), RESET→Reset 1, STOP→Stop 1, PUMP_SELECT→PumpSelect(A→0, B→1); asset·incident·actions·approvedBy·issuedAt 버림(asset은 토픽 키); 거부 시 폐기하고 audit만",
         keep="decisions deque 200(메모리)", ref="gw/main.py:58-103; gw/validate.py:17-66; hydcommon/schemas.py:8-54"),
    dict(branch="본선", step="8", where="cmd-gateway → emqx", how="MQTT plant/{k}/cmd/auto, QoS 1, retain=False", fmt="JSON", fields="cmdId · source · expiresAt · writes",
         change="없음", keep="없음", ref="gw/main.py:90-94; hydcommon/topics.py:51-52"),
    dict(branch="본선", step="9", where="plant-sim · edge._on_message → Plant.command → plc.apply_command", how="source는 토픽으로 결정(cmd/auto=HITL), payload의 source 무시",
         fmt="파이썬 dict → CmdResult", fields="cmd_id · result(DONE/REJECTED) · reason · writes_applied",
         change="검사 순서 모드/출처(HITL은 REMOTE_AUTO만) → 만료(PLC 시계) → 최근 32 cmdId → 범위(FanSpeedSP 0~100, LoadSP 60~100, Reset·Stop 1, PumpSelect 0~1) → 인터록(TRIP이면 Reset만, Reset은 TS1<55) → fan_pct·load_pct·pump·PlcState 반영(전부 통과해야 적용)",
         keep="UnitState·PlcState 메모리; 결과는 status로(status 리니지)", ref="plantsim/edge.py:23-26,61-90; plantsim/plc.py:67-134; plantsim/plant.py:100-105"),
    dict(branch="본선", step="10", where="process · on_status(ACK)", how="status 리니지 4·4i", fmt="파이썬 dict", fields="inc.ack{result, reason, interlock, t}",
         change="DONE → ACKED → RE_OBSERVING(900/TIME_SCALE s 타이머) · REJECTED → ESCALATED(PLC REJECTED: reason) · 30 s 무응답 → ESCALATED(ACK_TIMEOUT); instance는 on_incident_update로 task:command 제출",
         keep="Incident", ref="procsvc/machine.py:188-205,221-233; procsvc/instances.py:773-800"),
    dict(branch="본선", step="11", where="process · on_timer('reobs')", how="tag 리니지 11", fmt="파이썬 dict", fields="REOBSERVATION{cleared, tag, value, criterion, passed, extensions}",
         change="cleared AND 회복 기준 → RESOLVED, 아니면 연장(최대 3) 또는 ESCALATED(MITIGATION_FAILED); instance: task:reobserve 출력 recovered → gw:recovered",
         keep="Incident·audit", ref="procsvc/machine.py:234-261; procsvc/instances.py:786-800"),
    dict(branch="본선", step="12", where="process · 작업지시: legacy _complete_legacy_work_order / instance task:work-order → _run_work_order → hooks.exec_enterprise",
         how="저장된 work_order_request 재사용 → exec_skill → HTTP POST enterprise-sim /api/exec(timeout 10 s)",
         fmt="JSON", fields="decision · option · skill('skill:schedule-maintenance') · system · asset · by · params{task, window}",
         change="WO_CREATE → skill:schedule-maintenance(PR_CREATE → skill:procure-part params{supplier, part}); task = '{sop} {SOP 이름} → 작업지시 {value}', window = 선택지 id에 'night'면 '야간 정비창' 아니면 '즉시'; 응답 ref 없으면 실패",
         keep="Incident.work_order_request(재시도용)", ref="procsvc/main.py:660-686,710-738; procsvc/work_orders.py:7-21; procsvc/instance_mode.py:272-285; procsvc/instances.py:730-741"),
    dict(branch="본선", step="13", where="enterprise-sim · /api/exec → MemoryEnterprise(EnterpriseState.execute) | SupabaseEnterprise(ent.exec_skill)",
         how="멱등 키 (decision, skill), 지문 decision·option·skill·asset·params; 같은 키 다른 입력은 409",
         fmt="JSON / SQL 행",
         fields="tx{id TX-MMDD-XXXX, t, system, skill, ref(WO-MMDD-XXXX), detail, asset, decision, option, by, compensates, before, after}; supabase: ent.work_orders(id, asset, task, window_label, decision_id, option_id, requested_by) · ent.transactions(id, t, system, skill, ref, detail, asset, decision_id, option_id, requested_by, fingerprint(md5), before, after)",
         change="work order status '배정됨'; 생성형 스킬은 before=null",
         keep="memory: /data/enterprise.sqlite3 state JSON(_tx 표시 300건, _done 멱등 원장 전체) / supabase: ent 스키마(보존 정책 없음)",
         ref="entsim/main.py:122-138; entsim/state.py:77-105,127-133; entsim/supabase_backend.py:42-60; it/supabase/migrations/20261007000019_transactions_before_after.sql:9-106; 20261003000002_enterprise.sql:133-147"),
    dict(branch="본선", step="14", where="process · work_orders.confirm → machine.on_work_order", how="응답 ref 필수, 같은 Incident에 다른 ref면 거부",
         fmt="파이썬 dict", fields="work_order{ok, ref, detail, id, t, name, sop, requested_value, source, decision}",
         change="WORK_ORDER_CREATED → CLOSED, audit WORK_ORDER_CREATED·INCIDENT_CLOSED; decision executions에 DONE 기록 → state EXECUTED/PARTIAL; instance: task:work-order 출력 {work_order} → ev:closed → 인스턴스 COMPLETED",
         keep="Incident·book → process.sqlite3; instance todolist", ref="procsvc/work_orders.py:67-86; procsvc/machine.py:264-280; procsvc/approval_hooks.py:21-38"),
    dict(branch="Neo4j 선례", step="15", where="process · CaseProjector(DECISION_CASE_Q)", how="APPROVED·EXECUTED·PARTIAL이고 chosen 있는 판단만",
         fmt="Cypher 노드", fields="DecisionCase{id case:DEC-…, decidedAt, reason, followedRecommendation, status, source_incident_id} -CHOSE-> Skill, -DECIDED_BY-> Role, -FOR_INCIDENT-> Incident, -INSTANCE_OF-> Decision",
         change="override → followedRecommendation 반전", keep="Neo4j", ref="procsvc/case_projection.py:37-58,85-93; it/neo4j/templates/t3_precedents.cypher"),
  ],
  ends=["PLC 설정값 변경 → 물리 응답이 tag로 재관측", "TimescaleDB actions(+ack) → Grafana 조치 표·주석", "process Incident/판단 상태 → 포털",
        "기업 원장 transactions·work_orders(CMMS 작업지시)", "Neo4j DecisionCase → 같은 고장 유형 다음 판단의 선례 점수", "audit"],
  loss=["Fx.emit_cmd는 전송 결과를 확인하지 않음 → 전송 실패여도 CMD_ISSUED가 남고 30 s 뒤 ACK_TIMEOUT으로 ESCALATED; producer가 아직 None이면 AttributeError",
        "게이트웨이 거부(스키마·화이트리스트·만료·중복·모드·초당 2건)는 audit에만 남고 process는 audit를 읽지 않음 → 사건은 ACK_TIMEOUT으로만 끝남(실제 사유는 audit에만)",
        "게이트웨이 그룹 첫 시작 latest·cmdId 기억 256건 메모리; 만료 120 s는 게이트웨이와 PLC가 각자 시계로 판정",
        "PLC 거부 사유(MODE_MISMATCH·EXPIRED·DUPLICATE·OUT_OF_RANGE·INTERLOCK_TRIP·RESET_TOO_HOT·UNKNOWN_RESOURCE) → ESCALATED",
        "_validate_actions는 선택한 판단 옵션이 아니라 가이드 카드 recommended(최상위 원인 스킬 액션 평탄화)로 code·범위를 검사 → 카드에 없는 code의 옵션은 승인 불가",
        "승인 재검사는 사실 나이 15 s·카드/정책 불변 필요 → 조건 변화 시 400/ApprovalReviewRequired로 명령 없음",
        "instance 모드 task:select 타이머 PT10M ÷ TIME_SCALE = 20배속에서 벽시계 30 s → 초과 시 에스컬레이션",
        "process 재시작: 비종결 Incident는 PROCESS_RESTART_REVIEW로 ESCALATED, process_approval_id 없는 APPROVED 판단은 PARTIAL",
        "actions 표: 게이트웨이가 거부한 명령도 '승인 조치'로 기록·주석 표시, ACK는 첫 값 고정",
        "Supabase 멱등 재실행 응답은 to_jsonb(행)이라 키가 decision_id·option_id·requested_by(최초 응답은 decision·option·by)"],
)

LINEAGE["audit"] = dict(
  title="감사 사건(audit)",
  origin="process main._audit (procsvc/main.py:650-656) · Fx.emit_audit ← machine._audit (procsvc/main.py:79-82, procsvc/machine.py:96-97) · cmd-gateway handle (gw/main.py:95-103)",
  hops=[
    dict(branch="process", step="1", where="process · _audit / Fx.emit_audit", how="audit_log.insert(0) 후 500건 초과분 삭제, persist(); 이벤트 루프 또는 워커 스레드",
         fmt="파이썬 dict", fields="t · incident · asset · actor · event · detail",
         change="event 예: GUIDE_SUBMITTED · DECISION_SUBMITTED/APPROVED/DENIED/REJECTED · APPROVAL_CURRENT_CHECK(보고서 전체) · SKILL_EXECUTED/FAILED · WORK_ORDER_FAILED · UNSUPPORTED_ALERT_PATTERN · INCIDENT_OPENED · INSTANCE_STARTED · TASK_COMPLETED/PENDING · SELECT_TIMEOUT · INCIDENT_ENDED_BEFORE_ACTION · AGENT_TASK_CLOSED · SKILL_EDITED/CREATED · DDL_INGESTED · DDL_SOURCE_DRIFT · SCM_SOURCE_SYNCED · MANUAL_INGESTED · MANUAL_ROLLED_BACK · INGEST_CLEARED · (machine) GUIDE_APPROVED · CMD_PUBLISHED · ACK_DONE · ACK_REJECTED · ACK_TIMEOUT · ALERT_CLEARED · REOBSERVATION(_EXTENDED) · UNSUPPORTED_RECOVERY_CRITERION · TIMER_IGNORED · WORK_ORDER_CREATED · INCIDENT_CLOSED · GUIDE_REJECTED · INCIDENT_REOPENED",
         keep="audit_log 메모리 500건 → /data/process.sqlite3 snapshot; GET /api/audit는 100건", ref="procsvc/main.py:49,63-66,612-614,650-656; procsvc/store.py:51-60"),
    dict(branch="process", step="2", where="process → Kafka audit", how="run_coroutine_threadsafe(producer.send) 결과 미확인; _audit는 producer 없으면 생략, Fx는 확인 없이 호출",
         fmt="JSON", fields="t · incident · asset · actor · event · detail",
         change="key = asset_key(asset), _audit는 HYD-01~03 아니면 hyd01 키로", keep="Kafka audit retention 5년", ref="procsvc/main.py:79-82,655-656; it/redpanda/topics.sh:13"),
    dict(branch="cmd-gateway", step="2g", where="cmd-gateway → Kafka audit", how="await prod.send, key=asset_key(asset) 또는 hyd00",
         fmt="JSON", fields="t · incident · actor('cmd-gateway') · event(CMD_FORWARDED|CMD_REJECTED) · detail{cmdId, writes, checks[...]} | {cmdId, check, reason}",
         change="asset 필드 없음", keep="Kafka audit 5년", ref="gw/main.py:84-103"),
    dict(branch="본선", step="3", where="connect-sink · handle_event(audit)", how="savepoint 안 INSERT, sink_offsets와 같은 트랜잭션",
         fmt="SQL 행", fields="audit(id bigserial, time, incident, actor, event, detail jsonb)",
         change="t → time(파싱 실패 시 Kafka 시각); asset 버림", keep="TimescaleDB audit(보존 정책 없음, time DESC 인덱스)",
         ref="sink/main.py:111-115; it/timescaledb/init.sql:54-62"),
    dict(branch="본선", step="4", where="grafana · 감사 로그 표", how="$__timeFilter(time) ORDER BY time DESC LIMIT 50", fmt="Grafana 표",
         fields="time · incident · actor · event · detail::text", change="detail 문자열화", keep="없음", ref="it/grafana/build_dashboard.py:106-107"),
    dict(branch="instance 병행 기록", step="5", where="process/agent-worker · record_events_bulk → Supabase events", how="audit 토픽과 별개",
         fmt="SQL 행", fields="events(id, job_id, todo_id, proc_inst_id, event_type, status, crew_type, data, timestamp)",
         change="timestamp는 DB now()(입력 timestamp 무시)", keep="Supabase", ref="it/supabase/migrations/20261003000001_process_engine.sql:219-231,315-331; procsvc/procdb.py:699-703"),
  ],
  ends=["TimescaleDB audit → Grafana 감사 로그", "process /api/audit(포털)", "Kafka audit 5년 원장"],
  loss=["audit 표에 asset 열이 없어 설비 정보가 사라짐(process 기록에는 있음)",
        "process 전송은 결과 확인 없음 → 브로커 오류 시 Kafka·TimescaleDB에 빠지고 SQLite 500건 안에만 남음",
        "_audit는 시작 직후 producer가 없으면 Kafka 전송 생략",
        "process 메모리/스냅샷은 최근 500건만",
        "게이트웨이 거부 기록은 incident 상태와 연결되지 않음(사건은 ACK_TIMEOUT)"],
)

LINEAGE["manual"] = dict(
  title="매뉴얼 → 지식(KnowledgeSource · ManualSection · Skill · Step)",
  origin="포털 hitl.js 업로드 → process POST /api/kg/manuals/preview (procsvc/manual_api.py:78-91), 원문 바이트는 ManualSources.save가 보관 (procsvc/manual_sources.py:125-160)",
  hops=[
    dict(branch="본선", step="1", where="portal → process POST /api/kg/manuals/preview", how="HTTP JSON", fmt="JSON",
         fields="filename · data(base64, 30 MiB 이하) · document_id(판본 추가 시 UUID)", change="base64 해독", keep="없음", ref="it/portal/www/hitl.js:499-500; procsvc/manual_api.py:78-91"),
    dict(branch="본선", step="2", where="process · ManualSources.save → extract", how="SQLite /data/manuals.sqlite3(PROCESS_STATE_PATH 옆, process-data 볼륨), BEGIN IMMEDIATE",
         fmt="SQL 행(BLOB + JSON 문자열)",
         fields="manual_documents(tenant, id, created_at) · manual_sources(tenant, document_id, sha256, filename, original, extraction{pages[{page, text, sha256}], extractor, media_type, warnings, status}, created_at)",
         change="PDF: pypdf 페이지 텍스트(OCR 없음), 사용자 영역 글리프 → '•'; 빈 페이지 있으면 status OCR_REQUIRED; md/txt: utf-8-sig 또는 cp949 해독; source_id = manual:{document_id}:{sha256}; 같은 해시 재업로드는 replayed",
         keep="SQLite 영구(삭제 경로 없음)", ref="procsvc/manual_sources.py:38-83,97-173; procsvc/main.py:966-969"),
    dict(branch="본선", step="3", where="process · manual_review.proposal(구조화 줄 파서) 미리보기", how="Neo4j에서 FailureMode 목록·문서 head 읽기",
         fmt="JSON", fields="source_id · document_id · filename · batch · previous_batch · method(structured-lines-v2) · status · chars · sections[{ref,title,excerpt,anchor}] · procedures[{id,name,section,anchor,steps,stepCount,suggestedFailureMode}] · warnings",
         change="번호 매긴 SOP·절·단계만 인식, 토큰 겹침으로 고장 유형 제안", keep="없음", ref="procsvc/manual_review.py:22-76; procsvc/manual_api.py:69-76"),
    dict(branch="에이전트 추출", step="4", where="process · POST /api/kg/manuals/sources/{source_id}/extractions → manual_extraction.start",
         how="정의 manual_source_extraction v1.6 불변 등록 → 4만 자 초과면 제목 경계 구간마다 인스턴스 → start_definition(event_id manual-extraction:{source_id}:{request_id}[:구간])",
         fmt="SQL 행(Supabase)", fields="bpm_proc_inst 변수 manual_source(원문 전체 또는 구간 텍스트) · segment · review_feedback / todolist task:extract-manual(agent_orch cliagents, agentMode COMPLETE, tool formHandler:manual_proposal, query [InputData] JSON)",
         change="구간은 페이지 텍스트를 잘라 0부터 다시 셈; 검토 피드백(WRONG·MISSING·OK, 최대 20) 고정", keep="Supabase(보존 정책 없음)",
         ref="procsvc/manual_extraction.py:44-58,123-181; procsvc/manual_segments.py:41-60; procsvc/instances.py:186-226; procsvc/engine.py:368-404"),
    dict(branch="에이전트 추출", step="5", where="agent-worker · Runner.poll_once → run", how="claim_process_workitems(worker) → Claude Code 헤드리스 → outcome.interpret(폼 계약) → save_task_result(final, 소유 확인)",
         fmt="JSON(todolist.output)", fields="text · proposal{source_id, sections, procedures, page_reviews, warnings} · cliagents_session_id",
         change="마지막 메시지에서 JSON 객체 추출, 형식 불일치는 같은 세션에서 최대 2회 교정 후 실패; 상태 SUBMITTED·draft_status COMPLETED",
         keep="Supabase todolist + 작업공간 /workspace(72시간)", ref="worker/runner.py:51-165; worker/outcome.py:36-56; procsvc/procdb.py:645-663"),
    dict(branch="에이전트 추출", step="6", where="process · poll_once → process_workitem → validate_result(validate_proposal)", how="엔진 claim(engine) 후 인스턴스 잠금",
         fmt="파이썬 dict", fields="proposal",
         change="인용 좌표 문자열 정확 일치·모든 페이지 page_reviews·SOP ID 형식·단계 order 연속 검사; 실패면 피드백 붙여 FB_REQUESTED(3회째 PENDING), 통과면 DONE·변수 proposal → 인스턴스 COMPLETED",
         keep="Supabase", ref="procsvc/instances.py:292-350,374-399; procsvc/manual_extraction.py:61-118"),
    dict(branch="본선", step="7", where="process · GET …/extractions/{instance} → result/_group_result → _preview", how="구간 결과 병합·좌표를 문서 전체 좌표로 이동, Neo4j로 SOP 소유 충돌 조회",
         fmt="JSON", fields="sections · procedures · page_reviews · warnings · source_id · document_id · filename · batch · previous_batch · method(manual-source-proposal-v1) · status · chars · extraction{instance, workitem, session_id, generation, segments} · coverage · conflicts",
         change="batch는 조회할 때마다 새 uuid4; coverage(인용 비율)는 서버 계산", keep="없음", ref="procsvc/manual_extraction.py:220-298; procsvc/manual_api.py:45-57"),
    dict(branch="본선", step="8", where="portal → POST /api/kg/manuals/commit → manual_review.validate", how="그래프 연결 전에 전부 검사(원문 인용 재검증)",
         fmt="JSON → plan dict",
         fields="입력: reviewed · by · source_id · batch · previous_batch · method · extraction · sections · procedures · links{SOP:{failureMode, relation, kind, approver, affects[{target, sign, note}]}} → plan: batch · tenant · document(sha256(tenant):document_id) · source_id · document_id · sha256 · filename · extractor · previous_batch · by · method · sections · procedures[{id, name, section, anchor, steps[{order, text, manual, anchor}], failureMode, relation, kind, approver, affects}] · extraction · page_reviews · candidate_rules",
         change="validate_skill 기본값 kind work_order · relation REMEDIED_BY · approver role:maint-mgr, 이름 80자 초과 거부; 추출 방식이면 현재 인스턴스 결과와 extraction 일치 확인; 고장 유형별 후보 규칙(Rule) 조회",
         keep="없음", ref="procsvc/manual_api.py:114-138; procsvc/manual_review.py:84-191; procsvc/kgadmin.py:111-156; procsvc/skill_graph.py:43-46"),
    dict(branch="본선", step="9", where="process · manual_graph.commit", how="Neo4j execute_write 한 트랜잭션: IngestionControl 잠금 → head·스냅샷 비교 → 소유권 검사 → 기존 소유 노드/관계 삭제 후 재생성",
         fmt="Cypher 노드·관계",
         fields="KnowledgeSource{id ks:manual:{document}:{sha256}, name(filename), kind manual, source_id, document_id, sha256, extractor} · ManualSection{id …:section:{sha256(ref)}, ref, title, excerpt, source_id, citation} · Skill{id skill:{sop 소문자}, name, sopId, kind, description, source_id, citation} · Step{id {skill id}:{order}, order, text, source_id, citation} (모두 _manual_document) / 관계 PART_OF · (FailureMode)-[MITIGATED_BY|REMEDIED_BY]->Skill · (Rule)-[OUTPUTS]->Skill · APPROVED_BY Role · AFFECTS{sign, note} · (System sys:scada|sys:cmms)-[HAS_SKILL]->Skill · HAS_STEP · REFERS_TO · 원장 ManualIngestionBatch{id, tenant, document, previous, fingerprint, status, before, after, plan, receipt, createdAt} · ManualIngestionDocument{id, head, snapshot, tenant}",
         change="anchor → citation(JSON 문자열); page_reviews·warnings·coverage는 노드로 가지 않고 batch.plan JSON에만; audit MANUAL_INGESTED",
         keep="Neo4j(되돌리기는 최신 batch부터)", ref="procsvc/manual_graph.py:21-99,135-203,206-234"),
    dict(branch="소비", step="10", where="agent t2_skills/t3_skills · process SKILL_Q · DMN 후보 규칙", how="Neo4j 읽기",
         fmt="Cypher 결과", fields="skillId · sopId · name · kind · description · approver · actions(CONSISTS_OF) · steps[{id, order, text, manual{id, ref, title, excerpt}}]",
         change="Step.manual → 카드 sop.steps[].manual, citations에 manual ref; Rule OUTPUTS로 dec:action-candidates 후보가 됨", keep="없음",
         ref="it/neo4j/templates/t2_skills.cypher; it/neo4j/templates/t3_skills.cypher; procsvc/main.py:890-909; agentsvc/card.py:76-115"),
  ],
  ends=["Neo4j SOP 지식(가이드 카드 단계·근거 절 인용, DMN 후보 스킬)", "manuals.sqlite3 원문 판본·추출 텍스트", "Supabase 추출 인스턴스·작업 기록", "audit MANUAL_INGESTED"],
  loss=["PDF는 텍스트 추출만(OCR 없음) — 빈 페이지가 하나라도 있으면 추출·적재 모두 거부; 기호 글꼴 문자는 '•'로 바뀜",
        "매뉴얼로 만든 Skill에는 CONSISTS_OF Action이 없음 → kind=control이어도 PLC 명령이 없어 instance에서 chosen_skill_kind=work_order, 생산 영향 keep",
        "SOP 이름 80자 초과·SOP ID 형식 위반·다른 원천이 소유한 SOP 번호는 적재 거부",
        "page_reviews·warnings·coverage는 그래프 노드가 아니라 batch JSON 문자열에만 남음",
        "에이전트 추출은 agent-worker(cliagents 프로필)가 있어야 진행 — AGENT_BRIDGE=legacy 평가기는 task:diagnose만 처리",
        "원문 전체가 bpm_proc_inst 변수와 todolist.query에 그대로 복사(크기 제한은 30 MiB·500쪽·구간 4만 자뿐)",
        "후보 규칙 연결은 고장 유형만으로 고르는 규칙(candidate_rules)에 한정"],
)

LINEAGE["inst"] = dict(
  title="instance 모드: 경보 → source_inbox → bpm_proc_inst → todolist → agent-worker → save_task_result → 다음 Task",
  origin="Kafka alerts RAISE를 process durable 소비자가 원바이트로 받음 (procsvc/main.py:225-272), PROCESS_MODE=instance일 때만 (procsvc/main.py:430-435)",
  hops=[
    dict(branch="본선", step="1", where="process · consume(durable) → kafka_record → _alert_policy_retrying → receive_many", how="group process(earliest, raw_values, 수동 commit), 최대 50건 묶음, 영수증 1건마다 커밋 후 Kafka commit; 정책 조회 실패는 백오프 재시도(offset 미커밋)",
         fmt="SQL 행", fields="process_source_inbox(… kind RAISE, event_key [alert, alertId, RAISE], payload, policy{pattern, route, criterion, definition, version, target}, status PENDING)",
         change="정책을 수신 시점에 고정(이후 정의 변경과 무관)", keep="Supabase(보존 정책 없음)",
         ref="procsvc/source_inbox.py:24-77,121-170; procsvc/main.py:207-272; procsvc/alert_policy.py:25-38"),
    dict(branch="본선", step="2", where="process · _source_loop → SourceDelivery.run_once → claim", how="설비당 살아 있는 claim 1건, lease 60 s(20 s마다 갱신), 0.2 s 간격",
         fmt="SQL 행", fields="status CLAIMED · owner · claim_token · lease_until · attempts · history",
         change="실패 3회 → FAILED(사람 retry), 연결 대기 → WAITING(5 s)", keep="Supabase", ref="procsvc/source_delivery.py:18-49; procsvc/source_inbox.py:205-284"),
    dict(branch="본선", step="3", where="process · InstanceRuntime.receive_alert → start_definition", how="정책 digest 재확인 → event_transaction(advisory lock) → find_event_instance(start_event_id=alertId)로 중복 방지",
         fmt="파이썬 dict → SQL 행",
         fields="bpm_proc_inst(proc_inst_id {def}.{uuid}, proc_def_id, proc_inst_name, status RUNNING, variables_data[{key, name, value}] asset·alert·alert_id·pattern·incident, role_bindings, proc_def_version, start_date, initial_variables, variable_sources, rework_generation 0, flow_state, start_event_id)",
         change="hooks.new_incident가 machine.Incident(빈 카드, recovery_policy) 생성 → incident id를 변수로; audit INCIDENT_OPENED·INSTANCE_STARTED; inbox HANDLED result{instance, incident, definition}",
         keep="Supabase bpm_proc_inst + process.sqlite3(Incident)", ref="procsvc/instances.py:186-267; procsvc/instance_mode.py:200-219; procsvc/engine.py:266-279"),
    dict(branch="본선", step="4", where="process · engine.start → todolist", how="도달 가능한 모든 활동을 TODO로 미리 생성 → task:diagnose 도달",
         fmt="SQL 행",
         fields="todolist(id, proc_inst_id, activity_id, activity_name, status, user_id(sys:agent), username, assignees, tool(formHandler:diagnose), query([Description] [Instruction] [InputData]{pattern, asset, alert}), agent_mode COMPLETE, agent_orch cliagents, reference_ids, version, generation …)",
         change="도달 시 TODO→IN_PROGRESS(서비스 작업은 바로 SUBMITTED), inputData 값을 query에 JSON으로 붙임; 실행 투영 outbox 트리거",
         keep="Supabase todolist, execution_projection_outbox → Neo4j ProcessInstance/WorkItem", ref="procsvc/engine.py:292-311,355-404; it/process/definitions/anomaly_response_v22.json; it/supabase/migrations/20261004000011_execution_projection_outbox.sql"),
    dict(branch="agent-worker", step="5", where="agent-worker · Runner.poll_once → fetch_pending_task", how="claim_process_workitems(kind worker, agent_orch cliagents): IN_PROGRESS·draft 없음 또는 FB_REQUESTED 또는 만료 lease(claim_count<3), 인스턴스 SKIP LOCKED",
         fmt="SQL 행", fields="draft_status STARTED · consumer({worker}:{uuid}) · lease_until(+120 s) · claim_count+1",
         change="없음", keep="Supabase", ref="worker/runner.py:51-56; procsvc/procdb.py:645-649; it/supabase/migrations/20261007000018_worker_lease.sql:14-55"),
    dict(branch="agent-worker", step="6", where="agent-worker · Runner.run", how="context.prepare(고정 정의의 폼·테넌트 MCP) → 작업공간 → .mcp.json → Claude Code stream_exec; 2 s마다 취소 확인, 30 s마다 lease 갱신, 제한 1800 s",
         fmt="CLI 스트림 → events 행", fields="events(job_id run-…, todo_id, proc_inst_id, crew_type, event_type task_started/task_working/task_completed/human_asked…, data)",
         change="질문이면 HUMAN_ASKED로 멈춤(사람 답 → FB_REQUESTED → 재개), 보류 판단이면 task_deferral", keep="Supabase events + /workspace 추적 파일",
         ref="worker/runner.py:78-143,167-257; worker/context.py; worker/bridge.py:103-141"),
    dict(branch="agent-worker", step="7", where="agent-worker · outcome.interpret → repo.save_task_result(final=True, expected_consumer)", how="UPDATE … WHERE consumer=본인 AND status IN_PROGRESS AND draft_status STARTED",
         fmt="SQL 행(jsonb output)", fields="output{text, <폼 필드>, cliagents_session_id} · status SUBMITTED · draft_status COMPLETED · consumer NULL",
         change="폼 필드만 outputs로, 원문 응답은 text; 소유를 잃었으면 저장 안 하고 취소 처리", keep="Supabase todolist",
         ref="worker/runner.py:144-165; worker/outcome.py:19-56; procsvc/procdb.py:651-663"),
    dict(branch="legacy 브리지(AGENT_BRIDGE=legacy)", step="7L", where="process · _legacy_polling → LegacyAssessment.tick (2 s)", how="task:diagnose를 legacy-eval:{hex} 소유로 claim → POST agent /api/agent/evaluate(do_submit=False, 90 s) → draft._legacy_attempt.result 저장 → 판단 DEC-EVAL-{hex} 게시(incident card 갱신 + _create_decision) → save_task_result{cause, failure_mode, guide_card} → _bridge_legacy_agent가 candidates·compliance·rank를 같은 RPC로 채움",
         fmt="JSON → SQL 행", fields="diagnose{cause, failure_mode, guide_card} · candidates{candidates} · compliance{compliance} · rank{decision{recommended, explanation, order}, decision_id}",
         change="에이전트 평가가 EVALUATED 아니면 task_deferral로 보류", keep="Supabase todolist·events, book",
         ref="procsvc/legacy_assessment.py:35-187; procsvc/instance_mode.py:132-149,335-390; agentsvc/main.py:180-188"),
    dict(branch="본선", step="8", where="process · _polling(2 s) → poll_once → claim_submitted → process_workitem", how="claim_process_workitems(kind engine): SUBMITTED·consumer NULL → consumer=process-engine:{host}; 인스턴스 잠금(bpm_proc_inst·todolist FOR UPDATE)",
         fmt="파이썬 dict → SQL 행", fields="variables_data(outputData 키만) · gateway_decisions · status DONE/PENDING · 다음 todolist 행",
         change="고정 폼 검증 → outputData에 선언된 키만 변수로 병합(text·cliagents_session_id는 버림) → 조건 판정 → DONE + 다음 활동 IN_PROGRESS([InputData] 갱신) 또는 PENDING; guide_card면 Incident.card 갱신; 실패 3회 → PENDING",
         keep="Supabase", ref="procsvc/instance_mode.py:152-166; procsvc/instances.py:292-370,401-421; procsvc/engine.py:421-484"),
    dict(branch="본선", step="9", where="다음 Task들", how="diagnose → candidates → compliance → rank(decision, decision_id) → select(사람, 운전원 role:operator, 타이머 PT10M÷TIME_SCALE) → gw:control → command/work-order → reobserve → gw:recovered → work-order → ev:closed",
         fmt="SQL 행", fields="task별 outputData: cause·failure_mode·guide_card / candidates / compliance / decision·decision_id / chosen_skill·chosen_skill_kind / recovered / work_order / note",
         change="서비스 작업(incident:command·incident:reobserve·enterprise:WO_CREATE)은 process가 직접 실행(cmd 리니지); 종료 시 status COMPLETED·end_event", keep="Supabase → Neo4j 실행 투영",
         ref="it/process/definitions/anomaly_response_v22.json; procsvc/instances.py:685-800; procsvc/engine.py:496-566"),
  ],
  ends=["Supabase bpm_proc_inst·todolist·events·process_approval_outbox(인스턴스 이력)", "process Incident·book(명령 경로)", "Neo4j ProcessInstance·WorkItem 실행 투영", "포털 인스턴스 화면·SSE 이벤트 스트림(/api/events/stream)"],
  loss=["PROCESS_MODE=instance일 때만 동작(compose 기본은 legacy, .env는 instance)",
        "정책 조회가 계속 실패하면 offset 미커밋으로 그 뒤 경보 전체가 밀림(/healthz source_policy_error)",
        "agent-worker와 LegacyAssessment가 같은 cliagents 큐를 둘 다 claim할 수 있음 → 먼저 잡은 쪽이 처리",
        "save_task_result 출력 중 outputData에 없는 키는 변수로 가지 않음(todolist.output에만)",
        "task:select 타이머가 20배속에서 30 s → 사람 응답이 늦으면 에스컬레이션",
        "worker lease 3회 만료 → draft FAILED(사람이 닫아야 함)",
        "events.timestamp는 DB now()로 기록(호출자가 준 timestamp 무시)"],
)

# 주의: 문서 · 주석과 코드가 다른 곳
CAUTION = [
  "요청 경로의 'tag_1s → tag_1m → Grafana'는 코드와 다름: Grafana 패널·주석은 모두 tag_1s·feat_1s·alerts·actions·audit만 읽고 tag_1m은 mcp_tsdb/dmn-mcp 질의 도구만 읽음 (it/grafana/build_dashboard.py:30-151)",
  "plantsim/edge.py:3 'plant/{a}/tag/{name} (1 Hz)' — 기본 lite에서는 DaqFilter가 데드밴드·10/30 s 하트비트로 거름",
  "plantsim/edge.py:96-98 reason_display 주석(FUXA용) — FUXA 프로젝트는 reason_text를 바인딩하고 reason_display는 어디서도 안 씀",
  "det/cep.py:8-16 고정 임계·HOLD_S 설명 — 실제 판정은 Neo4j AnomalyPattern TESTS·clearRule·holdSeconds(cep.evaluate/evaluate_pump/evaluate_fan은 테스트에서만 호출)",
  "det/main.py:3 'z-score anomaly score (autoencoder slot)'·init.sql:14 '1 s wave features' — TS1 feat의 mean은 순간값, rms는 항상 NULL, 기준값 고정; lite에서는 파형 feat 없음",
  "ot/fuxa/build_project.py:231 IT ALERT 알람 문구가 모든 패턴에 '쿨러 성능 저하 (Flink CEP RAISE)'로 고정",
  "표시 라벨 표(gw/validate.py:75-77 · build_dashboard.py:120-121 · agentsvc/card.py:118)에 detector가 내는 LOW_PRESSURE_TRIP·HIGH_VIBRATION_TRIP이 없음; 게이트웨이·Grafana 표에는 아무도 내지 않는 TEMP_TRIP이 있음",
  "procsvc/main.py:3-4 '최신 TS1로 재관측' · machine.on_timer 인자 latest_ts1 — 실제는 패턴별 회복 태그(TS1·PS1·VS1)",
  "procsvc/definition.py:13 '15분 재관측'은 시뮬레이션 시간 — 20배속 벽시계 45 s; select 타이머 PT10M도 벽시계 30 s",
  "it/timescaledb/init.sql:39 'actions: approved action.cmd + PLC ACK' — 게이트웨이가 거부한 명령과 FUXA 수동 명령의 ACK(asset NULL)도 들어감",
  "Evidence 이름 '최근 30초·2분·5분'(instances.cypher:243-249)은 벽시계, detector hold 60 s는 시뮬레이션 초",
  "Supabase ent.exec_skill 멱등 재실행 응답은 decision_id·option_id·requested_by 키(최초 응답·메모리 백엔드는 decision·option·by) (migrations/20261007000019:38 vs 104-105)",
  "schema.json Skill.kind 설명은 business를 언급하지만 enum은 control·work_order뿐",
  "record_events_bulk는 이벤트의 timestamp를 무시 — cancel_agent_task가 넘기는 timestamp는 PgRepo에서 사라지고 MemoryRepo에서만 유지 (procsvc/instances.py:545-546, migrations/20261003000001:316-331)",
]
