# -*- coding: utf-8 -*-
"""서비스 속 구조 데이터(2026-10-07 코드 조사, 파일:줄 근거). 형식: INTERNAL[키] = dict(runtime, parts, links, ext, notes)."""
INTERNAL = {}

INTERNAL["sim"] = dict(
  runtime="Python 3.12 · uvicorn 1프로세스 · 스레드 3(HTTP 요청 처리 · sim-loop 1초 주기 · paho-mqtt 네트워크 루프) · 공유 상태는 Plant.lock(threading.RLock) 하나로 보호",
  parts=[
    ("api", "강의용 HTTP API", "ot/plant-sim/plantsim/main.py:1-140", "고장 주입 · 모드 · 수동 쓰기 · 배속 · 초기화 · 상태 · 지표"),
    ("loop", "시뮬레이션 루프(sim-loop 스레드)", "plantsim/edge.py:122-137", "벽시계 1초마다 tick → 태그 · 상태 발행"),
    ("plant", "Plant(설비 3대 + 잠금)", "plantsim/plant.py:43-145", "Unit 3개 보관, 배속만큼 1설비초 소구간 반복"),
    ("fault", "고장 램프", "plantsim/plant.py:15-19,66-75,78-96", "교란 변수 3종을 선형으로 목표까지(기본 300설비초)"),
    ("thermal", "열 모델", "plantsim/thermal.py:1-131", "열의 저울 dTS1/dt · 나머지 18채널 계산 · 파형 함수"),
    ("plc", "soft-PLC", "plantsim/plc.py:1-173", "인터록 3종 · 명령 검사 5단계 · 모드 · ACK(status 내용)"),
    ("daq", "DAQ 필터(수집 프로필)", "plantsim/daq.py:1-39 · common/hydcommon/daq_contract.py", "lite: 6태그 매초 · 데드밴드 · 10/30초 하트비트 · full: 전부+파형"),
    ("edge", "엣지 발행·수신(EdgeX 역할)", "plantsim/edge.py:1-121", "MQTT 클라이언트 plant-sim-edge · 발행 · 명령 수신 · 출처 판정"),
  ],
  links=[
    ("loop", "plant", "함수 호출(Plant.tick, 잠금 안)", "벽시계 1초 → 배속(TIME_SCALE)만큼 1설비초 소구간", "plant.py:57-68 · edge.py:126"),
    ("plant", "fault", "함수 호출(_apply_fault)", "소구간마다 교란 변수 한 칸 이동", "plant.py:62,66-75"),
    ("plant", "thermal", "함수 호출(thermal.step)", "UnitState 갱신(운전 중이 아니면 부하 0)", "plant.py:63 · thermal.py:83-112"),
    ("plant", "plc", "함수 호출(check_interlock)", "소구간마다 TS1>65 · PS1<130 · VS1≥2.0 판정 → TRIP", "plant.py:65 · plc.py:54-66"),
    ("loop", "daq", "함수 호출(DaqFilter.select)", "이번 초에 보낼 태그만 고름", "edge.py:110"),
    ("loop", "edge", "함수 호출(_publish_tags · _publish_waves · _publish_status)", "설비마다 태그 · 파형(full) · 상태를 MQTT로", "edge.py:128-136"),
    ("edge", "plc", "함수 호출(Plant.command → plc.apply_command, 잠금 안)", "cmd/auto(출처 HITL) · cmd/manual(출처 FUXA) 검사 · 적용", "edge.py:61-82 · plant.py:99-104"),
    ("edge", "plc", "함수 호출(Plant.set_mode → plc.set_mode)", "mode 토픽(숫자 0/1/2도 받음)", "edge.py:83-89 · plant.py:106-111"),
    ("api", "fault", "함수 호출(Plant.inject)", "POST /api/fault", "main.py:84-92 · plant.py:78-96"),
    ("api", "plc", "함수 호출(set_mode requester=LOCAL · command source=FUXA)", "POST /api/mode · /api/manual", "main.py:95-114"),
    ("api", "plant", "공유 메모리(Plant.lock)", "POST /api/time_scale(1~200) · /api/reset · GET /api/state", "main.py:117-140"),
    ("api", "edge", "함수 호출(_publish_status)", "HTTP로 바뀐 상태를 바로 발행", "main.py:102,113,138-139"),
  ],
  ext=[
    ("edge", "out", "MQTT 3.1.1 emqx:1883 · 클라이언트 plant-sim-edge · 깨끗한 세션 · 인증 없음 · plant/{k}/tag/{이름} QoS 0", "{t, v, q:'good'} · lite 필터 적용", "edge.py:105-112"),
    ("edge", "out", "MQTT plant/{k}/wave/{PS1|EPS1|FS1} QoS 0", "{t0, hz, v[100 또는 10]} · DAQ_PROFILE=full(또는 PUBLISH_WAVE=1)일 때만", "edge.py:114-120"),
    ("edge", "out", "MQTT plant/{k}/status QoS 1 retain", "mode · state · trip · 설정값 · 교란 변수 · 마지막 명령 ACK · 한글 표시 문구 · sim_t · time_scale", "edge.py:91-103 · plant.py:126-131"),
    ("edge", "in", "MQTT 구독 plant/{k}/cmd/manual · cmd/auto · mode (QoS 1)", "연결될 때 3설비 × 3토픽 구독", "edge.py:51-55"),
    ("api", "both", "HTTP :8000 (호스트 127.0.0.1:8000) · 인증 없음 · CORS *", "/healthz · /metrics · /api/state · /api/fault · /api/mode · /api/manual · /api/time_scale · /api/reset · /docs", "main.py:28,63-140"),
  ],
  notes=[
    "Modbus 같은 장치 통신은 없다. 열 모델 · PLC · DAQ · 엣지는 같은 프로세스 안의 파이썬 모듈이고 함수 호출로 이어진다(plant.py · edge.py).",
    "명령 출처는 페이로드가 아니라 토픽으로 정한다: cmd/auto = HITL, 그 밖 = FUXA(edge.py:23-26).",
    "벽시계 1초 = 설비 TIME_SCALE초(기본 20). 열 모델 안정을 위해 1설비초씩 쪼개 계산한다(plant.py:57-68).",
    "status는 PLC 변화가 없어도 매초 보낸다(예측 검토가 매 틱을 보도록, edge.py:132-135). 연결 직후에도 전체 발행(edge.py:56-57).",
    "명령 처리 뒤에는 결과와 상관없이 status를 즉시 다시 발행한다(edge.py:90).",
    "/api/manual은 '현장 패널'이라 적혀 있지만 출처를 FUXA로 처리해 LOCAL 모드에서는 거부된다(main.py:106-114 · plc.py:76-77).",
    "노이즈는 설비마다 고정 시드 난수(1·2·3)라 재현된다(plant.py:47-48).",
  ],
)

INTERNAL["ing"] = dict(
  runtime="Python 3.12 · uvicorn 1프로세스(app.main:app, 포트 8093) · asyncio 이벤트 루프 1(태스크 2: pump · age_updater) · paho MQTT 네트워크 스레드 1(loop_start) · 동기 def 엔드포인트(/healthz·/metrics·/api/ingest/stats)는 uvicorn/anyio 스레드풀",
  parts=[
    ("mqttc", "paho MQTT 클라이언트", "common/hydcommon/mqtt.py:6-12 · dmz/connect-ingest/app/main.py:54-66,107-110", "emqx 접속·OT 토픽 구독·수신 콜백 실행(별도 스레드)"),
    ("map", "토픽 변환 to_kafka()", "dmz/connect-ingest/app/main.py:34-51 · common/hydcommon/topics.py:59-68", "MQTT 토픽·JSON을 Kafka 토픽·키·값으로 바꿈"),
    ("q", "asyncio 대기열 queue(최대 20000)", "dmz/connect-ingest/app/main.py:30,68-73", "스레드 경계 완충·가득 차면 버리고 dropped 계수"),
    ("pump", "Kafka 송신 태스크 pump()", "dmz/connect-ingest/app/main.py:76-88 · common/hydcommon/kafka.py:28-42", "대기열에서 꺼내 aiokafka로 send(키=설비키)"),
    ("age", "지표 갱신 태스크 age_updater()", "dmz/connect-ingest/app/main.py:91-95", "1초마다 마지막 수신 경과·대기열 길이 게이지 갱신"),
    ("state", "공유 상태 state·지표 Registry", "dmz/connect-ingest/app/main.py:24-29 · common/hydcommon/metrics.py:6-49", "연결 여부·건수·last_ts, 카운터·게이지(잠금 Lock)"),
    ("http", "FastAPI 엔드포인트", "dmz/connect-ingest/app/main.py:98-117 · common/hydcommon/service.py:9-24", "/healthz·/metrics·/api/ingest/stats 응답"),
  ],
  links=[
    ("mqttc", "map", "함수 호출(paho 스레드 안 on_message)", "msg.topic·msg.payload", "dmz/connect-ingest/app/main.py:60-61"),
    ("mqttc", "q", "그 밖(loop.call_soon_threadsafe로 이벤트 루프에 _enqueue 예약)", "(kafka토픽, 설비키, 값) 튜플", "dmz/connect-ingest/app/main.py:65,68-73"),
    ("mqttc", "state", "공유 메모리(잠금 없음, dict 직접 쓰기)", "state['mqtt']=True·state['last_ts']", "dmz/connect-ingest/app/main.py:55,64"),
    ("q", "pump", "asyncio 큐", "await queue.get()로 한 건씩", "dmz/connect-ingest/app/main.py:81"),
    ("pump", "state", "공유 메모리(카운터는 Registry Lock)", "state['kafka']·count 증가·ingest_messages_total", "dmz/connect-ingest/app/main.py:78,84-85"),
    ("age", "state", "공유 메모리(Registry Lock)", "ingest_last_event_age_seconds·ingest_queue_depth 게이지", "dmz/connect-ingest/app/main.py:93-94"),
    ("http", "state", "공유 메모리(Registry.render는 Lock)", "health_fn 결과·state 사본·queue.qsize()", "dmz/connect-ingest/app/main.py:98-100,115-117"),
  ],
  ext=[
    ("mqttc", "in", "MQTT emqx:1883(MQTT_HOST/MQTT_PORT) client_id=connect-ingest clean_session · 구독 plant/+/tag/+ QoS0 · plant/+/wave/+ QoS0 · plant/+/status QoS1", "태그 {t,v,q}·파형 {t0,hz,v[]}·상태 JSON", "dmz/connect-ingest/app/main.py:56 · common/hydcommon/mqtt.py:7-11"),
    ("pump", "out", "Kafka redpanda:9092(KAFKA_BOOTSTRAP) 토픽 plant.tag · plant.wave · plant.status, 키=설비키(hyd01), JSON 직렬화", "{asset,name,t,v,q} · {asset,sensor,t0,hz,v} · status 원문+asset", "dmz/connect-ingest/app/main.py:44-50,83 · common/hydcommon/kafka.py:30-32"),
    ("http", "in", "HTTP :8093 GET /healthz · GET /metrics(Prometheus 텍스트) · GET /api/ingest/stats", "mqtt·kafka·replicated·last_event_age_s / 지표 / state+queue", "dmz/connect-ingest/app/main.py:98-100,115-117 · common/hydcommon/service.py:13-22"),
  ],
  notes=[
    "MQTT 쪽은 paho 스레드, Kafka 쪽은 이벤트 루프라 둘 사이는 call_soon_threadsafe + asyncio.Queue로만 넘긴다 (dmz/connect-ingest/app/main.py:65,68-73)",
    "대기열이 20000건 차면 새 메시지를 버리고 state['dropped']만 올린다. 이 값은 지표가 아니라 /api/ingest/stats에서만 보인다 (dmz/connect-ingest/app/main.py:30,70-72,117)",
    "send 실패 시 경고 로그 후 0.5초 쉬고 다음 건으로 넘어간다. 실패한 메시지는 다시 넣지 않아 유실된다 (dmz/connect-ingest/app/main.py:86-88)",
    "Kafka 생산자는 브로커가 준비될 때까지 2초 간격 무한 재시도. 그동안 대기열만 쌓인다 (common/hydcommon/kafka.py:28-42 · dmz/connect-ingest/app/main.py:77)",
    "MQTT 재접속 지연 1~5초, keepalive 30초. 재접속 때 on_connect가 다시 구독한다 (common/hydcommon/mqtt.py:10-11 · dmz/connect-ingest/app/main.py:54-57)",
    "JSON이 아니거나 형식이 맞지 않는 토픽은 조용히 버린다(지표 없음). 이 서비스는 MQTT로 아무것도 발행하지 않는다 (dmz/connect-ingest/app/main.py:36-43,51,7)",
    "Kafka 키를 설비키로 써서 설비별 순서를 지킨다 (dmz/connect-ingest/app/main.py:6,45-50)",
    "/healthz의 ok는 MQTT 연결 ∧ Kafka 생산자 준비 ∧ pump 태스크 생존일 때만 참이고, 하나라도 끊기면 503이다(A144 35-227) (dmz/connect-ingest/app/main.py:109-117 · common/hydcommon/service.py:15-18)",
    "on_disconnect가 state['mqtt']를 False로 내리고 paho가 스스로 재접속한다. JSON 객체가 아닌 페이로드는 malformed로 세고 버린다(paho 콜백 예외로 네트워크 스레드가 죽던 것, A144 35-228) (dmz/connect-ingest/app/main.py:44-48,65-68)",
  ],
)

INTERNAL["gw"] = dict(
  runtime="Python 3.12 · uvicorn 1프로세스(gw.main:app, 포트 8090) · asyncio 이벤트 루프 1(태스크 1: run 소비 루프, 종료 감시 콜백 _watch) · paho MQTT 네트워크 스레드 1(loop_start, 클라이언트는 모듈 import 때 생성) · 동기 def 엔드포인트는 스레드풀",
  parts=[
    ("mqttc", "paho MQTT 클라이언트(상태·경보 수신)", "dmz/cmd-gateway/gw/main.py:31,34-55,119-121 · common/hydcommon/mqtt.py:6-12", "plant/+/status 기억·옛 보존 경보 표시문 보강 재발행"),
    ("cons", "Kafka 소비 루프 run()", "dmz/cmd-gateway/gw/main.py:58-67 · common/hydcommon/kafka.py:45-62", "action.cmd·alerts 구독, 레코드마다 handle 호출"),
    ("handle", "레코드 분기 handle()", "dmz/cmd-gateway/gw/main.py:70-103", "경보는 중계, 명령은 검증 후 전달/거절"),
    ("validate", "5단 검증 validate()", "dmz/cmd-gateway/gw/validate.py:31-66 · common/hydcommon/schemas.py:25-54", "스키마·허용목록·만료·중복·모드+초당 2건 판정, writes 생성"),
    ("relay", "경보 변환 alert_to_ot()", "dmz/cmd-gateway/gw/validate.py:69-86", "IT 경보를 OT 표시용(level·display_text)으로 변환"),
    ("gstate", "검증 상태 GatewayState", "dmz/cmd-gateway/gw/validate.py:17-21 · dmz/cmd-gateway/gw/main.py:29", "최근 상태(설비별)·본 cmdId 256개·초별 통과 수(메모리)"),
    ("prod", "Kafka 감사 생산자", "dmz/cmd-gateway/gw/main.py:59,95-103 · common/hydcommon/kafka.py:28-42", "CMD_FORWARDED / CMD_REJECTED를 audit로 송신"),
    ("http", "FastAPI 엔드포인트·판정 기록", "dmz/cmd-gateway/gw/main.py:25-30,106-132", "/healthz·/metrics·/api/gateway/log·/api/gateway/status, decisions(최근 200)"),
  ],
  links=[
    ("mqttc", "gstate", "공유 메모리(잠금 없음, paho 스레드가 dict 쓰기·루프 스레드가 읽기)", "last_status[설비ID]=status JSON", "dmz/cmd-gateway/gw/main.py:50-55"),
    ("mqttc", "relay", "함수 호출(paho 스레드)", "보존 경보 → display_text 추가본", "dmz/cmd-gateway/gw/main.py:43-47 · dmz/cmd-gateway/gw/validate.py:80-86"),
    ("cons", "handle", "함수 호출(await)", "ConsumerRecord(topic·value)", "dmz/cmd-gateway/gw/main.py:63-65"),
    ("handle", "relay", "함수 호출", "alerts 값 → OT 표시 페이로드", "dmz/cmd-gateway/gw/main.py:77"),
    ("handle", "validate", "함수 호출", "명령 dict·gstate·현재시각 → Decision(ok·check·reason·mqtt_payload)", "dmz/cmd-gateway/gw/main.py:84"),
    ("validate", "gstate", "공유 메모리(잠금 없음, 같은 루프 스레드)", "last_status 읽기·seen_cmd_ids·per_second 갱신", "dmz/cmd-gateway/gw/validate.py:49-63"),
    ("handle", "mqttc", "함수 호출(루프 스레드에서 paho publish)", "cmd/auto 페이로드·alert 페이로드", "dmz/cmd-gateway/gw/main.py:78,92"),
    ("handle", "prod", "함수 호출(await prod.send)", "audit 레코드", "dmz/cmd-gateway/gw/main.py:95-103"),
    ("handle", "http", "공유 메모리(deque maxlen=200·state dict·Registry Lock)", "판정 기록·forwarded/rejected/alerts_relayed·지표", "dmz/cmd-gateway/gw/main.py:85-89,79-80,93,99"),
    ("cons", "http", "콜백(add_done_callback _watch)", "소비 루프 종료 시 consumer_dead·consumer_error", "dmz/cmd-gateway/gw/main.py:110-114,122"),
  ],
  ext=[
    ("mqttc", "in", "MQTT emqx:1883 client_id=cmd-gateway · 구독 plant/+/status QoS1 · plant/+/alert QoS1", "PLC 상태(mode 포함) · 보존된 옛 경보", "dmz/cmd-gateway/gw/main.py:36-37"),
    ("mqttc", "out", "MQTT plant/{a}/cmd/auto QoS1 retain=false", "{cmdId,source:HITL,expiresAt,writes:[{res,v}]}", "dmz/cmd-gateway/gw/main.py:92 · dmz/cmd-gateway/gw/validate.py:64-65"),
    ("mqttc", "out", "MQTT plant/{a}/alert QoS1 retain=true", "{alertId,pattern,severity,state,level(2/0),t,text,display_text}", "dmz/cmd-gateway/gw/main.py:47,78"),
    ("cons", "in", "Kafka redpanda:9092 토픽 action.cmd · alerts, 그룹 cmd-gateway, auto_offset_reset=latest, 자동 커밋(enable_auto_commit=True)", "승인 명령 · 경보 RAISE/CLEAR", "dmz/cmd-gateway/gw/main.py:60 · common/hydcommon/kafka.py:45-52"),
    ("prod", "out", "Kafka 토픽 audit, 키=설비키(없으면 hyd00)", "{t,incident,actor:cmd-gateway,event:CMD_FORWARDED|CMD_REJECTED,detail}", "dmz/cmd-gateway/gw/main.py:95-103"),
    ("http", "in", "HTTP :8090 GET /healthz · /metrics · /api/gateway/log · /api/gateway/status", "건강·지표·최근 판정 200건·plc_status+seen_cmd_ids 끝 10개", "dmz/cmd-gateway/gw/main.py:106-107,125-132"),
  ],
  notes=[
    "검증 순서는 SCHEMA → WHITELIST → EXPIRED → DUPLICATE → MODE(REMOTE_AUTO 필수, 상태 미수신이면 거절) → RATE_LIMIT(초당 2건, 설비 구분 없이 전체). 첫 실패에서 멈춘다 (dmz/cmd-gateway/gw/validate.py:31-66)",
    "통과 시 MQTT 발행을 먼저 하고 그다음 audit를 보낸다. 거절 명령은 OT로 가지 않고 audit에만 남는다 (dmz/cmd-gateway/gw/main.py:90-103)",
    "중복 판정용 cmdId(최근 256개)·초별 계수·PLC 상태는 메모리에만 있어 재시작하면 사라진다. 재시작 직후 상태를 다시 받기 전 명령은 MODE로 거절된다 (dmz/cmd-gateway/gw/validate.py:17-21,52-54)",
    "경보 중계는 검증 없이(asset 없음·깨진 값만 무시) 표시 전용 보존 메시지로 내보내며 audit를 남기지 않는다 (dmz/cmd-gateway/gw/main.py:72-82)",
    "레코드 처리 예외는 로그만 남기고 다음 레코드로 간다. 자동 커밋이라 실패한 레코드를 다시 읽지 않는다 (dmz/cmd-gateway/gw/main.py:63-67 · common/hydcommon/kafka.py:50)",
    "paho publish·prod.send의 결과(전달 확인)를 기다리거나 검사하지 않는다 (dmz/cmd-gateway/gw/main.py:78,92,95)",
    "/healthz ok는 kafka 연결 and 소비 루프 생존만 본다. MQTT 연결은 판정에 들어가지 않고 state['mqtt']는 끊김 때 False로 바뀌지 않는다 (dmz/cmd-gateway/gw/main.py:35,106-107)",
    "plant/+/alert 구독은 retain 플래그가 붙은(구독 시점 보존) 옛 경보에 display_text가 없을 때만 다시 발행한다 (dmz/cmd-gateway/gw/main.py:43-47 · dmz/cmd-gateway/gw/validate.py:80-86)",
    "Kafka 생산자·소비자 모두 브로커 준비까지 2초 간격 재시도 (common/hydcommon/kafka.py:28-62)",
  ],
)

INTERNAL["sink"] = dict(
  runtime="Python 3.12 · uvicorn 1프로세스(app.main:app, 포트 8094) · asyncio 이벤트 루프 1(태스크 1: run 소비·적재 루프, 종료 감시 콜백 _watch) · psycopg AsyncConnection 1개(autocommit) · MQTT 없음 · 동기 def 엔드포인트는 스레드풀",
  parts=[
    ("cons", "Kafka 소비 루프 run()", "it/connect-sink/app/main.py:155-183 · common/hydcommon/kafka.py:45-62", "getmany(500ms·최대 2000건) → 적재 → 수동 커밋"),
    ("db", "DB 연결 connect_db()", "it/connect-sink/app/main.py:50-62", "TimescaleDB 접속·sink_offsets 표 생성·2초 재시도"),
    ("store", "배치 트랜잭션 store_records()", "it/connect-sink/app/main.py:119-152", "파티션별 DB 오프셋 확인·재전송분 건너뜀·한 트랜잭션에 행+오프셋"),
    ("bulk", "고빈도 일괄 삽입 write_batch()", "it/connect-sink/app/main.py:65-75", "plant.tag·feat.1s를 executemany로 삽입"),
    ("event", "이벤트 upsert handle_event()", "it/connect-sink/app/main.py:78-116", "alerts·action.cmd·plant.status ACK·audit 행 쓰기(세이브포인트)"),
    ("http", "FastAPI 엔드포인트·상태", "it/connect-sink/app/main.py:31-34,186-204", "/healthz·/metrics·/api/sink/stats"),
  ],
  links=[
    ("cons", "db", "함수 호출(await)", "시작 시·OperationalError/InterfaceError 시 재접속", "it/connect-sink/app/main.py:156,170-174"),
    ("cons", "store", "함수 호출(await)", "{TopicPartition: [레코드]} 배치·DB 연결", "it/connect-sink/app/main.py:166"),
    ("store", "bulk", "함수 호출(같은 DB 트랜잭션)", "tag 행 (time,asset,name,value)·feat 행 (time,asset,sensor,mean,rms,slope,score)", "it/connect-sink/app/main.py:137-141,149"),
    ("store", "event", "함수 호출(레코드마다 중첩 트랜잭션=세이브포인트)", "토픽·값·레코드 타임스탬프", "it/connect-sink/app/main.py:144-145"),
    ("cons", "http", "공유 메모리(state dict·Registry Lock)", "db·kafka·last_write·errors·rows, sink_rows_total", "it/connect-sink/app/main.py:158,167-172 · it/connect-sink/app/main.py:69,74,94"),
    ("cons", "http", "콜백(add_done_callback _watch)", "루프 종료 시 consumer_dead·consumer_error", "it/connect-sink/app/main.py:190-199"),
  ],
  ext=[
    ("cons", "in", "Kafka redpanda:9092 토픽 plant.tag · feat.1s · alerts · action.cmd · plant.status · audit, 그룹 connect-sink, auto_offset_reset=earliest, 자동 커밋 끔(배치 적재 후 commit)", "JSON 레코드", "it/connect-sink/app/main.py:36,157,176 · common/hydcommon/kafka.py:45-52"),
    ("db", "both", "PostgreSQL/TimescaleDB PG_DSN=postgresql://hyd:hyd@timescaledb:5432/hyd · 표 sink_offsets(topic,partition_id,next_offset) 생성·읽기·갱신", "파티션별 다음 오프셋(GREATEST로만 증가)", "it/connect-sink/app/main.py:29,53-56,125-128,150-152"),
    ("bulk", "out", "TimescaleDB 표 tag_1s · feat_1s(하이퍼테이블, 고유키 없음) INSERT", "1Hz 태그·1초 특징/점수", "it/connect-sink/app/main.py:68,72-73 · it/timescaledb/init.sql:5-25"),
    ("event", "out", "TimescaleDB 표 alerts(alert_id PK upsert: RAISE 삽입/CLEAR 갱신) · actions(cmd_id PK upsert, status ACK는 ack_result IS NULL일 때만) · audit(INSERT)", "경보·승인 명령·PLC ACK·감사", "it/connect-sink/app/main.py:80-115 · it/timescaledb/init.sql:28-61"),
    ("http", "in", "HTTP :8094 GET /healthz · /metrics · /api/sink/stats", "db·kafka·rows·last_write·errors", "it/connect-sink/app/main.py:186-187,202-204"),
  ],
  notes=[
    "순서: getmany → 한 DB 트랜잭션(행 + sink_offsets) 커밋 → Kafka 오프셋 commit. Kafka 커밋 전에 죽어도 DB의 next_offset보다 작은 오프셋은 건너뛰어 중복 적재를 막는다 (it/connect-sink/app/main.py:119-152,176-179)",
    "DB 연결 오류(OperationalError·InterfaceError)면 연결을 닫고 2초 간격으로 재접속한 뒤 같은 배치를 끝없이 다시 시도한다. 그동안 소비는 멈춘다 (it/connect-sink/app/main.py:164-174,50-62)",
    "레코드 단위 오류(ValueError·TypeError·KeyError·DataError·IntegrityError)는 errors만 올리고 건너뛴다. 이벤트 토픽은 세이브포인트로 그 행만 되돌린다 (it/connect-sink/app/main.py:135-148)",
    "write_batch(executemany)의 예외나 그 밖의 psycopg 오류는 어디서도 잡지 않아 run이 끝나고 /healthz가 503(consumer_dead)이 된다 (it/connect-sink/app/main.py:149,164-174,186-194)",
    "rebalance로 commit이 실패(CommitFailedError)해도 경고만 남기고 DB 체크포인트에 의존한다 (it/connect-sink/app/main.py:177-179)",
    "plant.status는 cmdId와 result가 둘 다 있을 때만 actions의 ACK 칸을 채운다. 명령 행이 없으면 cmd_id만 있는 행을 새로 만든다. 나머지 status는 버린다(오프셋은 진행) (it/connect-sink/app/main.py:104-110)",
    "plant.wave는 구독하지 않는다(파형 특징은 detector가 feat.1s로 만든 것만 적재) (it/connect-sink/app/main.py:36)",
    "시각은 값의 t(ISO)를 쓰고 없거나 깨지면 Kafka 레코드 타임스탬프, 그것도 없으면 현재 시각 (it/connect-sink/app/main.py:39-47)",
  ],
)

INTERNAL["det"] = dict(
  runtime="Python 3.12 · uvicorn 1프로세스(det.main:app, 포트 8092) · asyncio 이벤트 루프 1(태스크 2: run 소비 루프 · poll_catalog 15초 주기) · Neo4j 조회는 asyncio.to_thread 작업 스레드 · SQLite는 루프 스레드에서 동기 호출 · async def 엔드포인트는 루프에서, /healthz·/metrics(동기 def)는 스레드풀",
  parts=[
    ("cons", "Kafka 소비 루프 run()", "it/detector/det/main.py:278-327", "상태 복원·카탈로그 적재 후 plant.tag/wave/status 레코드별 처리·커밋"),
    ("handlers", "입력 처리 on_tag/on_wave/on_status", "it/detector/det/main.py:97-209 · it/detector/det/features.py:6-80 · it/detector/det/observations.py:7-55", "관측 유효성·TS1 기울기·z점수 점수·파형 특징·PLC 트립 감시"),
    ("runtime", "패턴 실행기 PatternRuntime", "it/detector/det/pattern_runtime.py:26-177 · it/detector/det/patterns.py:25-212 · it/detector/det/cep.py:52-91", "Neo4j 정의(TESTS·clearRule·hold)로 TS1 틱마다 4단계 상태기계 평가"),
    ("trip", "PLC 트립 감시 trip_alert()", "it/detector/det/cep.py:38-44,129-144", "PLC state=TRIP 진입/해제를 CRITICAL RAISE/CLEAR로"),
    ("catalog", "카탈로그 갱신 refresh_catalog/poll_catalog", "it/detector/det/main.py:229-264 · it/detector/det/pattern_source.py:1-18", "Neo4j에서 held 패턴 읽기·검증·원자 교체(15초)"),
    ("store", "SQLite 체크포인트·오프셋·아웃박스 Store", "it/detector/det/store.py:7-43 · it/detector/det/main.py:212-227", "상태 스냅샷·처리 오프셋·미전송 경보를 한 트랜잭션에 저장"),
    ("outbox", "경보 송출 drain_alerts()", "it/detector/det/main.py:267-270", "아웃박스 경보를 send_and_wait 후 삭제"),
    ("prod", "Kafka 생산자", "it/detector/det/main.py:297-298 · common/hydcommon/kafka.py:28-42", "feat.1s·alerts 송신"),
    ("http", "FastAPI 엔드포인트·지표", "it/detector/det/main.py:50-55,330-378", "/healthz·/metrics·/api/detector/patterns(·reload)·/api/detector/state"),
  ],
  links=[
    ("cons", "store", "SQLite 파일(동기 호출)", "seen(topic,partition,offset)로 재처리 건너뜀·checkpoint(key)", "it/detector/det/main.py:310-311,322"),
    ("cons", "handlers", "함수 호출(await, mutation_lock 안)", "topic별 레코드 값", "it/detector/det/main.py:312-321"),
    ("handlers", "runtime", "함수 호출(pattern_observe → runtime.observe/invalidate)", "설비·태그·값·이벤트시각·품질 → 상태 전이 이벤트 목록", "it/detector/det/main.py:114-124,159,197"),
    ("handlers", "trip", "함수 호출", "TripState·tripped 여부·trip 사유", "it/detector/det/main.py:207"),
    ("handlers", "prod", "함수 호출(await prod.send, 전달 대기 없음)", "feat.1s 값(TS1 틱·파형)", "it/detector/det/main.py:179-180,191-192"),
    ("handlers", "store", "공유 메모리(pending_alerts 리스트) → checkpoint에서 SQLite outbox로", "RAISE/CLEAR 경보 이벤트", "it/detector/det/main.py:212-226"),
    ("catalog", "runtime", "공유 메모리(mutation_lock·refresh_lock)", "검증된 카탈로그로 생성/replace, 실패 시 source_failed()", "it/detector/det/main.py:243-258"),
    ("catalog", "store", "함수 호출(checkpoint, record 없음)", "교체 직후 런타임 스냅샷", "it/detector/det/main.py:251"),
    ("cons", "outbox", "함수 호출(await)", "시작 시 1회·레코드마다 아웃박스 비우기", "it/detector/det/main.py:307,323"),
    ("outbox", "store", "SQLite 파일", "pending() 읽기·delivered(seq) 삭제", "it/detector/det/main.py:268-270"),
    ("outbox", "prod", "함수 호출(await send_and_wait)", "alerts 레코드", "it/detector/det/main.py:269"),
    ("http", "catalog", "함수 호출(await refresh_catalog)", "POST reload 즉시 갱신", "it/detector/det/main.py:357-360"),
    ("http", "runtime", "공유 메모리(잠금 없이 읽기)", "describe()·설비 상태·관측 보기", "it/detector/det/main.py:352-378"),
    ("cons", "http", "콜백(add_done_callback _watch)", "루프 종료 시 consumer_dead", "it/detector/det/main.py:335-344"),
  ],
  ext=[
    ("cons", "in", "Kafka redpanda:9092 토픽 plant.tag · plant.wave · plant.status(DETECTOR_TOPIC_PREFIX 있으면 접두.tag 등으로 교체), 그룹 detector(또는 접두), auto_offset_reset=latest, 자동 커밋 끔(레코드마다 commit)", "태그·파형·PLC 상태", "it/detector/det/main.py:43-48,299-306,324 · common/hydcommon/kafka.py:45-52"),
    ("prod", "out", "Kafka 토픽 feat.1s, 키=설비키", "{asset,t,sensor,mean,rms,slope,score}", "it/detector/det/main.py:179-180,191-192"),
    ("outbox", "out", "Kafka 토픽 alerts, 키=설비키", "{alertId,asset,pattern,severity,state:RAISE|CLEAR,t,evidence}", "it/detector/det/main.py:269 · it/detector/det/cep.py:47-49"),
    ("catalog", "in", "Neo4j bolt://neo4j:7687(NEO4J_URI, NEO4J_AUTH) DB neo4j · 읽기 트랜잭션(5초): (p:AnomalyPattern{detectionMode:'held', detectorScope})-[:TESTS]->(i:InputData)", "패턴 속성(rule·clearRule·holdSeconds·clearHoldSeconds·slopeWindowSeconds·severity)·TESTS", "it/detector/det/main.py:229-235 · it/detector/det/pattern_source.py:4-18"),
    ("store", "both", "SQLite 파일 DETECTOR_STATE_PATH=/data/detector.sqlite3(볼륨 detector-data, WAL) · 표 checkpoint · offsets · outbox", "런타임·트립 스냅샷 · 처리 오프셋 · 미전송 경보", "it/detector/det/main.py:282 · it/detector/det/store.py:8-17 · compose.yaml:247,255"),
    ("http", "in", "HTTP :8092 GET /healthz · /metrics · /api/detector/patterns · POST /api/detector/patterns/reload · GET /api/detector/state", "건강(kafka·patterns ready)·지표·카탈로그·설비별 상태", "it/detector/det/main.py:330-378"),
  ],
  notes=[
    "레코드 하나의 순서: seen() 확인 → mutation_lock 안에서 처리 → checkpoint(상태+오프셋+경보 아웃박스를 SQLite 한 트랜잭션) → drain_alerts(send_and_wait 후 삭제) → Kafka commit (it/detector/det/main.py:309-324 · it/detector/det/store.py:27-34)",
    "경보는 아웃박스 경유 최소 1회 전달이다. 송신 뒤 delivered 전에 죽으면 같은 alertId·state를 다시 보낸다. feat.1s는 아웃박스를 거치지 않고 전달 확인도 하지 않는다 (it/detector/det/main.py:179,191,267-270)",
    "패턴 평가는 TS1 수신 때만 돈다. 다른 태그는 관측·기울기 창만 갱신한다. 입력 누락·오래됨·기울기 점 부족이면 그 틱은 UNKNOWN으로 보류하고 대기 중인 hold만 취소한다(RAISED는 유지) (it/detector/det/pattern_runtime.py:131-158 · it/detector/det/cep.py:52-58)",
    "hold는 모의 초(이벤트 시각×TIME_SCALE, 기본 20)로 잰다. 패턴 정의마다 holdSeconds·clearHoldSeconds가 따로 있다 (it/detector/det/pattern_runtime.py:165-168 · it/detector/det/main.py:32)",
    "카탈로그는 15초마다와 POST reload 때 다시 읽는다. 검증 실패·Neo4j 불통이면 적용 중인 카탈로그를 유지하고 source_ready=False로 새 후보 판정을 멈추며 /healthz는 503이 된다. 발령된 경보는 CLEAR까지 원래 정의를 쥔다 (it/detector/det/main.py:243-264,330-332 · it/detector/det/pattern_runtime.py:40-50,87-100)",
    "재시작 시 SQLite 체크포인트로 런타임·트립 상태를 복원하고 대기 hold는 취소한다. 저장된 scope·DAQ_PROFILE·TIME_SCALE·grace가 환경과 다르면 RuntimeError로 루프가 끝난다(503) (it/detector/det/main.py:284-293 · it/detector/det/pattern_runtime.py:69-85)",
    "PLC 트립 경보는 Neo4j 정의와 별개로 plant.status의 state=TRIP 진입/해제에서 바로 낸다(hold 없음, CRITICAL). 트립 상태 검사는 PLC_STATE 보고 주기 10초+grace를 넘으면 STALE로 건너뛴다 (it/detector/det/main.py:195-209 · common/hydcommon/daq_contract.py:15-16)",
    "이상 점수는 고정 기준값(TS1 48±1, CE 84±3, VS1 0.6±0.05)의 z점수 RMS/4를 0~1로 자른 값이며 학습(baseline.push)은 호출되지 않는다 (it/detector/det/main.py:58,80-81,174 · it/detector/det/features.py:77-80)",
    "소비 시작은 latest라 그룹 커밋 오프셋이 없으면 과거 데이터를 읽지 않는다. 시작 시 파티션 할당을 0.05초 간격으로 기다린다 (it/detector/det/main.py:299-305)",
    "관측 유효성은 AssetState.observations와 PatternRuntime의 설비별 Observations 두 곳에서 따로 관리한다 (it/detector/det/main.py:74,114-160 · it/detector/det/pattern_runtime.py:19-23,109-118)",
  ],
)

# 주의: 문서·주석과 코드가 다른 곳 — 2026-10-08 정리(A149, 괄호 숫자는 remaining-sweep 항목 35·36의 옛 줄 번호): 이 절의 8건은 모두 A144가 닫음(.evidence/a144/a144-report.md 항목 35·36).
#   detector 시간 설명·cep 독스트링(221·222), sink 독스트링·batch_age 게이지(223·224), gateway 구독 독스트링·CHECKS 단일 원천(225·226), ingest /healthz ok·비객체 페이로드 버림(227·228).

INTERNAL["agent"] = dict(
  runtime="Python 3.12-slim · uvicorn agentsvc.main:app 1프로세스(:8091) · asyncio 이벤트 루프 1개(aiokafka consume 태스크) + 기본 ThreadPoolExecutor(pipeline·replay·/api/agent/decide, run_in_executor) + Starlette/anyio 스레드풀(동기 def 엔드포인트: evaluate·forecast·approval-check·choice-preview·ontology·runs·decisions). MCP 프로토콜 없음: 'mcp_*'는 같은 프로세스 안 파이썬 모듈(requirements에 mcp/fastmcp 없음). 상태는 전부 메모리(재시작 시 소실)",
  parts=[
    ("http", "FastAPI 엔드포인트", "it/agent/agentsvc/main.py:172-355 · common/hydcommon/service.py:9-24", "runs·decide·evaluate·forecast·승인검사·온톨로지 API와 /healthz·/metrics"),
    ("consumer", "Kafka 경보 소비 루프", "it/agent/agentsvc/main.py:150-201", "alerts 토픽 RAISE만 골라 run 생성 후 워커 스레드로 넘김"),
    ("pipeline", "추론 파이프라인·run 기록부", "it/agent/agentsvc/main.py:38-147 · it/agent/agentsvc/runs.py:1-81", "정책→신선도→T1→증거→카드→가드레일→제출, 단계마다 run.step"),
    ("kg", "지식 그래프 리더(mcp_kg)", "it/agent/agentsvc/tools/mcp_kg.py:1-100", "화이트리스트 .cypher 템플릿만 읽기 트랜잭션으로 실행"),
    ("tsdb", "시계열 리더·신선도(mcp_tsdb·mcp_prom)", "it/agent/agentsvc/tools/mcp_tsdb.py:1-150 · it/agent/agentsvc/tools/mcp_prom.py:1-36", "Evidence SQL·최신값·팬 연속운전시간·데이터 신선도 판정"),
    ("card", "가이드 카드·가드레일·LLM 서술", "it/agent/agentsvc/card.py:1-153 · it/agent/agentsvc/guardrail.py:1-71 · it/agent/agentsvc/llm.py:1-79", "원인 점수·카드 조립·인용/범위 검사·선택적 3문장 요약"),
    ("decide", "조치 카드 판단 엔진", "it/agent/agentsvc/decide.py:1-254 · it/agent/agentsvc/cards.py:1-274", "DMN 후보→규정→예측·BSC·선례→순위, DecisionRegistry 보관"),
    ("ent", "업무 사실 리더(mcp_ent·physical)", "it/agent/agentsvc/tools/mcp_ent.py:1-19 · it/agent/agentsvc/tools/physical.py:1-92", "MES/ERP/QMS/CMMS HTTP GET과 ent 물리 바인딩 단일 행 읽기"),
    ("forecast", "조치 예측 모델", "it/agent/agentsvc/forecasting.py:1-104 · common/hydcommon/forecast.py:1-115", "모델 바인딩+신선한 plant.status로 조치별 열·압력·진동 예측"),
    ("approval", "현재 원천 재평가(승인 검사)", "it/agent/agentsvc/approval.py:1-182", "사람이 고른 카드를 현재 규칙·사실로 다시 평가해 허용 여부 보고"),
  ],
  links=[
    ("consumer", "pipeline", "스레드 대기열(asyncio run_in_executor → 기본 ThreadPoolExecutor)", "Run 객체(경보 1건)", "it/agent/agentsvc/main.py:164-169"),
    ("consumer", "pipeline", "공유 메모리(RunRegistry._lock RLock)", "alertId별 run 1개 생성·중복 RAISE 무시", "it/agent/agentsvc/runs.py:46-62"),
    ("consumer", "http", "공유 메모리(state dict, 잠금 없음)", "kafka·neo4j 연결 여부·consumer_dead → /healthz 503", "it/agent/agentsvc/main.py:32,153-155,172-173,191-195"),
    ("http", "pipeline", "함수 호출(동기, anyio 스레드에서 pipeline(run, do_submit=False))", "/api/agent/evaluate 원천 RAISE 경보 → 제출 없는 평가 run", "it/agent/agentsvc/main.py:180-188"),
    ("http", "pipeline", "스레드 대기열(run_in_executor)", "/api/agent/replay 같은 경보 재실행(force_new)", "it/agent/agentsvc/main.py:217-225"),
    ("http", "pipeline", "공유 메모리(RunRegistry._lock; Run 내부 필드는 잠금 없이 워커가 갱신)", "runs 목록·run 상세(steps·card)", "it/agent/agentsvc/main.py:204-214 · it/agent/agentsvc/runs.py:24-35"),
    ("pipeline", "tsdb", "함수 호출", "mcp_prom.freshness(tsdb, asset) · tsdb.evaluate(evidence, asset)", "it/agent/agentsvc/main.py:56,70"),
    ("pipeline", "kg", "함수 호출", "t1_causes(pattern, asset) · t2_skills(top cause)", "it/agent/agentsvc/main.py:65,83"),
    ("pipeline", "card", "함수 호출", "rank_causes·evidence_status·build_card·llm.summarize·guardrail.check", "it/agent/agentsvc/main.py:72-97"),
    ("pipeline", "decide", "함수 호출", "decidelib.decide(kg, decisions, tsdb, …, causes[0]) 제출/비제출", "it/agent/agentsvc/main.py:104-106,128-130"),
    ("http", "decide", "스레드 대기열(run_in_executor) + 함수 호출", "/api/agent/decide 수동 판단(가정 facts, 비제출)", "it/agent/agentsvc/main.py:267-293"),
    ("http", "decide", "공유 메모리(DecisionRegistry._lock; get/all은 잠금 없이 읽음)", "결정 목록·상세", "it/agent/agentsvc/main.py:345-355 · it/agent/agentsvc/decide.py:31-52"),
    ("decide", "kg", "함수 호출", "dmn·inputs·skills·tradeoffs·precedents·suppliers·roles", "it/agent/agentsvc/decide.py:189-228"),
    ("decide", "tsdb", "함수 호출", "센서 최신값 latest · fan100_hours", "it/agent/agentsvc/decide.py:105-133"),
    ("decide", "ent", "함수 호출", "mcp_ent.fetch(MES/ERP/QMS/CMMS) · read_physical(_fact)", "it/agent/agentsvc/decide.py:93-160"),
    ("decide", "forecast", "함수 호출", "forecasting.candidates(kg, asset, skills) → 후보별 예측·컨텍스트", "it/agent/agentsvc/decide.py:206"),
    ("forecast", "kg", "함수 호출", "forecast_model(asset) 설비별 모델 바인딩 1행", "it/agent/agentsvc/forecasting.py:14-20"),
    ("http", "forecast", "함수 호출(anyio 스레드)", "/api/agent/forecast → forecasting.current", "it/agent/agentsvc/main.py:323-332"),
    ("http", "approval", "함수 호출(anyio 스레드)", "/api/agent/choice-preview → preview · /api/agent/approval-check → assess", "it/agent/agentsvc/main.py:314-342"),
    ("approval", "decide", "함수 호출", "decide.gather_facts(strict=True) · cards.evaluate · policy_digest", "it/agent/agentsvc/approval.py:55-78"),
    ("approval", "forecast", "함수 호출", "forecasting.candidates · consent_changes", "it/agent/agentsvc/approval.py:68,133"),
    ("approval", "card", "함수 호출", "guardrail.check_cards(현재 카드)", "it/agent/agentsvc/approval.py:88,132"),
    ("http", "kg", "함수 호출", "온톨로지 graph·template_text·roles·patterns", "it/agent/agentsvc/main.py:236-264"),
  ],
  ext=[
    ("consumer", "in", "Kafka(aiokafka) redpanda:9092 · 토픽 alerts · group agent · latest · auto commit · 시작 실패 시 2초마다 재시도", "경보 JSON(state=RAISE·alertId·asset·pattern)", "it/agent/agentsvc/main.py:154-160 · common/hydcommon/kafka.py:45-62"),
    ("http", "in", "HTTP :8091(호스트 127.0.0.1:8091) /api/agent/{evaluate,decide,forecast,approval-check,choice-preview,runs,replay,decisions} · /api/ontology/*", "process(current_approval·instance_mode)·포털 브라우저 요청", "it/agent/agentsvc/main.py:180-355 · it/process/procsvc/current_approval.py:18,42 · it/process/procsvc/instance_mode.py:133 · it/portal/www/enterprise.js:307"),
    ("http", "out", "HTTP GET /metrics(Prometheus 텍스트) · /healthz", "agent_runs_total{status} · 상태 dict", "common/hydcommon/service.py:13-22 · it/prometheus/prometheus.yml:15-16"),
    ("pipeline", "out", "HTTP GET process:8080/api/alerts/policy?pattern= · HTTP POST process:8080/api/incidents(timeout 10s)", "경보 지원 범위(route) · 가이드 카드 제출 → incident id·state", "it/agent/agentsvc/main.py:38-42,49"),
    ("decide", "out", "HTTP POST process:8080/api/decisions(timeout 10s) · HTTP GET process:8080/api/plant/{asset}/status", "순위 매긴 조치 카드 묶음 · plc_mode/plc_state", "it/agent/agentsvc/decide.py:55-64,113-125"),
    ("forecast", "out", "HTTP GET process:8080/api/plant/{asset}/status(나이 -2~15초만 허용)", "시뮬레이터 모델 입력 스냅숏", "it/agent/agentsvc/forecasting.py:23-35"),
    ("kg", "out", "Bolt neo4j:7687(neo4j 드라이버 5.27, execute_read, 트랜잭션 timeout 5s, 재시도 0) + 로컬 파일 /srv/templates/*.cypher(KG_TEMPLATES)", "T0~T3 템플릿 결과 행", "it/agent/agentsvc/tools/mcp_kg.py:12-37 · it/agent/Dockerfile:6-8"),
    ("tsdb", "out", "PostgreSQL wire timescaledb:5432/hyd · 역할 hyd_timeseries_reader(TSDB_DSN) · default_transaction_read_only · statement_timeout 5000 · 표 tag_1s/feat_1s/tag_1m", "Evidence 스칼라·관측 공백·최신값·FanSpeedSP 이력", "it/agent/agentsvc/tools/mcp_tsdb.py:17-24,44-46,74-150"),
    ("tsdb", "out", "HTTP GET connect-ingest:8093/healthz(timeout 3s)", "ingest ok·큐/지연", "it/agent/agentsvc/tools/mcp_prom.py:9,18-26"),
    ("ent", "out", "HTTP GET enterprise-sim:8095 /mes/orders · /erp/contract · /qms/lots · /cmms/history ?asset=(timeout 5s)", "{system, facts, records} 업무 사실", "it/agent/agentsvc/tools/mcp_ent.py:11-19 · it/agent/agentsvc/decide.py:135-157"),
    ("ent", "out", "PostgreSQL wire ENTERPRISE_READ_DSN(host.docker.internal:54322/postgres, 역할 hyd_enterprise_reader 확인) · read only · statement_timeout 3000ms · ent.<table>", "설비별 단일 행 컬럼 값(물리 InputData)", "it/agent/agentsvc/tools/physical.py:58-92 · common/hydcommon/enterprise.py:5-16"),
    ("card", "out", "HTTPS POST {OPENAI_BASE_URL}/chat/completions 또는 Anthropic SDK messages.create(timeout 기본 8s, 1~30s, 재시도 0)", "슬림 카드 JSON → 한국어 3문장 요약", "it/agent/agentsvc/llm.py:46-79"),
  ],
  notes=[
    "'mcp_kg·mcp_tsdb·mcp_prom·mcp_ent'는 MCP 서버가 아니라 같은 프로세스 안 파이썬 모듈이며 호출은 일반 함수 호출이다. 원격 연결은 각각 Bolt·PostgreSQL wire·HTTP뿐이다 (it/agent/agentsvc/tools/mcp_kg.py:3-4 · it/agent/requirements.txt)",
    "PROCESS_MODE가 'instance'면 consume 루프는 RAISE를 받기만 하고 건너뛴다. 이때 추론은 process가 POST /api/agent/evaluate로 부르고 pipeline이 do_submit=False로 HTTP 스레드에서 동기 실행된다 (it/agent/agentsvc/main.py:27,161-163,180-188)",
    "파이프라인 순서: 경보 정책(route!=response면 WITHHELD) → 신선도(TS1 나이 -2~60초 & ingest ok, 아니면 WITHHELD) → T1 원인 → Evidence SQL → 원인 순위 → 증거 미확인/무지지면 WITHHELD → T2 SOP → 카드·LLM 요약 → 가드레일(위반 시 REJECTED_BY_GUARDRAIL) → POST /api/incidents → state가 AWAITING_APPROVAL일 때만 decide 후 POST /api/decisions (it/agent/agentsvc/main.py:45-142)",
    "같은 alertId의 RAISE는 run 1개만 만든다(최근 200개 보관). evaluate·replay는 force_new로 새 run ID를 만든다 (it/agent/agentsvc/runs.py:39-68)",
    "DB 연결 풀 없음: 시계열·업무 DB는 호출마다 새 psycopg 연결(connect_timeout 5s), Neo4j는 드라이버 1개를 공유하고 질의마다 세션을 연다. 재시도는 없고 실패는 UNKNOWN/QUERY_ERROR로 남긴다 (it/agent/agentsvc/tools/mcp_tsdb.py:44-46,118-121 · it/agent/agentsvc/tools/mcp_kg.py:19-37)",
    "Evidence 판정: SQL 오류·스칼라 아님·데이터 없음·관측 공백(reporting_interval+2초 초과)은 UNKNOWN으로 남기고 거짓으로 세지 않는다. UNKNOWN이 하나라도 있으면 원인 score=None·카드 보류 (it/agent/agentsvc/tools/mcp_tsdb.py:74-125 · it/agent/agentsvc/card.py:42-61)",
    "gather_facts는 변수별로 예외를 잡아 값 None + error로 기록하고 계속한다. strict=True(승인 검사)에서는 센서·PLC 상태 나이 -2~15초를 넘으면 그 사실을 None 처리한다 (it/agent/agentsvc/decide.py:76-170)",
    "LLM 미설정·실패·finish_reason!=stop이면 템플릿 요약으로 대체하고 예외 클래스만 로그에 남긴다 (it/agent/agentsvc/llm.py:46-79)",
    "consume 태스크가 끝나면 done 콜백이 consumer_dead를 세워 /healthz가 503을 낸다 (it/agent/agentsvc/main.py:191-201)",
    "Run 객체 필드(steps·card·status)는 워커 스레드가 잠금 없이 바꾸고 HTTP 스레드가 to_dict로 읽는다. DecisionRegistry.get/all도 잠금 없이 읽는다 (it/agent/agentsvc/runs.py:24-35 · it/agent/agentsvc/decide.py:48-52)",
    "Evidence SQL은 sqlglot guard로 다시 생성한 문장을 %(asset)s 매개변수와 함께 실행한다. 재생성 뒤 자리표시자가 유지되는지는 실행으로 확인하지 않았다(미확인) (it/agent/agentsvc/tools/mcp_tsdb.py:23-24,91)",
  ],
)

INTERNAL["dmnmcp"] = dict(
  runtime="Python 3.12-slim · python -m dmn_mcp.server · FastMCP 2.13.0.2 transport='http'(streamable HTTP, uvicorn, ws 없음) 1프로세스 :8198 경로 /mcp · 도구 함수는 동기 def(FastMCP의 스레드 배치 방식은 코드에서 미확인) · Kafka·LLM 호출 없음 · it/agent/agentsvc 소스를 이미지에 복사해 import(에이전트 HTTP를 부르지 않음)",
  parts=[
    ("mcpsrv", "FastMCP 서버·도구 등록", "it/dmn-mcp/dmn_mcp/server.py:16-115,125-126", "MCP 도구 13개 노출, 인자 스키마(Annotated) 정의"),
    ("health", "헬스 라우트", "it/dmn-mcp/dmn_mcp/server.py:118-122", "Neo4j ping 실패면 503"),
    ("envelope", "결과 봉투", "it/dmn-mcp/dmn_mcp/tools.py:17-42", "예외를 {result:error, error_kind} 로 바꿔 스택 노출 차단"),
    ("dmntools", "DmnTools 파사드", "it/dmn-mcp/dmn_mcp/tools.py:45-132", "diagnose·evaluate_cards·submit_decision 등 agentsvc 호출 조립"),
    ("engine", "판단 엔진(agentsvc 복사본)", "it/agent/agentsvc/decide.py · cards.py · card.py · guardrail.py · forecasting.py · common/hydcommon/forecast.py", "원인 순위·DMN 후보/규정/순위·예측·제출"),
    ("kg", "지식 그래프 리더(mcp_kg)", "it/agent/agentsvc/tools/mcp_kg.py:1-100", "Cypher 템플릿 읽기 실행"),
    ("tsdb", "시계열 리더·신선도", "it/agent/agentsvc/tools/mcp_tsdb.py:1-150 · it/agent/agentsvc/tools/mcp_prom.py:1-36", "Evidence·스키마 설명·가드된 SELECT·신선도"),
    ("prom", "Prometheus API 리더", "it/agent/agentsvc/tools/prometheus.py:1-143", "metadata·series·query/query_range 읽기와 크기 제한"),
    ("ent", "업무 사실 리더", "it/agent/agentsvc/tools/mcp_ent.py:1-19 · it/agent/agentsvc/tools/physical.py:1-92", "enterprise-sim HTTP·ent 물리 바인딩 읽기"),
  ],
  links=[
    ("mcpsrv", "envelope", "함수 호출", "도구마다 enveloped(lambda: …)() 로 감쌈", "it/dmn-mcp/dmn_mcp/server.py:32-115"),
    ("envelope", "dmntools", "함수 호출", "도구 인자 → DmnTools 메서드, 반환값 → ok(document)", "it/dmn-mcp/dmn_mcp/tools.py:27-42"),
    ("mcpsrv", "prom", "함수 호출(tools.prometheus 직접)", "prometheus_metadata·series·query 인자", "it/dmn-mcp/dmn_mcp/server.py:65-81"),
    ("dmntools", "tsdb", "함수 호출", "freshness·evaluate·describe_schema·query", "it/dmn-mcp/dmn_mcp/tools.py:55-61,83-87"),
    ("dmntools", "kg", "함수 호출", "t1_causes·t2_skills·dmn·inputs·precedents·tradeoffs", "it/dmn-mcp/dmn_mcp/tools.py:59-81,120-124"),
    ("dmntools", "engine", "함수 호출", "card.rank_causes/build_card · decide.gather_facts/decide · forecasting.current", "it/dmn-mcp/dmn_mcp/tools.py:62-118"),
    ("dmntools", "engine", "공유 메모리(DmnTools.registry = 자체 DecisionRegistry, threading.Lock)", "evaluate_cards·submit_decision 결정 기록", "it/dmn-mcp/dmn_mcp/tools.py:49 · it/agent/agentsvc/decide.py:31-52"),
    ("engine", "kg", "함수 호출", "DMN 규칙·입력·스킬·상충·선례·역할·공급사·예측 모델 바인딩", "it/agent/agentsvc/decide.py:189-228 · it/agent/agentsvc/forecasting.py:14-20"),
    ("engine", "tsdb", "함수 호출", "센서 최신값·fan100_hours", "it/agent/agentsvc/decide.py:105-133"),
    ("engine", "ent", "함수 호출", "mcp_ent.fetch · read_physical(_fact)", "it/agent/agentsvc/decide.py:93-160"),
    ("health", "dmntools", "함수 호출", "health() → kg.ping · llm.available", "it/dmn-mcp/dmn_mcp/tools.py:131-132"),
  ],
  ext=[
    ("mcpsrv", "in", "MCP streamable HTTP 0.0.0.0:8198 /mcp(호스트 127.0.0.1:8198) · 도구 diagnose·dmn_rules·inputs·gather_facts·timeseries_schema·timeseries_query·prometheus_metadata·prometheus_series·prometheus_query·evaluate_cards·forecast_actions·submit_decision·precedents·tradeoffs", "MCP tools/call 요청(agent-worker의 Claude Code/Codex 등 MCP 클라이언트)", "it/dmn-mcp/dmn_mcp/server.py:29-126 · compose.yaml:431-449"),
    ("health", "in", "HTTP GET :8198/healthz", "{ok, neo4j, llm}", "it/dmn-mcp/dmn_mcp/server.py:118-122 · compose.yaml:453-455"),
    ("kg", "out", "Bolt neo4j:7687(execute_read, timeout 5s) + 로컬 파일 /srv/templates/*.cypher", "T0~T3 템플릿 행", "it/agent/agentsvc/tools/mcp_kg.py:12-37 · it/dmn-mcp/Dockerfile:7-9"),
    ("tsdb", "out", "PostgreSQL wire timescaledb:5432/hyd(hyd_timeseries_reader, read only, statement_timeout 5000, 표 tag_1s/feat_1s/tag_1m, 최대 200행)", "Evidence 스칼라·스키마·질의 행", "it/agent/agentsvc/tools/mcp_tsdb.py:17-72"),
    ("tsdb", "out", "HTTP GET connect-ingest:8093/healthz", "ingest 상태", "it/agent/agentsvc/tools/mcp_prom.py:9,22"),
    ("prom", "out", "HTTP GET prometheus:9090/api/v1/{metadata,series,query,query_range}(timeout 8s, 응답 2MB·200시리즈·20000점 제한)", "PromQL 결과·지표 메타데이터", "it/agent/agentsvc/tools/prometheus.py:39-143 · compose.yaml:440"),
    ("engine", "out", "HTTP GET process:8080/api/plant/{asset}/status · HTTP POST process:8080/api/decisions(submit_decision만)", "PLC 상태·예측 입력 · 조치 카드 묶음", "it/agent/agentsvc/decide.py:55-64,113-125 · it/agent/agentsvc/forecasting.py:23-35"),
    ("ent", "out", "HTTP GET enterprise-sim:8095 /mes/orders·/erp/contract·/qms/lots·/cmms/history", "업무 사실 {system, facts, records}", "it/agent/agentsvc/tools/mcp_ent.py:11-19"),
    ("ent", "out", "PostgreSQL wire ENTERPRISE_READ_DSN(host.docker.internal:54322/postgres, hyd_enterprise_reader)", "ent 물리 바인딩 단일 행 값", "it/agent/agentsvc/tools/physical.py:71-92 · compose.yaml:449"),
  ],
  notes=[
    "agentsvc를 감싸는 방식은 '소스 복사 + import'다. Dockerfile이 it/agent/agentsvc를 /srv/agentsvc로 복사하고 tools.py가 직접 import한다. agent 서비스(8091)와는 네트워크로 통신하지 않는다 (it/dmn-mcp/Dockerfile:9-10 · it/dmn-mcp/dmn_mcp/tools.py:12-14)",
    "DecisionRegistry·Neo4j 드라이버는 이 프로세스 전용 인스턴스다. dmn-mcp에서 만든 결정은 agent의 /api/agent/decisions에 보이지 않는다 (it/dmn-mcp/dmn_mcp/tools.py:46-50)",
    "모든 도구는 예외를 던지지 않는다: KeyError/ValueError/TypeError → INVALID, psycopg SQLSTATE 42xxx → INVALID, 나머지 psycopg 오류와 기타 예외 → UNKNOWN (it/dmn-mcp/dmn_mcp/tools.py:27-42)",
    "쓰기는 submit_decision의 POST process /api/decisions 하나뿐이다. overrides와 함께 제출하면 decide가 ValueError → INVALID로 거절한다 (it/dmn-mcp/dmn_mcp/tools.py:106-118 · it/agent/agentsvc/decide.py:177-178)",
    "diagnose는 agent pipeline과 달리 /api/alerts/policy 경보 정책을 확인하지 않고 LLM 요약도 하지 않는다(카드 summary는 템플릿) (it/dmn-mcp/dmn_mcp/tools.py:53-73)",
    "timeseries_query는 sqlglot guard로 SELECT 1문장·public 스키마 tag_1s/feat_1s/tag_1m·허용 함수(+TIME_BUCKET)만 통과시키고 바깥 LIMIT ≤ 200을 붙인다 (it/agent/agentsvc/tools/mcp_tsdb.py:18-24 · common/hydcommon/sql_read.py:37-76)",
    "prometheus는 compose 'monitor' 프로필, dmn-mcp는 'cliagents' 프로필이다. Prometheus가 없으면 SourceError → UNKNOWN 봉투가 된다 (compose.yaml:263-270,431-437 · it/agent/agentsvc/tools/prometheus.py:47-52)",
    "/healthz는 Neo4j ping만 상태를 정한다. TimescaleDB·process·Prometheus 연결은 검사하지 않는다 (it/dmn-mcp/dmn_mcp/server.py:118-122)",
  ],
)

INTERNAL["entmcp"] = dict(
  runtime="Python 3.12-slim · python -m enterprise_mcp.server · FastMCP 2.13.0.2 transport='http'(streamable HTTP, uvicorn, ws 없음) 1프로세스 :8199 경로 /mcp · 도구 함수는 동기 def · 연결 풀 없음(도구 호출마다 psycopg 연결) · 상태 없음",
  parts=[
    ("mcpsrv", "FastMCP 서버·도구 등록", "it/enterprise-mcp/enterprise_mcp/server.py:19-97,112-113", "업무 DB 읽기 도구 10개 노출"),
    ("health", "헬스 라우트", "it/enterprise-mcp/enterprise_mcp/server.py:100-109", "리더 역할·transaction_read_only=on 확인, 아니면 503"),
    ("reads", "고정 읽기(RPC)", "it/enterprise-mcp/enterprise_mcp/tools.py:17-54", "ent.mes_orders 등 SQL 함수 7개 호출 → 봉투"),
    ("sqlq", "가드된 SQL 질의", "it/enterprise-mcp/enterprise_mcp/tools.py:69-77 · it/enterprise-mcp/enterprise_mcp/sql_guard.py:1 · common/hydcommon/sql_read.py:1-80", "SELECT 1문장 AST 검사·ent 한정·LIMIT 200 후 실행"),
    ("catalog", "카탈로그·DDL 렌더", "it/enterprise-mcp/enterprise_mcp/catalog.py:1-69 · it/enterprise-mcp/enterprise_mcp/tools.py:57-67", "pg_catalog에서 ent 표/열/주석/제약 읽어 DDL 문자열로"),
    ("conn", "전용 리더 연결", "it/enterprise-mcp/enterprise_mcp/server.py:19,23-27 · common/hydcommon/enterprise.py:1-16 · it/enterprise-mcp/enterprise_mcp/tools.py:40-43", "hyd_enterprise_reader 역할 확인·읽기 전용 트랜잭션·5초 제한"),
  ],
  links=[
    ("mcpsrv", "reads", "함수 호출", "tools.read('mes_orders', asset=…) 등 7개", "it/enterprise-mcp/enterprise_mcp/server.py:32-71"),
    ("mcpsrv", "catalog", "함수 호출", "describe_schema() → DDL 문자열 · describe_catalog() → 봉투", "it/enterprise-mcp/enterprise_mcp/server.py:74-86"),
    ("mcpsrv", "sqlq", "함수 호출", "query(sql) · SqlRejected → INVALID, DB 오류 → UNKNOWN", "it/enterprise-mcp/enterprise_mcp/server.py:89-97"),
    ("reads", "conn", "함수 호출(EnterpriseTools._connect 주입 콜러블)", "연결·read only·statement_timeout·search_path", "it/enterprise-mcp/enterprise_mcp/tools.py:37-51"),
    ("sqlq", "conn", "함수 호출", "guard() 통과 문장 실행", "it/enterprise-mcp/enterprise_mcp/tools.py:69-77"),
    ("catalog", "conn", "함수 호출", "CATALOG_SQL 1문장 실행", "it/enterprise-mcp/enterprise_mcp/tools.py:61-67"),
    ("health", "conn", "함수 호출", "current_user·transaction_read_only 조회", "it/enterprise-mcp/enterprise_mcp/server.py:104-107"),
  ],
  ext=[
    ("mcpsrv", "in", "MCP streamable HTTP 0.0.0.0:8199 /mcp(호스트 127.0.0.1:8199) · 도구 mes_orders·erp_contract·erp_inventory·cmms_history·qms_lots·scm_suppliers·ems_demand·describe_schema·describe_catalog·query", "MCP tools/call 요청(agent-worker의 Claude Code/Codex 등 MCP 클라이언트; agent 서비스는 부르지 않음)", "it/enterprise-mcp/enterprise_mcp/server.py:32-113 · compose.yaml:416-429"),
    ("health", "in", "HTTP GET :8199/healthz", "{ok, role, read_only}", "it/enterprise-mcp/enterprise_mcp/server.py:100-109 · compose.yaml:427-429"),
    ("conn", "out", "PostgreSQL wire ENTERPRISE_DSN(기본 host.docker.internal:54322/postgres = Supabase, extra_hosts host-gateway) · 역할 hyd_enterprise_reader", "pg_roles 역할 검사 · 이후 각 부품의 SQL", "it/enterprise-mcp/enterprise_mcp/server.py:19 · common/hydcommon/enterprise.py:5-16 · compose.yaml:425-426"),
    ("reads", "out", "PostgreSQL wire: select ent.<mes_orders|erp_contract|erp_inventory|cmms_history|qms_lots|scm_suppliers|ems_demand>(%s)", "JSON 문서 {system, facts, records}", "it/enterprise-mcp/enterprise_mcp/tools.py:17-25,46-54"),
    ("sqlq", "out", "PostgreSQL wire: 가드된 SELECT on ent.*(최대 200행)", "statement·columns·rows·row_count", "it/enterprise-mcp/enterprise_mcp/tools.py:69-77"),
    ("catalog", "out", "PostgreSQL wire: pg_class/pg_attribute/pg_constraint 메타데이터(ent, SELECT 권한 있는 것만)", "relations JSON → DDL", "it/enterprise-mcp/enterprise_mcp/catalog.py:6-27"),
  ],
  notes=[
    "도구 호출마다 새 연결을 열고 역할이 정확히 hyd_enterprise_reader(슈퍼유저·CREATEROLE·CREATEDB·BYPASSRLS 아님)인지 확인한다. 다르면 RuntimeError (common/hydcommon/enterprise.py:5-16)",
    "모든 DB 작업은 'set transaction read only' · statement_timeout 5000ms · search_path=pg_catalog, ent 안에서 실행된다 (it/enterprise-mcp/enterprise_mcp/tools.py:40-43)",
    "query는 sqlglot로 SELECT/집합연산 1문장만, ent 스키마 표만, 허용 함수 목록만 통과시키고 쓰기·COPY·LOCK·사용자정의 타입을 거절한 뒤 바깥 LIMIT을 200 이하로 덮어쓴다 (common/hydcommon/sql_read.py:37-80)",
    "모든 도구가 guarded로 감싸져 SQL 거절은 INVALID, DB·연결 오류는 UNKNOWN 봉투(첫 줄만)로 나간다. describe_schema도 {result: ok, document: DDL} 봉투다(A144 35-390) (it/enterprise-mcp/enterprise_mcp/tools.py:41-53 · it/enterprise-mcp/enterprise_mcp/server.py)",
    "/healthz는 새 연결에서 read only를 따로 설정하지 않고 transaction_read_only를 읽으므로, DB 역할 기본값이 read only가 아니면 503이 된다(역할 설정은 이 코드에서 미확인) (it/enterprise-mcp/enterprise_mcp/server.py:104-107)",
    "agent 서비스의 업무 사실은 이 서버가 아니라 enterprise-sim HTTP(8095)와 ENTERPRISE_READ_DSN 직접 연결로 읽는다. enterprise-mcp를 부르는 쪽은 MCP 클라이언트(agent-worker 등)다 (it/agent/agentsvc/tools/mcp_ent.py:11-19 · it/agent/agentsvc/tools/physical.py:71-74)",
  ],
)

# 주의: 문서·주석과 코드가 다른 곳 — 2026-10-08 정리(A149, 괄호 숫자는 remaining-sweep 항목 35·36의 옛 줄 번호)
#   닫힘(A144 .evidence/a144/a144-report.md 항목 35·36): agent '유일한 쓰기' 독스트링(385), mcp_* 이름·compose 주석·mcp_prom(386), dmn-mcp 도구 13개·env 목록(388),
#   dmn instructions는 이미 정정돼 있었음(389, server.py:19), enterprise-mcp 봉투·DB 예외·도구 목록(390), sql_guard 독스트링(391), 미사용 PG_DSN·AGENT_BRIDGE 제거·TSDB_DSN(392),
#   죽은 KnowledgeGraph.forecasts() 제거(393), runs.py 상태 주석 EVALUATED(394).
# - 현행(A144 35-395): agent·dmn-mcp에 extra_hosts(host.docker.internal)를 넣고 tests/test_compose_contract.py로 고정했다. Docker Desktop 밖(Linux Engine) 이름 해석 실측은 미검증.
# - 남음(A144 §34 결정: 코드 유지): mcp_ent.py:3 'never hard-codes which system holds a fact'와 달리 decide.py:136-158이 출처별 경로(/mes/orders, /erp/contract, /qms/lots, /cmms/history)를 코드에 고정한다. 독스트링 정정은 미처리.

INTERNAL["proc"] = dict(
  runtime="Python 3.12 · uvicorn 1프로세스(:8080, procsvc.main:app, --workers 없음) · asyncio 이벤트 루프 1개에 상주 태스크: consume(aiokafka 수신·발행) · _case_projection_loop · _ddl_sync_loop · 사건 타이머 fire_timer(명령마다 생성) / PROCESS_MODE=instance면 추가로 _polling(2 s) · _legacy_polling(2 s, AGENT_BRIDGE=legacy) · _source_loop(+접수 1건마다 임대 갱신 태스크) · SSE 연결마다 event_stream 제너레이터 · 블로킹 IO(psycopg·neo4j·urllib)는 asyncio 기본 스레드 풀(run_in_executor·to_thread)과 FastAPI 동기 def 라우트의 스레드 풀에서 실행",
  parts=[
    ("api", "HTTP 계층(사건·판단·인스턴스 라우트)", "procsvc/main.py:348-351,446-635,746-870,1153-1276 · procsvc/instance_mode.py:421-834 · common/hydcommon/service.py:9-24", "포털·에이전트 요청을 받아 각 부품을 호출, /healthz·/metrics"),
    ("kafka", "Kafka 수신·발행 루프", "procsvc/main.py:225-310 · common/hydcommon/kafka.py:28-62", "plant.status·alerts 수신, action.cmd·audit 발행"),
    ("incident", "사건 상태기계·타이머·legacy 승인 실행", "procsvc/machine.py:1-280 · procsvc/definition.py:1-55 · procsvc/decisions.py · procsvc/work_orders.py · procsvc/approval_hooks.py · procsvc/current_approval.py · procsvc/main.py:63-128,354-376,650-743", "Incident 전이, ACK·재관측 타이머, 기업 거래 실행"),
    ("store", "SQLite 사건 스냅샷·투영 아웃박스", "procsvc/store.py:19-79 · procsvc/case_projection_store.py:7-81", "incidents·book·audit 전체 스냅샷과 그래프 투영 의도 저장"),
    ("projector", "사건 그래프 투영 루프", "procsvc/main.py:131-144,190-203 · procsvc/case_projection.py:72-106 · procsvc/knowledge_projection.py:32-68", "아웃박스를 Neo4j Incident·DecisionCase로 반영, 지식 변경 시 재투영"),
    ("kg", "지식 관리·원천 동기화", "procsvc/main.py:147-187,873-1150 · procsvc/manual_api.py:13-150 · procsvc/manual_sources.py · procsvc/manual_extraction.py · procsvc/manual_graph.py · procsvc/graph_ingest.py · procsvc/ddl_sync.py · procsvc/scm_sync.py", "스킬·DDL·매뉴얼 적재, 60 s마다 DDL·SCM·임대 정리"),
    ("source", "원천 접수함·전달(instance 전용)", "procsvc/source_inbox.py:87-296 · procsvc/source_delivery.py:13-62 · procsvc/main.py:312-345", "Kafka·HTTP 원천을 PG에 영속 접수 후 임대로 1건씩 처리"),
    ("runtime", "인스턴스 런타임·엔진 폴링(instance 전용)", "procsvc/instances.py:88-955 · procsvc/engine.py · procsvc/approval_delivery.py · procsvc/rework_runtime.py · procsvc/effect_compensation.py · procsvc/legacy_assessment.py · procsvc/instance_mode.py:109-418", "인스턴스·작업 전이, 승인 전달, 서비스 작업, 경계 타이머"),
    ("repo", "PG 저장소(Supabase)", "procsvc/procdb.py:424-756 · procsvc/approval_store.py · procsvc/rework_store.py · procsvc/effect_store.py · procsvc/projection_repo.py", "ProcessGPT형 표·RPC 호출, 인스턴스 행 잠금 트랜잭션"),
    ("sse", "이벤트 SSE 스트림", "procsvc/instance_mode.py:79-106,538-543", "events 표를 0.7 s마다 읽어 브라우저로 밀어 줌"),
  ],
  links=[
    ("kafka", "incident", "함수 호출(이벤트 루프 안)", "legacy 경로: plant.status ACK→machine.on_status, alerts CLEAR→on_alert, 미지원 RAISE→ESCALATED 사건", "procsvc/main.py:273-309"),
    ("kafka", "source", "asyncio.to_thread(스레드 풀)", "instance 경로: 가져온 묶음(최대 50건)을 receive_many로 영속 접수, 성공분까지만 오프셋 커밋", "procsvc/main.py:238-272"),
    ("kafka", "runtime", "asyncio.to_thread(스레드 풀)", "RAISE 접수 전 경보 정책 조회(alert_policy), 실패 시 1→30 s 백오프 재시도", "procsvc/main.py:207-222,247-248"),
    ("source", "runtime", "asyncio.to_thread(스레드 풀)", "청구한 RAISE 접수→receive_alert→start_definition(인스턴스+사건 개시)", "procsvc/source_delivery.py:33-34 · procsvc/instances.py:245-267"),
    ("source", "incident", "asyncio.to_thread + 인스턴스 잠금(rt._transition)", "CLEAR·ACK 접수→_apply_source_event→machine.on_alert·on_status", "procsvc/source_delivery.py:35-36 · procsvc/main.py:312-332"),
    ("incident", "kafka", "asyncio.run_coroutine_threadsafe(producer.send)", "action.cmd 명령·audit 이벤트 발행(명령 전 persist)", "procsvc/main.py:75-82,650-656"),
    ("incident", "store", "SQLite 파일(Store._lock)", "persist(): incidents·book·audit 전체 JSON 스냅샷 저장 + 바뀐 항목 아웃박스 적재", "procsvc/main.py:63-66 · procsvc/store.py:51-60 · procsvc/case_projection_store.py:26-40"),
    ("store", "projector", "asyncio.Event(case_projection_event) + SQLite 파일(case_projection_outbox, Store._lock)", "저장 시 깨우기 신호, 루프가 아웃박스 배치(20건) 읽고 완료·오류 기록", "procsvc/main.py:131-133,190-203 · procsvc/case_projection_store.py:55-74"),
    ("incident", "runtime", "loop.run_in_executor(스레드 풀, 실행 후 잊음)", "사건 전이마다 on_incident_update→서비스 작업 task:command·task:reobserve 제출", "procsvc/main.py:128 · procsvc/instance_mode.py:173-183 · procsvc/instances.py:773-800"),
    ("runtime", "incident", "콜백(Hooks·ProcessContext) + 공유 메모리(incidents·book dict, 잠금 없음)", "new_incident·update_incident_card·approve_commands(→machine.on_approve)·reopen_incident·exec_enterprise, legacy 평가 결과→_create_decision", "procsvc/instance_mode.py:197-294 · procsvc/main.py:379-384,809-814"),
    ("runtime", "repo", "함수 호출(스레드 풀 안, 호출마다 psycopg 연결 또는 _transition 연결을 threading.local로 공유)", "인스턴스·todolist·events 읽기·쓰기, claim_submitted·fetch_pending_task RPC", "procsvc/instances.py:95-113,352-370 · procsvc/procdb.py:433-475"),
    ("source", "repo", "함수 호출(repo._conn 공유, 접수마다 별도 커밋)", "process_source_inbox·process_source_state 삽입·청구·완료", "procsvc/source_inbox.py:96-170,205-284"),
    ("sse", "repo", "asyncio.to_thread", "list_events_since(커서) 0.7 s 주기 조회", "procsvc/instance_mode.py:85-90 · procsvc/procdb.py:718-724"),
    ("api", "incident", "함수 호출(이벤트 루프) · run_in_executor", "가이드 카드 접수·거부·조치 카드 선택(/decide)·판단 승인·작업지시 재전달", "procsvc/main.py:494-534,582-609,831-870,1197-1276"),
    ("api", "runtime", "loop.run_in_executor(스레드 풀)", "인스턴스 시작·todolist 제출·select·재작업·보상·취소·닫기", "procsvc/instance_mode.py:545-834"),
    ("api", "source", "asyncio.to_thread + 0.2 s 폴링 대기(최대 30 s)", "instance 모드의 POST /api/incidents를 원천 접수로 넣고 처리 완료까지 대기", "procsvc/main.py:501-515 · procsvc/source_delivery.py:51-62"),
    ("api", "sse", "함수 호출(StreamingResponse 제너레이터)", "GET /api/events/stream 연결마다 event_stream 생성", "procsvc/instance_mode.py:538-543"),
    ("api", "store", "asyncio.to_thread", "GET /api/graph-projections 투영 대기 현황", "procsvc/main.py:446-452"),
    ("projector", "repo", "함수 호출(스레드 풀)", "사건 투영 후 enqueue_incident_projections, 지식 변경 시 enqueue_knowledge_projections", "procsvc/main.py:141-144 · procsvc/knowledge_projection.py:55"),
    ("kg", "runtime", "함수 호출(스레드 풀)", "매뉴얼 추출 요청→register_definition·start_definition(에이전트 작업 인스턴스), 결과 조회", "procsvc/manual_api.py:28-67 · procsvc/manual_extraction.py:159-181"),
    ("kg", "repo", "asyncio.to_thread", "60 s 주기 워커 임대 만료 정리 expire_worker_leases", "procsvc/main.py:169-176,182-184"),
  ],
  ext=[
    ("api", "in", "HTTP :8080 (uvicorn, compose 127.0.0.1:8080) /api/incidents·/api/decisions·/api/alerts/policy·/api/plant/{asset}/status·/api/audit·/api/summary·/api/definition·/api/instances·/api/todolist·/api/process/*·/api/agents/status·/healthz·/metrics", "포털(브라우저)·에이전트의 가이드 카드·판단 제출, 사람 승인·작업 제출", "procsvc/main.py:446-870,1183-1276 · procsvc/instance_mode.py:500-834 · compose.yaml:352-382"),
    ("kafka", "in", "Kafka(redpanda:9092) 토픽 plant.status·alerts, 그룹 process (legacy: latest·자동 커밋 / instance: earliest·수동 커밋·원시 바이트)", "PLC ACK·운전 상태, 경보 RAISE·CLEAR", "procsvc/main.py:228-235 · common/hydcommon/topics.py:9-13"),
    ("kafka", "out", "Kafka 토픽 action.cmd·audit (키 hyd01 형식)", "승인된 PLC 명령, 감사 이벤트", "procsvc/main.py:75-82,655-656"),
    ("incident", "out", "PostgreSQL TimescaleDB(timescaledb:5432, PG_DSN) 표 tag_1s SELECT", "재관측 판정용 최신 회복 태그(TS1·PS1·VS1)", "procsvc/main.py:104-113"),
    ("incident", "out", "HTTP enterprise-sim:8095 POST /api/exec · GET /api/transactions?decision= (10 s)", "CMMS 작업지시·ERP 구매요청·보상 거래, 판단별 거래 원장", "procsvc/main.py:387-401,663-686"),
    ("incident", "out", "HTTP agent:8091 POST /api/agent/approval-check · /api/agent/choice-preview (20 s)", "승인 직전 현재 조건 검사, 변경 조치 예측 검토본", "procsvc/current_approval.py:16-55"),
    ("store", "both", "SQLite 파일 /data/process.sqlite3 (WAL·synchronous FULL) 표 snapshot·decision_reviews·case_projection_source·case_projection_outbox·knowledge_projection_checkpoint·projection_repairs", "사건·판단·감사 스냅샷, 검토본, 투영 아웃박스", "procsvc/store.py:20-28 · procsvc/case_projection_store.py:8-24 · procsvc/main.py:422"),
    ("projector", "out", "Neo4j bolt://neo4j:7687 (호출마다 드라이버 생성, execute_write) CaseProjection·Incident·DecisionCase MERGE, 인벤토리 조회", "사건·판단 사례 그래프 투영", "procsvc/main.py:874-887 · procsvc/case_projection.py:9-58 · procsvc/knowledge_projection.py:14-23"),
    ("kg", "both", "Neo4j bolt://neo4j:7687 Skill·Role·FailureMode·InputData·System·ManualSection·Supplier 등", "스킬 편집, DDL·매뉴얼 적재·되돌리기, 규칙 SQL, 동기화 결과", "procsvc/main.py:874-1150 · procsvc/manual_api.py:24-26"),
    ("kg", "in", "PostgreSQL Supabase(SUPABASE_DSN) information_schema.columns · ent.suppliers 읽기", "업무 DB 카탈로그·공급사 마스터", "procsvc/ddl_sync.py:22-23,46-49 · procsvc/scm_sync.py:14,55-59 · procsvc/main.py:147-166"),
    ("kg", "both", "SQLite 파일 /data/manuals.sqlite3 표 manual_documents·manual_sources", "매뉴얼 원본 바이트·판본별 추출 텍스트", "procsvc/main.py:966-969 · procsvc/manual_sources.py:97-112"),
    ("kg", "in", "HTTP :8080 /api/kg/* (skills·catalog·ddl·scm·ingests·rules/sql·ranking-policy·bsc·manuals)", "지식 관리 화면의 요청", "procsvc/main.py:907-1150 · procsvc/manual_api.py:34-150"),
    ("source", "both", "PostgreSQL Supabase 표 process_source_inbox·process_source_state (advisory lock·행 잠금)", "원천 접수 원문·고정 정책·처리 이력, 설비별 최신 상태", "procsvc/source_inbox.py:121-296"),
    ("source", "in", "HTTP :8080 /api/source-events (목록·상세·재시도)", "실패 접수 확인·재처리", "procsvc/main.py:470-491"),
    ("runtime", "out", "HTTP agent:8091 POST /api/agent/evaluate (90 s, 응답 2 MB 한도)", "legacy 브리지: 경보 진단·카드·판단 평가", "procsvc/instance_mode.py:132-149"),
    ("runtime", "out", "HTTP agent-worker:8097 GET /health · /agents (2 s)", "에이전트 워커 상태 모니터링", "procsvc/instance_mode.py:399-418"),
    ("runtime", "out", "Neo4j(record_cypher·query_cypher=_q) INSTANCE_Q·DELETE_INSTANCE_Q·EXECUTION_Q", "ProcessInstance·WorkItem 실행층 투영과 조회", "procsvc/instances.py:891-953 · procsvc/instance_mode.py:294"),
    ("runtime", "in", "로컬 파일 /srv/definitions/anomaly_response_v22.json · alert_triage_v1.json", "프로세스 정의(시작 시 등록)", "procsvc/instance_mode.py:37-38,113-117 · it/process/Dockerfile:7-8"),
    ("repo", "both", "PostgreSQL Supabase 표 proc_def·proc_def_version·bpm_proc_inst·todolist·events·form_def·users·tenants·notifications·process_approval_outbox·process_rework_receipt·process_effect_receipt·execution_projection_outbox, RPC claim_process_workitems·save_task_result·record_events_bulk·cleanup_stale_consumers·renew_task_lease·expire_worker_leases", "인스턴스·작업·이벤트(에이전트 워커와 같은 표 공유)", "procsvc/procdb.py:424-756 · procsvc/approval_store.py:57-89 · procsvc/projection_repo.py:72-134"),
    ("sse", "out", "HTTP SSE text/event-stream GET /api/events/stream (event: history 최대 60건 + data 프레임, 15 s keepalive)", "events 행 실시간 전달", "procsvc/instance_mode.py:79-106,538-543"),
  ],
  notes=[
    "기본은 PROCESS_MODE=legacy(compose 기본값). instance 라우트는 항상 등록되지만 legacy에서는 409를 돌려주고 source·runtime·sse 부품은 동작하지 않는다 (procsvc/main.py:41,351,430-435 · procsvc/instance_mode.py:494-497 · compose.yaml:369)",
    "Kafka 수신은 getmany 250 ms·최대 SOURCE_BATCH_MAX=50건. legacy는 latest부터 자동 커밋, instance는 earliest부터 접수가 커밋된 뒤에만 오프셋 커밋하고 실패 접수부터 1 s 뒤 재시도 (procsvc/main.py:50,228-272)",
    "사건 타이머는 메모리 asyncio 태스크: ACK 30 s(실시간), 재관측 900 sim-s÷TIME_SCALE(20배면 45 s), 값이 기준 안인데 CLEAR 미도착이면 1/3 창씩 최대 3회 연장, 명령 만료 120 s. 다른 명령용으로 예약된 타이머는 무시 (procsvc/definition.py:25-34 · procsvc/machine.py:153,199-201,227-259 · procsvc/main.py:84-101)",
    "재시작하면 타이머가 사라지므로 복원 시 승인 대기·CMMS 대기 외 진행 중 사건은 ESCALATED(PROCESS_RESTART_REVIEW), APPROVED 판단은 PARTIAL로 바꾼다. 명령은 재전송하지 않는다 (procsvc/store.py:62-79)",
    "persist()는 사건 전이·감사마다 incidents·book·audit(최대 500)을 통째로 JSON 직렬화해 SQLite에 덮어쓴다 (procsvc/main.py:63-66,650-654 · procsvc/store.py:51-60)",
    "incidents·book·audit_log 전역 dict의 상태 전이는 machine.STATE_LOCK(RLock) 안에서 하고, Store.save는 STATE_LOCK → Store._lock 순서로 잡아 스냅샷을 찍는다(I/O는 잠금 밖, A143 항목 13) (procsvc/machine.py:29-35 · procsvc/store.py:1-9,51-60)",
    "instance 엔진 폴링은 ENGINE_POLL_INTERVAL_S=2: 승인 전달→SUBMITTED 청구·처리→대기 서비스 재실행→종료 사건 정리→실행층 투영 순, 이어서 legacy 판단 복구·경계 타이머 발화, 150틱(약 5분)마다 오래된 소비자 정리 (procsvc/instance_mode.py:42-44,152-166 · procsvc/instances.py:352-370)",
    "작업 처리 실패는 retry를 올리고 3번째(MAX_RETRIES)에 PENDING으로 막는다. 현재 조건 거부(ApprovalReviewRequired)는 즉시 PENDING (procsvc/instances.py:41,401-421)",
    "인스턴스 전이는 _transition으로 직렬화: PG 트랜잭션에서 bpm_proc_inst 행과 todolist 행을 FOR UPDATE, 같은 스레드 중첩만 허용, 외부 효과(감사·투영·서비스 실행)는 커밋 뒤 실행 (procsvc/instances.py:95-118 · procsvc/procdb.py:460-475)",
    "원천 접수 청구는 설비당 CLAIMED 1건, 임대 60 s를 20 s마다 갱신, 실패 3회면 FAILED, 대응 사건이 아직 없으면 WAITING으로 5 s 뒤 재시도. 접수가 없으면 0.2 s 쉬고 다시 청구 (procsvc/source_inbox.py:205-284 · procsvc/source_delivery.py:14-49 · procsvc/main.py:335-345)",
    "RAISE 경보 정책 조회는 DB 오류 시 1 s→최대 30 s 백오프로 무한 재시도하고 그동안 오프셋을 커밋하지 않으며 /healthz에 source_policy_error를 띄운다 (procsvc/main.py:207-222)",
    "투영 루프는 Event 신호 또는 2 s 시간 초과마다 깨어 KnowledgeReconciler(15 s 간격 인벤토리 다이제스트 비교) 후 아웃박스를 비운다. 실패한 작업은 5 s 뒤 재시도, Incident를 DecisionCase보다 먼저 투영 (procsvc/main.py:190-203 · procsvc/knowledge_projection.py:33-68 · procsvc/case_projection_store.py:55-74)",
    "_ddl_sync_loop는 DDL_SYNC_INTERVAL_S=60마다 DDL 원천 비교 → SCM 공급사 동기화 → 워커 임대 만료 정리를 차례로 실행하고 실패해도 다음 주기로 넘어간다 (procsvc/main.py:179-187)",
    "SSE는 연결마다 0.7 s 주기로 PG를 조회하고 매 조회가 새 psycopg 연결을 연다(autocommit). 15 s 동안 새 이벤트가 없으면 keepalive 주석 프레임 (procsvc/instance_mode.py:79-106 · procsvc/procdb.py:433-440)",
    "/healthz는 kafka 연결 전이거나 consumer_dead·source_receive_error·source_handler_error·source_policy_error가 있으면 503 (procsvc/main.py:348-350,411-415 · common/hydcommon/service.py:13-18)",
    "action.cmd는 이 서비스만 쓴다. 명령 전송 전에 persist로 CMD_ISSUED를 먼저 기록하고 명령 재시도는 하지 않는다 (procsvc/main.py:1-4,75-77 · procsvc/machine.py:1-6)",
    "Neo4j는 _q 호출마다 GraphDatabase.driver를 새로 만들고 닫는다(연결 풀 재사용 없음) (procsvc/main.py:874-887)",
  ],
)

INTERNAL["ent"] = dict(
  runtime="Python 3.12 · uvicorn 1프로세스(:8095, entsim.main:app) · 백그라운드 태스크·스레드 없음 · 모든 라우트가 동기 def라 FastAPI 스레드 풀에서 실행 · 백엔드는 import 시 ENTERPRISE_BACKEND로 하나 고정: memory는 EnterpriseState threading.Lock으로 직렬화+SQLite 저장, supabase는 호출마다 psycopg 새 연결",
  parts=[
    ("api", "HTTP 라우트·백엔드 선택·지표", "entsim/main.py:21-24,64-149", "시스템별 읽기 7종, /api/exec·거래·상태·초기화, 전역 ent 선택"),
    ("mem", "MemoryEnterprise 어댑터", "entsim/main.py:27-61", "data.py 읽기와 state.py 쓰기를 같은 메서드 계약으로 묶음"),
    ("seed", "시드 데이터·시점 계산", "entsim/data.py:1-140", "교육용 MES·ERP·CMMS·QMS·SCM·EMS 값, 납기 등 현재 기준 재계산"),
    ("state", "쓰기 상태·멱등 원장", "entsim/state.py:15-220", "스킬 실행·보상 적용, 판단·스킬 멱등 키, 최근 거래 300건"),
    ("supa", "Supabase ent 백엔드", "entsim/supabase_backend.py:13-89", "ent 스키마 함수·표로 같은 HTTP 계약 수행"),
  ],
  links=[
    ("api", "mem", "함수 호출(전역 ent, BACKEND=memory)", "read·execute·transactions·snapshot·reset·ping", "entsim/main.py:64-73,78-149"),
    ("api", "supa", "함수 호출(전역 ent, BACKEND=supabase)", "같은 6개 메서드", "entsim/main.py:64-73"),
    ("mem", "seed", "함수 호출", "시스템별 읽기 함수, current_order 시각 계산, reset 시 reanchor", "entsim/main.py:32-39,51-58"),
    ("mem", "state", "함수 호출", "execute·transactions·snapshot·reset", "entsim/main.py:31,45-57"),
    ("state", "seed", "함수 호출·모듈 상수 공유(data._ORDERS·_SUPPLIERS·_QMS·_INVENTORY)", "초기 오더, 공급사 이름, 로트, 재고", "entsim/state.py:69,143,149-161"),
    ("supa", "state", "모듈 상수 공유(COMPENSATION_SKILLS)", "보상 스킬이면 ent.exec_compensation, 아니면 ent.exec_skill 선택", "entsim/supabase_backend.py:42-44"),
  ],
  ext=[
    ("api", "in", "HTTP :8095 (compose 127.0.0.1:8095) GET /mes/orders·/erp/contract·/erp/inventory·/cmms/history·/qms/lots·/scm/suppliers·/ems/demand", "에이전트 enterprise 도구의 사실 읽기", "entsim/main.py:87-119 · it/agent/agentsvc/tools/mcp_ent.py:11-18"),
    ("api", "in", "HTTP :8095 POST /api/exec · GET /api/transactions?decision=", "process의 승인된 스킬·보상 실행, 판단별 거래 조회", "entsim/main.py:122-138 · it/process/procsvc/main.py:387-401,663-686"),
    ("api", "in", "HTTP :8095 GET /api/state·/api/transactions · POST /api/reset · /healthz · /metrics", "포털 업무 프로세스 탭(2.5 s), 헬스 점검(5 s)", "entsim/main.py:74-75,136-149 · it/portal/www/enterprise.js:343,448 · it/portal/www/layers.js:10"),
    ("state", "both", "SQLite 파일 ENTERPRISE_STATE_PATH=/data/enterprise.sqlite3 (WAL) 표 state(id=1 JSON 한 행)", "상태·거래 300건·멱등 원장 전체", "entsim/state.py:48-62 · compose.yaml:392"),
    ("supa", "both", "PostgreSQL Supabase(SUPABASE_DSN) 함수 ent.mes_orders 등 읽기 7종·ent.exec_skill·ent.exec_compensation·ent.reset_executions·ent.hours_from_now, 표 ent.transactions·ent.production_orders·ent.work_orders·purchase_requests·shipments·lot_dispositions·ems_actions·ent.assets", "업무 데이터 읽기·쓰기", "entsim/supabase_backend.py:13-18,30-85 · entsim/main.py:64-69"),
  ],
  notes=[
    "기본 백엔드는 memory(compose 기본값). instance 모드와 함께 쓸 때 supabase로 바꾸며 HTTP 계약은 같다 (entsim/main.py:3-7,21 · compose.yaml:393-394)",
    "멱등: decision이 있으면 키는 (decision, skill), 보상 스킬은 (decision, skill, ref). 같은 키에 다른 입력이 오면 idempotency conflict, decision이 없으면 매번 새 거래 (entsim/state.py:84-92,102-103)",
    "거래 피드는 최근 300건으로 자르지만 decision 지정 조회는 멱등 원장(_done) 전체에서 찾는다 (entsim/state.py:100-101,209-216)",
    "memory 백엔드는 execute·reset마다 상태 전체를 JSON 한 행으로 SQLite에 덮어쓰고, 시작 시 그 행을 복원한다 (entsim/state.py:44-62,104)",
    "data._SCENARIO_START는 import 시각이라 재시작하면 납기·출하·정비창 시각이 재시작 시점 기준으로 다시 잡힌다(복원되는 것은 쓰기 상태뿐). 명시적 재설정은 /api/reset의 reanchor (entsim/data.py:15-21 · entsim/main.py:56-58)",
    "보상은 정방향 거래가 남긴 상태 그대로일 때만 적용(작업지시 배정됨·구매요청 승인됨→발주·격리 대기 등), 출하 승인·대체 출하·수요 제어는 되돌릴 수 없음으로 분류 (entsim/state.py:19-31,170-207)",
    "/healthz: memory는 항상 ok, supabase는 ent.assets 건수 조회. 한 번의 healthz가 ping 2회와 transactions() 전체 조회를 함께 실행 (entsim/main.py:74-75 · entsim/supabase_backend.py:79-85)",
    "쓰기 권한 검사 없음: process만 /api/exec를 호출한다는 것은 주석상 약속이고 코드는 인증하지 않는다 (entsim/main.py:6-7,122-133)",
    "지표는 enterprise_reads_total{system}·enterprise_exec_total{system} 두 카운터 (entsim/main.py:22-24,83,131)",
  ],
)

INTERNAL["portal"] = dict(
  runtime="브라우저 단일 페이지(프레임워크·빌드 없음, classic script 14개가 전역 state·API·getJ/postJ·selectTab을 공유, JS 단일 스레드 + setInterval 8개 + EventSource 1개) · 서버는 nginx:1.27-alpine 정적 파일만(127.0.0.1:8088→80, 역방향 프록시 없음) · 브라우저가 각 서비스 호스트 포트를 CORS로 직접 호출",
  parts=[
    ("nginx", "정적 파일 서버", "it/portal/nginx.conf:1-8", "www 파일 제공, SPA 대체 경로, no-cache 헤더"),
    ("config", "서비스 주소표·표시 문구", "it/portal/www/layers.js:1-45 · it/portal/www/ui.js:1-156", "API·LAYERS(호스트명+포트)와 상태 한글 라벨"),
    ("core", "앱 뼈대·설비/이상 화면", "it/portal/www/app.js:1-589", "탭 전환·fetch 래퍼·1/2/5 s 폴링, 결함 시뮬·이상 확인·추세"),
    ("main", "홈 화면", "it/portal/www/main.js:1-183", "흐름도와 실시간 요약(1 s, 공유 state만 읽음)"),
    ("ent", "온톨로지·판단 규칙·업무 프로세스 탭", "it/portal/www/enterprise.js:1-450", "지식 지도, DMN 판단 실행, 판단 승인·기업 시스템 현황"),
    ("hitl", "HITL 카드·BPMN·스킬·매뉴얼·DDL", "it/portal/www/hitl.js:1-581", "legacy 조치 카드 선택, 스킬 편집, 매뉴얼·DDL 적재"),
    ("inst", "프로세스 인스턴스·할일 탭", "it/portal/www/instances.js:1-523 · it/portal/www/instanceSteps.js · it/portal/www/instanceRework.js · it/portal/www/instanceEffects.js · it/portal/www/taskDeferral.js", "인스턴스·todolist 2 s 폴링, 선택·제출·재작업·보상"),
    ("stream", "실시간 이벤트 스트림", "it/portal/www/liveStream.js:1-143", "SSE 구독, 상단 티커, 인스턴스 화면 즉시 재조회"),
    ("adv", "고급 패널(정의 등록·원천 접수)", "it/portal/www/definitionRegistry.js:1-65 · it/portal/www/sourceEvents.js:1-59", "패널을 열 때만 정의 목록·실행, 원천 접수 조회·재시도"),
  ],
  links=[
    ("nginx", "core", "HTTP(정적 파일 로드)", "index.html과 스크립트 14개(?v= 캐시 무효화)를 순서대로 로드", "it/portal/www/index.html:262-275 · it/portal/nginx.conf:6-7"),
    ("config", "core", "공유 전역 상수(API·LAYERS·UI)", "서비스 주소, 헬스 점검 대상, 라벨", "it/portal/www/layers.js:43-45 · it/portal/www/app.js:104,125"),
    ("core", "main", "공유 전역 객체 state", "state.plant·state.incidents를 1 s마다 읽어 요약", "it/portal/www/main.js:137-155 · it/portal/www/app.js:32"),
    ("core", "ent", "전역 함수 재정의(selectTab 래핑) + 공유 state.tab", "탭 진입 시 loadGraph·loadDecisionView·refreshProcess", "it/portal/www/enterprise.js:39-45,448"),
    ("core", "hitl", "공유 전역 state + selectTab 래핑", "state.detail(선택 사건)로 HITL 패널, 탭 진입 시 스킬·매뉴얼·DDL 로드", "it/portal/www/hitl.js:118-122,571-580"),
    ("ent", "hitl", "전역 객체 window.hydEnt", "hitl이 선택 판단(decDetail)을 읽어 BPMN 갱신, 적재 후 hydEnt.loadGraph(true) 호출", "it/portal/www/hitl.js:221-226,380,488 · it/portal/www/enterprise.js:450"),
    ("core", "inst", "selectTab 래핑 + 공유 state.tab", "instances 탭일 때만 load 실행", "it/portal/www/instances.js:17-18,516-518"),
    ("stream", "inst", "전역 객체 window.hydInstances + setTimeout(250 ms)", "작업 전이 이벤트 수신 시 load(true), 행 클릭 시 hydInstancesSelect", "it/portal/www/liveStream.js:15-29,67-70,106"),
    ("adv", "inst", "전역 함수 window.hydInstancesSelect", "실행 시작한 인스턴스를 선택", "it/portal/www/definitionRegistry.js:61-64 · it/portal/www/instances.js:512"),
  ],
  ext=[
    ("nginx", "in", "HTTP :80 (compose 127.0.0.1:8088), 읽기 전용 볼륨 ./it/portal/www", "브라우저의 정적 파일 요청", "it/portal/nginx.conf:1-8 · compose.yaml:402-413"),
    ("core", "out", "HTTP plant-sim :8000 GET /api/state(1 s) · POST /api/fault·/api/mode·/api/manual·/api/reset·/api/time_scale", "설비 상태, 결함 주입·조작", "it/portal/www/app.js:242-272,556"),
    ("core", "out", "HTTP detector :8092 GET /api/detector/state(1 s) · cmd-gateway :8090 GET /api/gateway/log(1 s, 결함 시뮬 탭만)", "탐지 단계, 명령 검증 기록", "it/portal/www/app.js:557,566"),
    ("core", "out", "HTTP process :8080 GET /api/incidents·/api/audit(2 s)·/api/definition(1회)·/api/incidents/{id} · POST /reject·/work-order-retry", "사건 목록·감사·상세", "it/portal/www/app.js:391-406,522-533,574-577"),
    ("core", "out", "HTTP agent :8091 GET /api/agent/runs(2 s)·/api/agent/runs/{id}", "에이전트 실행 기록", "it/portal/www/app.js:390,397,575"),
    ("core", "out", "HTTP 각 서비스 /healthz·외부 UI no-cors 탐침(5 s), Grafana :3000 d-solo iframe(refresh=5s)·/api/health", "헬스 점, 추세 그래프", "it/portal/www/app.js:121-158,537-548 · it/portal/www/layers.js:6-41"),
    ("main", "out", "HTTP agent :8091 GET /api/ontology/graph?asset=HYD-01 (페이지 로드 1회)", "지식 지도 노드·관계 수", "it/portal/www/main.js:133-135,179"),
    ("ent", "out", "HTTP agent :8091 GET /api/ontology/patterns·/api/ontology/graph·/api/ontology/template/{t} · POST /api/agent/decide", "온톨로지 그래프·질의 템플릿·판단 실행", "it/portal/www/enterprise.js:46-60,214,307"),
    ("ent", "out", "HTTP process :8080 GET /api/decisions·/api/decisions/{id} · POST /api/decisions/{id}/approve·/reject (업무 프로세스 탭 2.5 s)", "판단 목록·승인·반려", "it/portal/www/enterprise.js:340-348,417,425,448"),
    ("ent", "out", "HTTP enterprise-sim :8095 GET /api/state·/api/transactions (업무 프로세스 탭 2.5 s)", "기업 시스템 현황·실행 이력", "it/portal/www/enterprise.js:4,343"),
    ("hitl", "out", "HTTP process :8080 GET /api/decisions·/api/decisions/{id}(1.5 s, 이상 확인 탭에서 사건 선택 시)·/api/incidents/{id}(2 s, 업무 프로세스 탭) · POST /api/incidents/{id}/decision-preview·/decide", "조치 카드 검토·선택(legacy)", "it/portal/www/hitl.js:118-132,195-218,221-232"),
    ("hitl", "out", "HTTP process :8080 /api/kg/skills(GET·POST·PUT)·/api/kg/catalog·/api/kg/manuals/*·/api/kg/ddl/preview·/api/kg/ddl/commit·/api/kg/ingests(GET·DELETE)", "스킬·매뉴얼·DDL 지식 관리", "it/portal/www/hitl.js:245-248,314-330,346-563"),
    ("inst", "out", "HTTP process :8080 GET /api/process/mode·/api/instances·/api/todolist?status=IN_PROGRESS·/api/instances/{id}·/graph·/api/graph-projections·/api/agents/status·/api/todolist/{id}·/api/decisions/{id} (인스턴스 탭 2 s)", "인스턴스·할일·투영·워커 상태", "it/portal/www/instances.js:17-60,521"),
    ("inst", "out", "HTTP process :8080 POST /api/todolist/{id}/select·submit·human-response·close·cancel·approval-retry·work-order-retry·approval-discard(-preview)·decision-preview·reassess, /api/instances/{id}/rework(-preview)·/effects(/compensate·/review)", "사람 작업 제출과 복구 조작", "it/portal/www/instances.js:185-425 · it/portal/www/instanceRework.js:112-125 · it/portal/www/instanceEffects.js:22,64 · it/portal/www/taskDeferral.js:27,63"),
    ("stream", "in", "HTTP SSE process :8080 GET /api/events/stream (EventSource, 페이지 로드 시 연결)", "events 행(history·data 프레임)", "it/portal/www/liveStream.js:110-123,140-141"),
    ("adv", "out", "HTTP process :8080 GET·POST /api/process/definitions, GET /api/process/definitions/{id}?version=, POST /api/instances/start, GET /api/source-events(+/{id}), POST /api/source-events/{id}/retry", "정의 등록·실행, 원천 접수 조회·재시도", "it/portal/www/definitionRegistry.js:13-64 · it/portal/www/sourceEvents.js:18-54"),
  ],
  notes=[
    "프록시 없음: 주소는 location.hostname+포트로 만들고 각 서비스가 CORS *를 허용한다. nginx는 파일만 준다 (it/portal/www/layers.js:3-4,43-45 · it/portal/www/app.js:1-2 · common/hydcommon/service.py:11 · it/portal/nginx.conf:1-8)",
    "fetch 래퍼는 GET 8 s·쓰기 30 s에서 중단하고 cache no-store, 오류 detail을 메시지로 바꾼다 (it/portal/www/app.js:7-26)",
    "탭과 무관하게 항상 도는 폴링: refreshFast 1 s(plant·detector), refreshSlow 2 s(incidents·agent runs·audit), pollHealth 5 s(약 12개 서비스). busy 플래그로 겹침만 막는다 (it/portal/www/app.js:121-123,553-583)",
    "탭 한정 폴링: hitl 1.5 s(이상 확인 탭+선택 사건), procBpmn 2 s·refreshProcess 2.5 s(업무 프로세스 탭), instances 2 s(인스턴스 탭, 틱마다 GET 최대 9건), main renderLive 1 s(네트워크 없음) (it/portal/www/hitl.js:118-122,218-232 · it/portal/www/enterprise.js:448 · it/portal/www/instances.js:17-42,521 · it/portal/www/main.js:180)",
    "SSE는 탭과 무관하게 페이지 로드 때 연결. 최근 160건만 두고 id로 중복 제거, 작업 전이·질문·오류 이벤트면 250 ms 뒤 인스턴스 화면을 재조회한다(2 s 폴링은 그대로) (it/portal/www/liveStream.js:1-13,58-70,140-141)",
    "selectTab은 app.js → enterprise.js → hitl.js → instances.js 순으로 덮어써지므로 스크립트 로드 순서가 기능 조건이다 (it/portal/www/index.html:262-275 · it/portal/www/enterprise.js:39-45 · it/portal/www/hitl.js:571-580 · it/portal/www/instances.js:516-518)",
    "상태는 브라우저 메모리(전역 state·I·H·ent)와 sessionStorage(스킬 편집 초안·매뉴얼 추출 request_id)뿐이고 서버 세션·인증이 없다. 기본 사용자 OP-17 등이 하드코딩 (it/portal/www/hitl.js:236-243,437-442 · it/portal/www/instances.js:9 · it/portal/www/app.js:531)",
    "고급 패널(정의 등록·원천 접수)은 details를 열 때만 호출하고 주기 폴링이 없다 (it/portal/www/definitionRegistry.js:34-37 · it/portal/www/sourceEvents.js:48)",
    "추세 탭은 Grafana d-solo iframe 5개가 각자 5 s 새로고침하고 포털은 Grafana 연결만 no-cors로 확인한다 (it/portal/www/app.js:537-548)",
  ],
)

# 주의: 문서·주석과 코드가 다른 곳 — 2026-10-08 정리(A149, 괄호 숫자는 remaining-sweep 항목 35·36의 옛 줄 번호)
#   닫힘(A143 .evidence/a143/README.md): main.py 독스트링(570·573), MemoryRepo+instance 조합은 시작 시 명시 거부(571, 항목 14), store.py 독스트링·STATE_LOCK(572, 항목 13), entsim 멱등 충돌 409 통일(574, 항목 16).
# - 현행(A147 브라우저 실측 .evidence/a147/behavior.json 9): liveStream.js는 /api/events/stream 응답이 409(legacy 모드)면 '실시간 꺼짐'으로 표시하고 재연결하지 않는다(12 s 동안 요청 1회).
#   그 밖의 실패(process 재시작·5xx)는 2·4·8 s … 최대 30 s 백오프로 재연결한다 (it/portal/www/liveStream.js:142-157)
# - 남음: instances.js:3 머리 주석은 GET /api/process/definition을 읽는다고 적었지만 load()는 이 경로를 호출하지 않는다(정의는 /api/instances/{id} 응답의 view.definition) (it/portal/www/instances.js:1-6,17-42)

INTERNAL["worker"] = dict(
  runtime="Python 3.12(python:3.12-slim) · 1프로세스 · 동기 실행 1건씩 · 스레드: main(폴링+실행+check_stop) · http.server :8097 · workspace sweep(1시간) · 실행 중에만 hyd-cli-output 펌프 1개 · 자식 프로세스 Claude Code CLI(Node 22 npm, 또는 codex) → CLI의 자식으로 neo4j MCP(uvx stdio)",
  parts=[
    ("w_main", "폴링 루프·환경 정리", "it/agent-worker/worker/main.py:21-105, worker/env_guard.py:1-33", "비밀 환경변수 제거 후 3초 간격으로 Runner.poll_once 반복"),
    ("w_http", "상태 HTTP 스레드", "it/agent-worker/worker/main.py:48-68", "/health·/healthz·/agents 에 status dict·CLI 설치 여부 응답"),
    ("w_sweep", "작업공간 청소 스레드", "it/agent-worker/worker/main.py:71-80, worker/workspace.py:106-148", "72h 지난 실행 폴더 삭제, IN_PROGRESS 작업 폴더는 보존"),
    ("w_runner", "Runner 실행 흐름", "it/agent-worker/worker/runner.py:42-165, 235-272", "점유→준비→실행→판정→저장/질문/보류/실패를 DB 상태로 끝냄"),
    ("w_prep", "실행 준비(맥락·작업공간·MCP 브리지·프롬프트)", "worker/context.py:44-91, worker/workspace.py:82-103, worker/bridge.py:28-159, worker/prompt.py:13-82, runner.py:278-289", "폼·사용자·tenants.mcp 읽고 CLAUDE.md·.mcp.json·task.json·프롬프트 작성"),
    ("w_stream", "스트림 감시(취소·임대 갱신·제한시간)", "it/agent-worker/worker/runner.py:167-232", "CLI 이벤트를 events 행으로 기록하고 check_stop으로 취소·임대·제한시간 판정"),
    ("w_pump", "출력 펌프 스레드·프로세스 트리", "it/agent-worker/worker/process_control.py:15-133", "cliagents stream_exec를 별도 스레드로 돌려 큐로 넘기고 종료 시 트리 강제 종료"),
    ("w_cli", "Claude Code CLI 자식 프로세스", "외부 바이너리 @anthropic-ai/claude-code (it/agent-worker/Dockerfile:5), runner.py:318-343", "작업공간에서 헤드리스로 업무 수행, MCP 서버를 스스로 띄우거나 HTTP로 호출"),
    ("w_outcome", "결과 판정·사람 질문·보류", "worker/outcome.py:36-114, worker/hitl.py:17-119, it/process/procsvc/task_deferral.py:49-110", "마지막 메시지를 폼 계약·__human_input__·__deferred__로 해석"),
    ("w_repo", "PgRepo DB 접근", "it/process/procsvc/procdb.py:424-751", "psycopg 3로 todolist·events·정의·폼·사용자·테넌트 읽기/쓰기"),
  ],
  links=[
    ("w_main", "w_runner", "함수 호출", "poll_once() — 처리 건수 반환, 0이면 poll_interval_s 대기", "worker/main.py:90-101"),
    ("w_main", "w_http", "공유 메모리(잠금 없음, 전역 dict status · _runner.in_flight)", "status·polls·handled·error, 실행 중 건수", "worker/main.py:28-30, 52, 93-100"),
    ("w_runner", "w_repo", "함수 호출", "fetch_pending_task('cliagents', '<consumer>:<uuid>', limit=1, tenant='hyd') → 점유된 todolist 행", "worker/runner.py:51-56"),
    ("w_runner", "w_prep", "함수 호출", "context.prepare · workspace.for_run/provision · bridge.select_servers/install · prompt.build/resume_prompt · 종료 후 bridge.cleanup", "worker/runner.py:62, 73, 85-122"),
    ("w_prep", "w_repo", "함수 호출", "get_proc_def(version 고정) · get_form · list_users · get_tenant(mcp)", "worker/context.py:54, 64, 69, 72"),
    ("w_prep", "w_cli", "로컬 파일(작업공간)", "CLAUDE.md(작업 규칙) · context/schema_prompt.md · context/task.json · .mcp.json · 긴 프롬프트 context/prompt.md", "worker/workspace.py:97-103, worker/bridge.py:124-141, worker/runner.py:278-289"),
    ("w_runner", "w_stream", "함수 호출", "_stream(provider, ExecRequest, env, crew, trace_path) — 교정 재요청 때 같은 세션으로 다시 호출", "worker/runner.py:123-127, 146-153"),
    ("w_stream", "w_pump", "함수 호출(제너레이터)", "controlled_stream(stream_exec, provider, request, env, check_stop, RunFailed)", "worker/runner.py:184-185, 306-310"),
    ("w_pump", "w_cli", "자식 프로세스 stdio", "argv(프롬프트·--allowedTools·resume 세션) / stdout 스트림 JSON → cliagents 파서 → ExecEvent, CLAUDE_CONFIG_DIR env", "worker/process_control.py:54-65, 101-118; runner.py:120-123"),
    ("w_pump", "w_stream", "스레드 대기열 queue.Queue(maxsize=128)", "ExecEvent 항목과 종료 표식 done, 펌프 실패 예외", "worker/process_control.py:91-128"),
    ("w_stream", "w_repo", "함수 호출", "이벤트마다 record_events · 2초마다 get_workitem(취소 확인) · 30초마다 renew_task_lease", "worker/runner.py:172-183, 208-215, 228-232"),
    ("w_stream", "w_runner", "반환값/예외", "(final_text, session_id, pause_reason) 또는 Cancelled·RunFailed", "worker/runner.py:176, 181, 183, 223-226"),
    ("w_runner", "w_outcome", "함수 호출", "task_deferral.control → hitl.business_question → outcome.interpret(폼 계약) 순서로 판정", "worker/runner.py:128-155"),
    ("w_outcome", "w_repo", "함수 호출", "task_deferral.defer: instance_transaction 안에서 status PENDING·draft._deferral 저장 + task_deferred 이벤트", "it/process/procsvc/task_deferral.py:89-110"),
    ("w_runner", "w_repo", "함수 호출", "save_task_result(final, expected_consumer) · HUMAN_ASKED(set_draft_status·update_workitem·human_asked 이벤트·insert_notification) · update_task_error · release_worker_claim", "worker/runner.py:65, 159-161, 241-252, 260-268"),
    ("w_runner", "w_outcome", "로컬 파일", "HITL 캐시 .processgpt-pending.json 기록/삭제, 재개 시 plan_resume가 읽음", "worker/runner.py:97, 132, 162, 254; worker/hitl.py:77-119"),
    ("w_sweep", "w_repo", "함수 호출", "get_workitem(run_id).status=='IN_PROGRESS' 이면 폴더 보존", "worker/main.py:74-75"),
    ("w_sweep", "w_prep", "로컬 파일(작업공간 디렉터리 삭제)", "보존기간 지난 /workspace/<tenant>/<todo id> rmtree", "worker/workspace.py:106-125"),
  ],
  ext=[
    ("w_repo", "both", "PostgreSQL 프로토콜(psycopg 3) host.docker.internal:54322 (SUPABASE_DSN, postgres 사용자)", "claim_process_workitems·renew_task_lease·record_events_bulk RPC, todolist 조건부 UPDATE, proc_def_version·form_def·users·tenants 조회, notifications INSERT", "worker/settings.py:34; procdb.py:425-440, 645-681, 699-736"),
    ("w_http", "in", "HTTP :8097 (127.0.0.1:8097 공개) GET /health /healthz /agents", "status JSON(200/503), CLI 설치 목록 — 포털 WORKER_URL·컨테이너 헬스체크", "worker/main.py:48-68; compose.yaml:374, 464, 484"),
    ("w_cli", "out", "자식 프로세스 stdio MCP 'neo4j': uvx --with fastmcp==2.13.0.2 mcp-neo4j-cypher@0.4.1 --transport stdio → bolt://neo4j:7687 (NEO4J_READ_ONLY=true)", "get_neo4j_schema · read_neo4j_cypher 온톨로지 조회", "it/supabase/seed.sql:59-60; worker/settings.py:57-59"),
    ("w_cli", "out", "Streamable HTTP MCP 'enterprise' http://enterprise-mcp:8199/mcp", "업무 DB(ent) 읽기 도구 mcp__enterprise__*", "it/supabase/seed.sql:61; worker/bridge.py:137-138"),
    ("w_cli", "out", "Streamable HTTP MCP 'hyd-dmn' http://dmn-mcp:8198/mcp", "DMN 판정·카드 평가·submit_decision", "it/supabase/seed.sql:62; worker/workspace.py:41"),
    ("w_cli", "out", "HTTPS 모델 API(ANTHROPIC_API_KEY) / codex는 OpenAI 호환 base_url(/v1/responses)", "LLM 호출", "compose.yaml:472; worker/settings.py:42-45; worker/runner.py:112-119"),
    ("w_prep", "both", "로컬 파일 볼륨 /workspace (worker-data) — /workspace/hyd/<todo id>/", "실행별 작업공간·.mcp.json·.agent-home/claude-code(CLAUDE_CONFIG_DIR)·outputs/result.json", "compose.yaml:465; worker/settings.py:50; worker/bridge.py:152-159; worker/runner.py:163-164"),
    ("w_prep", "in", "로컬 파일 /srv/ontology/schema_prompt.md (SCHEMA_PROMPT)", "온톨로지 스키마 설명 → context/schema_prompt.md 로 복사", "Dockerfile:15, 17; worker/runner.py:46, 346-350"),
    ("w_stream", "out", "로컬 파일 <작업공간>/<job_id>.events.jsonl", "CLI ExecEvent 전체 추적 기록(텍스트·생각 포함)", "worker/runner.py:127, 186-191"),
  ],
  notes=[
    "환경 정리: 설정을 읽은 직후 SUPABASE_DSN·*_PASSWORD·*_DSN·*_SECRET·*_SERVICE_KEY 를 os.environ에서 지워 CLI·MCP 자식이 상속하지 못하게 한다(GPU 키 이름만 예외) (worker/main.py:23-27; worker/env_guard.py:10-33)",
    "폴링: 일이 있으면 즉시 다시 폴링, 없으면 POLL_INTERVAL_S(기본 3초) 대기, 예외는 status=error 로 남기고 계속 (worker/main.py:90-101; worker/settings.py:32)",
    "동시 실행은 1건: poll_once가 limit=1로 점유해 handle을 동기로 끝낸 뒤 돌아온다 (worker/runner.py:51-56; worker/main.py:28)",
    "임대 갱신은 별도 스레드가 아니다: main 스레드의 controlled_stream 루프가 25 ms마다 check_stop을 부르고, 그 안에서 2초마다 취소 확인·30초마다 renew_task_lease(120초)·1800초 제한시간을 본다. 갱신 실패=점유 상실→Cancelled (worker/process_control.py:120-124; worker/runner.py:172-183; worker/settings.py:47, 66-67; procdb.py:43)",
    "취소 판정: 행이 없거나 status≠IN_PROGRESS, draft_status=CANCELLED, consumer 변경 중 하나면 Cancelled → release_worker_claim + task_cancelled 이벤트 (worker/runner.py:64-67, 228-232)",
    "프로세스 종료: Windows는 Job Object(KILL_ON_JOB_CLOSE), POSIX는 새 세션+killpg SIGKILL. 펌프가 10초 안에 안 멈추면 RunFailed (worker/process_control.py:15-82, 129-133)",
    "CLI 종료코드≠0 이면 stderr 끝 2000자를 담아 RunFailed, 0인데 stderr가 있으면 로그만 (worker/process_control.py:108-113)",
    "판정 순서: __deferred__ 보류 → __human_input__ 사람 질문 → 권한 거절로 결과 없음(HUMAN_ASKED) → 폼 계약 검사. 계약 불일치면 같은 세션에 형식 교정 최대 2회, 그래도 실패면 RunFailed (worker/runner.py:128-155; worker/settings.py:48)",
    "저장: save_task_result가 consumer·IN_PROGRESS·STARTED 조건부 UPDATE라 점유를 잃었으면 False → Cancelled. payload에 cliagents_session_id를 넣어 다음 작업·사람 답변이 같은 세션을 이어간다 (worker/runner.py:156-160, 292-303; procdb.py:651-663)",
    "HUMAN_ASKED: 인스턴스 잠금 트랜잭션 안에서 draft_status=HUMAN_ASKED, draft={cliagents_session_id,_human_request}, human_asked 이벤트(status ASKED), role:operator 알림을 한 번에 기록. 작업공간 파일은 캐시일 뿐이고 재개는 DB draft의 job_id 일치를 먼저 본다 (worker/runner.py:235-257; worker/hitl.py:40-49, 113-119)",
    "MCP 등록: 활동 정의의 tools/mcpServers에 적힌 테넌트 서버만 .mcp.json에 쓴다(없으면 전부). stdio(command)는 CLI가 자식으로 띄우고, url 항목은 Claude Code의 {type:'http'}로 쓴다. 실행 뒤 bridge.cleanup이 .mcp.json의 env(비밀번호)를 지운다 (worker/bridge.py:28-59, 103-141; worker/runner.py:72-75, 91-95)",
    "Claude Code는 --allowedTools로 MCP 읽기 도구·Read/Glob/Grep 등만 미리 승인하고, 그 밖은 permission_request → 사람 질문이 된다 (worker/runner.py:120-121; worker/settings.py:53-59)",
    "CLAUDE_CONFIG_DIR 분리는 ANTHROPIC_API_KEY가 있을 때만(구독 로그인은 공유 설정 폴더 유지) (worker/settings.py:60-62; worker/bridge.py:152-159)",
    "codex 경로는 .mcp.json 대신 codex-mcp.toml + -c 덮어쓰기, --ignore-user-config, 헌법·스키마를 프롬프트 앞에 붙인다 (worker/bridge.py:107-123; worker/runner.py:107-119)",
    "events 테이블에는 run_start·tool_start·tool_end·error·usage·file_artifact만 행으로 저장, text·thinking·plan은 trace jsonl에만 남는다. 이벤트마다 즉시 record_events_bulk 호출 (worker/events.py:16-19, 62-68; worker/runner.py:208-214)",
    "16000자 넘는 프롬프트는 context/prompt.md로 쓰고 argv에는 안내문만(Windows 32K 한계) (worker/settings.py:55-56; worker/runner.py:278-289)",
    "Windows에서 claude.cmd 셸 래퍼 대신 bin/claude.exe를 직접 실행(인자 변형 방지) (worker/runner.py:318-343)",
  ],
)

INTERNAL["supa"] = dict(
  runtime="Supabase CLI 로컬 스택(Docker 컨테이너 묶음) · PostgreSQL 15 :54322(shadow :54320) · PostgREST API :54321(노출 스키마 public·ent·storage·graphql_public) · Studio :54323 · Realtime·Auth 켬 · Storage·Inbucket·Analytics·Pooler 끔 · 스키마 2개: public(프로세스 엔진) · ent(업무 DB) · 역할 anon·authenticated·service_role·hyd_enterprise_reader(+postgres)",
  parts=[
    ("t_def", "정의·폼·테넌트 표(public)", "it/supabase/migrations/20261003000001_process_engine.sql:45-121, 20261004000002_immutable_definitions.sql:1-18", "tenants(mcp) · users(사람·에이전트) · proc_def · proc_def_version · form_def"),
    ("t_work", "인스턴스·작업 표(public)", "20261003000001_process_engine.sql:124-216, 20261004000001, 09, 10, 14, 20261007000018:6-12", "bpm_proc_inst · todolist(lease_until·claim_count) · process_rework_receipt"),
    ("t_evt", "이벤트·알림 표(public)", "20261003000001_process_engine.sql:219-255, 20261005000013_task_deferral.sql:1-5", "events(event_type_enum) · notifications · proc_inst_source"),
    ("t_durable", "프로세스 내구 기록 표(public)", "20261004000005, 07, 08, 11, 12, 20261005000016", "process_approval_outbox · process_source_inbox/state · execution_projection_outbox · projection_repairs · process_effect_receipt"),
    ("ent_master", "업무 마스터·현황 표(ent)", "20261003000002_enterprise.sql:14-109, 20261004000006, 20261007000017:7-47", "assets · production_orders · sales_contracts · fg_inventory · maintenance_profiles/history · quality_profiles · parts · suppliers · energy_demand"),
    ("ent_exec", "업무 실행 결과·원장 표(ent)", "20261003000002_enterprise.sql:112-146, 20261005000015:5-14, 20261007000019:4-7", "work_orders · purchase_requests · shipments · lot_dispositions · ems_actions · transactions(before/after)"),
    ("rpc_claim", "점유·임대 RPC", "20261007000018_worker_lease.sql:14-91, 20261004000004_process_lock_order.sql:43-87", "claim_process_workitems · fetch_pending_task · claim_submitted_workitems · renew_task_lease · expire_worker_leases · cleanup_stale_consumers"),
    ("rpc_result", "결과·이벤트·맥락 RPC", "20261004000004_process_lock_order.sql:53-69, 20261003000001_process_engine.sql:315-364", "save_task_result · record_events_bulk · fetch_context_bundle"),
    ("rpc_ent_read", "업무 읽기 RPC(ent)", "20261003000002_enterprise.sql:149-199, 20261007000017:50-84", "mes_orders · erp_contract · erp_inventory · cmms_history · qms_lots · scm_suppliers · ems_demand · hours_from_now"),
    ("rpc_ent_write", "업무 쓰기 RPC(ent)", "20261007000019:9-106, 20261007000020:5-80, 20261007000017:88-111", "exec_skill · exec_compensation(멱등) · reset_executions · reanchor_scenario_times"),
  ],
  links=[
    ("rpc_claim", "t_work", "SQL(UPDATE … FOR UPDATE SKIP LOCKED, 인스턴스 먼저 잠금)", "worker 점유: IN_PROGRESS·agent_orch 일치·(새 작업|FB_REQUESTED|임대 만료 STARTED & claim_count<3) → consumer·draft_status STARTED·lease_until now+120s·claim_count+1·log", "20261007000018_worker_lease.sql:22-54"),
    ("rpc_claim", "t_work", "SQL UPDATE", "renew_task_lease: consumer·IN_PROGRESS·STARTED 일 때 lease_until 연장 / expire_worker_leases: 만료+claim_count≥3 → FAILED·consumer null / cleanup_stale_consumers: 30분 넘은 SUBMITTED consumer 해제", "20261007000018_worker_lease.sql:58-87; 20261004000004:71-87"),
    ("rpc_claim", "t_work", "SQL(engine 점유)", "claim_submitted_workitems → claim_process_workitems(kind engine): SUBMITTED & consumer null 행에 consumer 기록", "20261004000004_process_lock_order.sql:48-51; 20261007000018:31, 45, 48"),
    ("rpc_result", "t_work", "SQL UPDATE(인스턴스 FOR UPDATE 후)", "save_task_result: COMPLETE면 output·status SUBMITTED·draft_status COMPLETED·consumer null, DRAFT면 draft만", "20261004000004_process_lock_order.sql:53-69"),
    ("rpc_result", "t_evt", "SQL INSERT", "record_events_bulk: jsonb 배열 → events(id·job_id·todo_id·event_type·status·data)", "20261003000001_process_engine.sql:316-330"),
    ("rpc_result", "t_def", "SQL SELECT", "fetch_context_bundle: tenants.mcp · form_def.fields_json/html · users(에이전트), todolist·users로 알림 이메일", "20261003000001_process_engine.sql:333-364"),
    ("t_work", "t_work", "트리거(update_bpm_proc_inst_updated_at, set_updated_at)", "todolist UPDATE → 같은 행 updated_at, 부모 bpm_proc_inst.updated_at 갱신", "20261003000001_process_engine.sql:201-216"),
    ("t_work", "t_durable", "트리거(hyd_execution_instance · hyd_execution_workitem, security definer)", "bpm_proc_inst·todolist INSERT/UPDATE/DELETE마다 execution_projection_outbox 행 추가", "20261004000011_execution_projection_outbox.sql:23-44"),
    ("t_durable", "t_work", "외래 키", "approval_outbox.todo_id→todolist, proc_inst_id→bpm_proc_inst / effect_receipt·rework_receipt→bpm_proc_inst", "20261004000005:4-5; 20261005000016:7; 20261004000010:8-26"),
    ("t_work", "t_def", "외래 키", "tenant_id → tenants(id) (on delete cascade)", "20261003000001_process_engine.sql:136, 172"),
    ("rpc_ent_read", "ent_master", "SQL SELECT(stable 함수)", "{system, facts, records, as_of} — 남은 시간 h는 *_at 시각에서 now() 기준 계산", "20261003000002_enterprise.sql:149-199; 20261007000017:50-84"),
    ("rpc_ent_read", "ent_exec", "SQL SELECT", "cmms_history가 work_orders 목록을 함께 반환", "20261007000017_enterprise_time_anchors.sql:82"),
    ("rpc_ent_write", "ent_exec", "SQL INSERT/UPDATE", "exec_skill: work_orders·purchase_requests·lot_dispositions·shipments·ems_actions 생성 + transactions(fingerprint·before·after) / exec_compensation: 취소·격리해제 + 보상 거래 행", "20261007000019:44-103; 20261007000020:38-72"),
    ("rpc_ent_write", "ent_master", "SQL UPDATE", "reallocate-production·restore-production이 production_orders.asset/moved_from 변경, reanchor_scenario_times가 due_at·ship_at·night_window_at·performed_at 재설정", "20261007000019:52-62; 20261007000020:54-60; 20261007000017:88-99"),
  ],
  ext=[
    ("rpc_claim", "in", "PostgreSQL :54322 (psycopg, postgres 사용자) — agent-worker PgRepo", "claim_process_workitems(...,'worker') 직접 호출 · renew_task_lease", "it/process/procsvc/procdb.py:645-649, 679-681"),
    ("rpc_claim", "in", "PostgreSQL :54322 — process 서비스(엔진)", "claim_submitted · expire_worker_leases · cleanup_stale_consumers", "procdb.py:683-696; it/process/procsvc/instances.py:357; it/process/procsvc/main.py:173; it/process/procsvc/instance_mode.py:164"),
    ("rpc_result", "in", "PostgreSQL :54322 — worker·process PgRepo.record_events", "events 배열", "procdb.py:699-703"),
    ("t_work", "both", "PostgreSQL :54322 직접 SQL — PgRepo(worker·process)", "todolist 조건부 UPDATE(save/set_draft_status/release), insert/update 인스턴스·작업, instance_transaction 잠금", "procdb.py:460-475, 577-672"),
    ("t_def", "in", "seed.sql (supabase start / db reset 후 실행) · process upsert_proc_def", "tenants.mcp(neo4j stdio·enterprise·hyd-dmn HTTP) · users 7행 · form_def 6행 · 정의 버전", "it/supabase/seed.sql:57-85; procdb.py:522-543"),
    ("ent_master", "in", "seed.sql", "설비 3대·오더·계약·재고·정비·품질·공급사·에너지 가상 데이터, 끝에 reanchor_scenario_times()", "it/supabase/seed.sql:4-52, 87"),
    ("rpc_ent_read", "in", "PostgreSQL :54322 역할 hyd_enterprise_reader — enterprise-mcp / enterprise-sim(supabase 백엔드)", "ent.* 읽기 RPC 호출", "it/enterprise-mcp/enterprise_mcp/tools.py:18; it/enterprise-sim/entsim/supabase_backend.py:14; compose.yaml:425"),
    ("rpc_ent_write", "in", "PostgreSQL :54322 (SUPABASE_DSN) — enterprise-sim supabase 백엔드", "exec_skill / exec_compensation / reset_executions", "it/enterprise-sim/entsim/supabase_backend.py:44, 76; compose.yaml:395"),
    ("t_evt", "out", "PostgreSQL :54322 — process 서비스 events 조회(실시간 스트림 커서)", "events 행", "procdb.py:708-724"),
    ("t_def", "both", "PostgREST :54321 · Studio :54323 · Realtime", "REST/실시간 노출 — 실제 사용 클라이언트는 미확인(조사 범위 코드는 psycopg 직결만)", "it/supabase/config.toml:7-32"),
  ],
  notes=[
    "잠금 순서: 모든 작업 행 변경은 부모 bpm_proc_inst를 먼저 FOR UPDATE 한 뒤 todolist를 잠근다(자식 UPDATE 트리거가 부모를 갱신해 교착이 났기 때문) (20261004000004_process_lock_order.sql:1-3, 21-35; procdb.py:499-506)",
    "점유 조건에 부모 인스턴스 status=RUNNING·is_deleted=false가 붙는다. 그래서 끝난 인스턴스의 작업은 점유되지 않는다 (20261007000018_worker_lease.sql:32-37)",
    "임대: 점유 시 lease_until=now+120s·claim_count+1. STARTED인데 임대가 지났고 claim_count<3이면 다른 워커가 다시 점유(log에 'Lease expired: reclaimed by'). 3회 만료면 expire_worker_leases가 FAILED·consumer null. 마이그레이션 시점 STARTED 행엔 임대 120초 부여 (20261007000018_worker_lease.sql:6-12, 28-30, 48-54, 69-87)",
    "renew_task_lease는 consumer·IN_PROGRESS·STARTED가 모두 맞을 때만 갱신하고 bool 반환 — HUMAN_ASKED로 바뀐 뒤엔 갱신 대상이 아니다 (20261007000018_worker_lease.sql:58-66)",
    "save_task_result RPC: COMPLETE 모드만 SUBMITTED로 넘어가고 DRAFT 모드는 draft에 저장·draft_status COMPLETED. RPC 자체에는 consumer 확인이 없다 (20261004000004_process_lock_order.sql:53-69)",
    "todolist·bpm_proc_inst의 모든 INSERT/UPDATE/DELETE가 execution_projection_outbox에 행을 쌓는다. 실행 중 30초마다 하는 임대 갱신도 todolist UPDATE라 매번 쌓인다 (20261004000011:23-44; 20261007000018:62)",
    "변경 금지 트리거: initial_variables, 작업 세대 식별(generation·rework_request_id·supersedes_id), rework receipt, effect receipt의 요청부 (20261004000009:10-18; 20261004000010:28-44; 20261005000016:24-37). 정의 버전은 (tenant, proc_def_id, version) 고유 (20261004000002:3-5)",
    "업무 쓰기 멱등: exec_skill은 (decision_id, skill) 정방향 고유, exec_compensation은 (decision_id, skill, ref) 고유. 같은 키에 입력 md5 fingerprint가 다르면 23505 오류, 같으면 이전 결과 반환 (20261005000015:5-10; 20261007000019:32-40; 20261007000020:27-35)",
    "보상은 원래 상태일 때만 허용(작업지시 '배정됨', 구매요청 '승인됨 → 발주', 격리 '격리 · 전수검사 대기'), release-lot·substitute-shipment·demand-control은 보상 RPC 없음 (20261005000015:1-4; 20261007000020:38-69)",
    "권한: public 엔진 표는 RLS 켜고 anon·authenticated 전체 읽기, authenticated 전체 쓰기 허용 정책 (20261003000001_process_engine.sql:400-413). 내구 기록 표(outbox·inbox·effect)는 anon·authenticated 회수, service_role만 (20261004000005:21-23; 20261004000007:44-47, 57-59; 20261005000016:39-41)",
    "권한(ent): 표는 anon·authenticated 읽기, service_role 전체. exec_skill·exec_compensation·reset_executions·reanchor_scenario_times는 PUBLIC에서 회수하고 service_role만 (20261003000002_enterprise.sql:303-320; 20261004000003:23-26; 20261007000017:109-110)",
    "hyd_enterprise_reader: 로그인 역할, default_transaction_read_only on·statement_timeout 5s·search_path pg_catalog,ent, ent 표 SELECT + 전용 RLS 정책(정책 없으면 0행). 비밀번호가 마이그레이션에 평문 (20261004000003:3-29)",
    "시각 기준: ent의 상대 시간 열(due_in_h 등)은 사용 중단, *_at 시각을 저장하고 읽기 RPC가 now() 기준 h로 계산. seed와 reset_executions가 reanchor_scenario_times로 '지금' 기준 시나리오를 다시 맞춘다 (20261007000017:1-47, 86-107; seed.sql:87)",
    "enum 확장: event_type_enum에 task_deferred·task_reassessment_requested, process_status에 CANCELLED, approval outbox 상태에 DISCARDED (20261005000013:3-4; 20261004000008:2-5)",
  ],
)

# 주의: 문서·주석과 코드가 다른 곳 — 2026-10-08 정리(A149, 괄호 숫자는 remaining-sweep 항목 35·36의 옛 줄 번호): 이 절의 10건은 모두 닫힘.
#   A143(.evidence/a143/README.md): procdb 독스트링(706의 procdb 부분)·renew_task_lease 부모 잠금(708, 마이그레이션 24)·enterprise.sql 주석(709)·config.toml 표(713)·todolist.draft 주석(714).
#   A144(.evidence/a144/a144-report.md 35-711): ALLOWED_TOOLS 기본값은 worker/settings.DEFAULT_ALLOWED_TOOLS 하나, compose는 통과만(711).
#   A129: /agents?check_auth=1 은 CLI별 auth/login status 프로브를 실제로 돌린다(712, worker/main.py agents()).
#   A149: 워커 독스트링 — 임대 갱신은 main 스레드 check_stop 안에서 30 s마다(705, runner.py), '→ SUBMITTED'는 agent_mode=COMPLETE일 때·DRAFT는 draft만 저장(707, main.py·runner.py),
#         repo 메서드 이름 fetch_pending_task/save_task_result는 제품 이름이고 PgRepo가 HYD 잠금 순서 SQL로 실행(706 워커 부분), 정지 정본은 DB draft._human_request·파일은 캐시(710, hitl.py).
#         compose.yaml:468-469 주석은 같은 repo 메서드 이름으로 읽으면 맞아 그대로 둠.

