# -*- coding: utf-8 -*-
"""hyd-iot-edu 기술 레이어 구조도 데이터(설계서 v2 「그림 1」 방식).
카드 = 논리 구성요소(컨테이너가 아님). box 칸에 실제로 들어 있는 컨테이너 · 포트를 적는다.
근거: compose.yaml · 각 서비스 코드(2026-10-07 코드 감사). 카드 글에는 파일 · 함수 이름을 쓰지 않는다(사용자 2026-10-07).
화살표 1~76 은 이전 판과 같은 뜻을 유지하고, 새 화살표는 끝(77~)에만 덧붙인다.
2026-10-08: 위층(L7~L9)을 하는 일 단위 카드로 나눴다. 같은 층이 띠 여러 개(L9 셋 · L8 둘 · L7 둘)로 나뉘고 띠 왼쪽 표시는 같은 층 번호다.
 같은 뜻의 화살표가 나뉜 카드로 옮겨 간 것: 39 · 68(→ 기업 거래), 40 · 67(→ 사례 · 실행 투영), 42(→ AI 작업 다리), 47(→ 회사 데이터 서버),
 49 · 61 · 73(→ ent 기업 데이터), 51(→ 이상 확인 · 업무 화면), 59 · 60(→ 승인 재평가 카드), 60(← 승인 전달), 66(→ 원천 접수함), 69(← 인스턴스 화면), 73(← 주기 맞추기).
"""
NCOL = 7

_P = ("#fff8eb", "#d97706", "#b45309")
_A = ("#fdf2f8", "#db2777", "#be185d")
_K = ("#faf5ff", "#a21caf", "#86198f")
LAYERS = [  # id, 표시, 이름, 핵심 기능, 배경, 테두리, 글자
 ("L9", "L9", "프로세스 · 승인 · 앱 — 사람과 화면", "HITL 승인 · 업무 화면", *_P),
 ("L9b", "L9", "업무 진행 내부 (process 컨테이너)", "업무 실행 조율 · 버팀 장치", *_P),
 ("L9c", "L9", "업무 기록부 · 기업 시스템", "업무 데이터 · 거래 · 원장", *_P),
 ("L8", "L8", "AI 에이전트 — 조사관 · 판단 엔진", "원인 판단 · 조치 카드 생성", *_A),
 ("L8b", "L8", "AI 직원 · MCP 서버", "할 일 수행 · 도구 경계", *_A),
 ("L7", "L7", "온톨로지 — 지식 그래프와 관리", "지식 저장 · 질의 · 편집", *_K),
 ("L7b", "L7", "온톨로지 일곱 층 (지식 그래프 안의 내용)", "원인 · 조치 · 가치 지식", *_K),
 ("L6", "L6", "관제 · SCADA · 인프라 감시", "관제", "#eff6ff", "#2563eb", "#1d4ed8"),
 ("L5", "L5", "시계열 저장소", "이력 저장", "#ecfeff", "#0e7490", "#0e7490"),
 ("L4", "L4", "스트림 처리 · CEP", "실시간 이상 탐지", "#f5f3ff", "#7c3aed", "#6d28d9"),
 ("L3", "L3", "이벤트 백본 · DMZ", "이벤트 장부 · 공장↔사무 경계", "#ecfdf5", "#0f766e", "#0f766e"),
 ("L2", "L2", "IoT 미들웨어 · MQTT", "디바이스 연결 · 수집", "#f8fafc", "#475569", "#334155"),
 ("L1", "L1", "센서 네트워크 · 설비", "현장 계측 · 구동", "#f1f5f9", "#334155", "#1e293b"),
]

CARDS = {
 # ── L9 사람 · 화면 ──
 "people": dict(layer="L9", col=0, title="운전원 · 담당자", tech="같은 PC의 브라우저 · 로그인 없음", kind="person",
                lines=["포털: 카드 고름 · 승인 · 반려 · 고장 넣기", "FUXA: 값 · 알람 · 수동 조작 · 모드", "제품 화면: Neo4j · EMQX · Grafana", "이름 · 역할은 스스로 적음"]),
 "portal": dict(layer="L9", col=1, title="포털: 실습 · 설비 화면 (guide-app 역할)", tech="nginx · 정적 화면 · 서버 쪽 중계 없음", box="portal",
                lines=["실습 홈 · 시스템 아키텍처(응답 표시등)", "결함 시뮬레이션 · 실시간 모니터링", "브라우저가 각 API를 직접 호출(CORS)"]),
 "pinst": dict(layer="L9", col=2, title="포털: 프로세스 인스턴스 화면", tech="instance 방식에서만 · 이벤트는 SSE", box="portal",
               lines=["할 일 · AI 질문 답 · 사람 작업 폼", "승인 전달 · 재작업 · 효과(보상 · 확인)", "고급: 원천 접수함 · 정의 등록"]),
 "phitl": dict(layer="L9", col=3, title="포털: 이상 확인 · 업무 화면", tech="legacy 승인 · 판단 승인/반려", box="portal",
               lines=["사건 · 안내 카드 · 판단 카드 · 점수 내역", "값 조절 → 새 예측 검토 → 결정", "업무 프로세스: 반려(사유) · 기업 보드"]),
 "pkg": dict(layer="L9", col=4, title="포털: 지식 화면", tech="지식 지도 · 에이전트 스킬 · 조치 판단 규칙", box="portal",
             lines=["일곱 층 그래프 · 패턴 경로 · 질의문 보기", "DDL 등록 · 매뉴얼 등록", "가정 실험: 사실을 바꿔 판단만"]),
 # ── L9b 업무 진행 내부 ──
 "bridge": dict(layer="L9b", col=0, title="AI 작업 다리 (AGENT_BRIDGE)", tech="legacy: 조사관이 AI 몫 · off: AI 직원", box="process",
                lines=["할 일 행에 임대 · 결과 묶음 먼저 보관", "AI 작업 넷을 한꺼번에 채움", "새 세대(재작업)에는 끼지 않음"]),
 "inbox": dict(layer="L9b", col=1, title="원천 접수함", tech="instance 방식 · 장부보다 먼저 저장", box="process",
               lines=["경보 · 설비 상태 원문 + 지문 + 위치", "접수 순간 경보 정책 고정", "설비별 임대 · 기다림 · 실패 → 사람"]),
 "inst": dict(layer="L9b", col=2, title="프로세스 인스턴스 엔진 (instance 방식)", tech="BPMN 정의서 · 설비 이상 조치 · 미지원 경보 검토", box="process",
              lines=["경보 하나 = 인스턴스 하나(경보 번호로 중복 막음)", "모든 작업을 예정으로 펼침 · 게이트웨이 판정", "경계 타이머 → 상급자 호출"]),
 "legacy": dict(layer="L9b", col=3, title="사건 상태기계 (legacy · 미니 BPMN)", tech="사건 단계 · 타이머 · SQLite", box="process",
                lines=["카드 접수 → 승인 대기 → 명령(만료)", "→ 결과 대기 → 재관측 → 회복 → 작업지시 → 종결", "실패는 사람에게 넘김 · 반려 · 조치 없이 해제", "볼륨 process-data"]),
 "appr": dict(layer="L9b", col=4, title="승인 전달 · 재검사", tech="승인 의도(사본) → 전달 · 판단당 하나", box="process",
              lines=["사건 상태 · 원자 조치 · 검토본 일치", "전달 직전 · 명령 직전 재평가", "다시 전달은 같은 역할 · 폐기는 효과 없을 때만"]),
 "rework": dict(layer="L9b", col=5, title="재작업 · 효과 · 보상", tech="고정 판본의 영향 범위 · 새 세대", box="process",
                lines=["미리보기 지문 · 막는 사유", "되돌릴 효과 → 보상 거래 · 영수증", "못 되돌릴 효과 · 설비 명령 → 확인 영수증"]),
 "proj": dict(layer="L9b", col=6, title="사례 · 실행 투영", tech="원본은 SQLite · Supabase → 지식 그래프 사본", box="process",
              lines=["사건 · 판단 사례 → 운영 기록 층", "정의 판본 · 인스턴스 · 작업 → 실행 층", "판 번호 · 지문 울타리 · 영수증 · 재시도"]),
 # ── L9c 업무 기록부 · 기업 시스템 ──
 "sacc": dict(layer="L9c", col=0, title="업무 기록부 접근 경계", kind="info",
              lines=["서비스 계정: 업무 진행 · AI 직원", "읽기 전용 계정: 판단 엔진 물리 입력 · 회사 데이터 서버", "기본 표 익명 읽기(교육용 한계) · 새 표는 막음"]),
 "supa": dict(layer="L9c", col=1, title="Supabase ① 프로세스 표", tech="PostgreSQL (compose 밖) · ProcessGPT 모양", box="supabase start",
              lines=["테넌트 · 사용자(사람 · 에이전트) · 폼", "정의 · 판본(불변) · 인스턴스 · 할 일(세대 · 임대)", "이벤트 · 알림"]),
 "ent": dict(layer="L9c", col=2, title="기업 시스템 목업: 읽기", tech="ERP · MES · CMMS · QMS · SCM · EMS · 인증 없음", box="enterprise-sim",
             lines=["MES 오더 · ERP 계약 · 재고 · CMMS 이력", "QMS 로트 · SCM 공급사 · EMS 수요", "memory: 고정 표 · supabase: ent 원천"]),
 "entx": dict(layer="L9c", col=3, title="기업 거래 · 보상 · 원장", tech="업무 진행만 호출 · 같은 요청 열쇠 = 한 번", box="enterprise-sim",
              lines=["작업지시 · 구매요청 (실행)", "보상: 작업지시 · 구매요청 취소 · 재배정 원복 · 격리 해제", "원장 전후 기록 · 볼륨 enterprise-data"]),
 "supaent": dict(layer="L9c", col=4, title="Supabase ③ ent 기업 데이터", tech="회사 업무 DB 역할", box="supabase start",
                 lines=["읽는 표: 설비 · 생산오더 · 판매 계약 · 재고", "· 보전 프로필 · 이력 · 품질 · 부품 · 공급사 · 에너지", "거래 표: 작업지시 · 구매요청 · 출하 · 로트 처분 · EMS 조치 · 원장"]),
 "supainf": dict(layer="L9c", col=5, span=2, title="Supabase ② 버팀 장치 표", tech="instance 방식의 영수증 · 대기열", box="supabase start",
                 lines=["원천 접수함 · 설비별 최신 상태", "승인 전달 · 재작업 영수증 · 효과 영수증", "실행 투영 대기열 · 투영 수리 기록"]),
 # ── L8 조사관 · 판단 엔진 ──
 "guard": dict(layer="L8", col=0, title="가드레일", tech="agent 안 · 제출 전 검사", box="agent",
               lines=["명령 필드 금지(명령 번호 · 토픽 · 쓰기)", "인용 · 범위 · 신선도 · 모름 증거", "카드 검사: 규칙 인용 · 승인 역할 · 단계"]),
 "pipe": dict(layer="L8", col=1, title="조사 파이프라인 (LangGraph 역할)", tech="legacy: 경보마다 · instance: 요청 때", box="agent",
              lines=["경보 정책 → 신선도 → 원인 후보 → 증거", "→ 증거 판정 → 원인 순위 → SOP", "→ 카드 → LLM 요약 → 가드레일 → 제출"]),
 "tools": dict(layer="L8", col=2, title="조사 도구 함수 (지식 · 시계열 · 상태 · 업무)", tech="같은 프로그램 안 함수 (MCP 서버 아님)", box="agent",
               lines=["Bolt · SQL(읽기 전용) · HTTP", "물리 입력은 업무 DB 직접 SQL"]),
 "decide": dict(layer="L8", col=3, title="조치 카드 판단 엔진", tech="LLM 없음 · 같은 입력 = 같은 답", box="agent",
                lines=["지식 → 사실 → 예측 → 후보 → 규정", "→ 득실 → 순위 → 카드 검사 → 제출", "판단 넷: 원인 판정 · 조치 후보", "· 규정 적합성 · 조치 우선순위"]),
 "apprA": dict(layer="L8", col=4, title="승인 재평가 · 변경안 · 가정 실험", tech="읽기 전용 · 제출하지 않음", box="agent",
               lines=["지금 사실로 고른 카드 다시 평가", "사람이 바꾼 값의 새 예측(검토본 재료)", "사실을 바꿔 넣은 판단(포털 실험)"]),
 "runs": dict(layer="L8", col=5, title="실행 기록 · 읽기 API", tech="메모리 · 재시작하면 사라짐", box="agent",
              lines=["경보마다 실행 하나 · 단계별 근거", "판단 기록", "지식 지도 그래프 · 템플릿 · 역할 · 패턴"]),
 "llm": dict(layer="L8", col=6, title="LLM API (밖)", tech="OpenAI 호환 · Anthropic", kind="ext",
             lines=["agent: 카드 요약 문장", "워커: Claude Code가 작업 수행"]),
 # ── L8b AI 직원 · MCP ──
 "worker": dict(layer="L8b", col=0, title="AI 직원 작업 주기 (cliagents 워커)", tech="Claude Code CLI 자식 프로세스 · 선택", box="agent-worker",
                lines=["폴링 → 할 일 집기 · 임대 → 맥락", "→ 작업 공간 → 연결 설정 → CLI", "→ 결과 · 질문 · 보류 → 저장", "볼륨 worker-data · 또는 강사 PC"]),
 "wsp": dict(layer="L8b", col=1, title="작업 공간 · 연결 설정", tech="할 일마다 폴더 하나 · 보존 뒤 정리", box="agent-worker 안",
             lines=["규칙 문서 · 지시 · 할 일 · 결과 · 대화 기록", "선언된 MCP 서버만 · 끝나면 비밀 지움", "자식에게 비밀 환경 값 안 넘김"]),
 "outc": dict(layer="L8b", col=2, title="결과 판정 · 질문 · 보류", tech="폼 계약 검사", box="agent-worker 안",
              lines=["서식 틀리면 같은 대화로 고쳐 달라", "사람 질문 → 사람 대기 → 답으로 이어감", "근거 모름 → 보류 영수증 · 취소 → 프로세스 끔"]),
 "mcps": dict(layer="L8b", col=3, title="판단 엔진 서버 (hyd-dmn)", tech="Streamable HTTP · 판단 엔진을 도구로", box="dmn-mcp",
              lines=["진단 · 규칙 · 입력 · 사실 · 시계열 · 지표", "카드 평가 · 예측 · 선례 · 득실", "쓰기는 판단 제출 하나"]),
 "mcpent": dict(layer="L8b", col=4, title="회사 데이터 서버", tech="Streamable HTTP · 읽기 전용 계정", box="enterprise-mcp",
                lines=["시스템별 고정 읽기 도구", "표 정의 · 카탈로그 · 검사한 SELECT", "특권 계정이면 시작 거부"]),
 "mcpneo": dict(layer="L8b", col=5, title="Neo4j MCP 서버", tech="mcp-neo4j-cypher · READ_ONLY", box="agent-worker 안 stdio",
                lines=["스키마 보기 · 읽기 질의 두 도구", "CLI가 자식으로 띄움 · 실행 때 내려받음"]),
 # ── L7 지식 그래프와 관리 ──
 "schema": dict(layer="L7", col=0, title="온톨로지 스키마", tech="정의 하나 → 제약 · OWL · AI 설명문",
                lines=["층: 가치(BSC) · 프로세스(BPMN) · 리소스", "· 진단 · 스킬/규칙(SOP · DMN)", "· 외부 · 예측 · 운영 기록"]),
 "seed": dict(layer="L7", col=1, title="지식 채우기", tech="kg-seed · cypher-shell · 기동 때 한 번", kind="once",
              lines=["제약 → 인스턴스 → 전문가 답 보강", "사람이 고친 지식은 덮지 않음", "탐지 정의는 넣지 않음"]),
 "neo": dict(layer="L7", col=2, title="Neo4j 지식 그래프", tech="Neo4j 5.26 Community + APOC", box="neo4j",
             lines=["일곱 층 지식 + 탐지 정의", "사건 · 판단 투영 · 실행 층 · 매뉴얼 절", "편집 영수증 · 적재 묶음", "볼륨 neo4j-data"]),
 "tmpl": dict(layer="L7", col=3, title="Cypher 질의 템플릿", tech="읽기 전용 템플릿", box="agent에 복사",
              lines=["경보 → 원인 후보 + 증거 규칙", "원인 → SOP 스킬 → 단계 → 매뉴얼", "판단 입력 · 공급사 · 예측 모델 · 선례"]),
 "manual": dict(layer="L7", col=4, title="매뉴얼 인제스천", tech="process 안 · 원문 판본 보관", box="process",
                lines=["원문 판본(지문) · 길면 구간", "구조 파서 또는 AI 직원 → 사람 검토", "→ 한 트랜잭션 적재 · 최신 묶음 되돌리기", "골든 질문 시험"]),
 "kedit": dict(layer="L7", col=5, title="지식 편집", tech="process 안 · 영수증 · 판 번호 검사", box="process",
               lines=["스킬 이름 · 설명 · 승인 역할 · 새 스킬", "순위 점수식 · BSC 조건 판정 정책", "DDL 미리보기 → 입력 데이터 연결"]),
 "ksync": dict(layer="L7", col=6, title="주기 맞추기", tech="process 안 · 업무 진행 방식과 무관", box="process",
               lines=["등록한 표 · 칸 변화 → 원천 상태", "SCM 공급사 → 공급사 노드 · 견적", "AI 직원의 묶인 임대 정리"]),
 # ── L7b 온톨로지 일곱 층 ──
 "ext": dict(layer="L7b", col=0, title="⑥ 외부 변수 · 예측", tech="변수 · 예측 프레임워크", box="neo4j 안",
             lines=["환율 · 외기 온도 · 전력 단가 · 고객 수요", "예측: 원인 · 스킬 가정 → 상태 변수", "저장 예측은 참고용"]),
 "val": dict(layer="L7b", col=1, title="① 가치 (BSC)", tech="관점 → 전략 목표 → 성과 지표", box="neo4j 안",
             lines=["SUPPORTS 목표 받침", "MEASURES · OWNED_BY 부서", "INFLUENCES 부호 · 강도 · 조건"]),
 "skl": dict(layer="L7b", col=2, title="⑤ 스킬 · 규칙 (SOP · DMN)", tech="스킬 = SOP · 판단 · 결정표 · 규칙", box="neo4j 안",
             lines=["HAS_STEP 단계 → REFERS_TO 매뉴얼 절", "CONSISTS_OF 원자 조치 · AFFECTS", "규칙 TESTS 입력 · OUTPUTS · APPLIES_TO", "입력 SOURCED_FROM 시스템"]),
 "dia": dict(layer="L7b", col=3, title="④ 설비 진단 (ISO 13374)", tech="패턴 → 증상 → 고장 → 원인 → 증거", box="neo4j 안",
             lines=["DETECTS · INDICATES · CAUSES", "LEADS_TO 고장 전파", "EVIDENCED_BY 증거 규칙(기록 DB 질의)"]),
 "res": dict(layer="L7b", col=4, title="③ 리소스", tech="조직 · 시스템 · 설비 · 상태 변수", box="neo4j 안",
             lines=["부서 · 역할(등급) · 정보 시스템", "설비 → 구성품 → 센서 · 구동기 · 부품", "상태 변수(조작 · 결과 · 외란) · 공급사"]),
 "prc": dict(layer="L7b", col=5, title="② 프로세스 (BPMN)", tech="프로세스 · 흐름 노드 · 순서 흐름", box="neo4j 안",
             lines=["이벤트 · 작업 · 게이트웨이", "ACHIEVES 목표 · READS/PRODUCES 데이터", "ATTACHED_TO 경계 타이머"]),
 "rec": dict(layer="L7b", col=6, title="⑦ 운영 기록", tech="사례 기록 · 실행 층", box="neo4j 안",
             lines=["사건 · 판단 사례(선례)", "판본 · 인스턴스 · 작업 노드", "투영 울타리 · 편집 영수증"]),
 # ── L6 ──
 "fuxa": dict(layer="L6", col=0, title="FUXA 웹 SCADA", tech="FUXA latest(판 고정 안 됨)", box="fuxa",
              lines=["값 · 상태 · IT 경보 표시 · 알람", "수동 조작: 팬 · 부하 · 리셋 · 모드"]),
 "finit": dict(layer="L6", col=1, title="화면 넣기", tech="fuxa-init · 기동 때 한 번", kind="once", lines=["프로젝트 업로드 · 확인"]),
 "graf": dict(layer="L6", col=4, title="Grafana", tech="Grafana 11.3 · 익명 보기 · 관리자 편집", box="grafana",
              lines=["추세 · 경보 · 조치 · 감사", "주석: 경보 발생 · 해제 · 명령 발행"]),
 "prom": dict(layer="L6", col=5, title="Prometheus (선택)", tech="monitor 프로필 · 저장 공간 없음", kind="opt", box="prometheus",
              lines=["서비스 지표 긁기", "경고 규칙 · Alertmanager 없음"]),
 # ── L5 ──
 "sink": dict(layer="L5", col=3, title="저장 심부름꾼 (JDBC Sink 역할)", tech="connect-sink · Python asyncio", box="connect-sink",
              lines=["토픽 → 표 · 묶음 저장", "행 + Kafka 위치를 한 트랜잭션"]),
 "tsdb": dict(layer="L5", col=4, span=2, title="TimescaleDB (PostgreSQL)", tech="초 단위 값 · 특징값(하이퍼테이블) / 경보 · 조치 · 감사 표", box="timescaledb",
              lines=["분 단위 요약(연속 집계)", "계정: 쓰기 · 그래프용 읽기 · 시계열 읽기 전용", "볼륨 tsdb-data"]),
 "ret": dict(layer="L5", col=6, title="보존 정책", kind="info", lines=["원시 값: 압축 뒤 지움", "분 단위 요약: 더 오래", "경보 · 명령 · 감사: 지우지 않음"]),
 # ── L4 ──
 "feat": dict(layer="L4", col=2, title="특징 계산", tech="detector 안", box="detector",
              lines=["기울기 · 이상 점수(고정 기준과의 거리)", "→ feat.1s"]),
 "pattern": dict(layer="L4", col=3, title="패턴 실행기 (CEP 역할)", tech="Neo4j 탐지 정의 · 판 = 지문", box="detector",
                 lines=["대기 → 후보 → 울림 → 해제 중", "유지 시간 · 해제식 · 정의 주기적 재적재", "입력 품질 · 관측 공백 검사"]),
 "trip": dict(layer="L4", col=4, title="트립 감시", tech="PLC 상태 직접 감시", box="detector",
              lines=["PLC 트립 → 치명 경보 울림 / 리셋되면 풀림"]),
 "store": dict(layer="L4", col=5, title="체크포인트 · outbox", tech="SQLite 한 파일", box="detector",
               lines=["상태 + 읽은 위치 + 경보 한 트랜잭션", "경보 최소 한 번 전달", "볼륨 detector-data"]),
 # ── L3 ──
 "gw": dict(layer="L3", col=1, title="명령 게이트웨이 (DMZ)", tech="cmd-gateway · ot-net + it-net", box="cmd-gateway",
            lines=["검사 1: 서식 · 허용 조치 · 만료 · 중복", "· 원격 자동 모드 · 속도 제한", "경보 중계 → alert(retain)"]),
 "ing": dict(layer="L3", col=2, title="수집 다리 (DMZ · MQTT Source 역할)", tech="connect-ingest · ot-net + it-net", box="connect-ingest",
             lines=["구독만 · 메모리 대기열", "넘치거나 전송 실패면 버림(수만 셈)", "디스크 버퍼 없음"]),
 "rp": dict(layer="L3", col=3, span=2, title="Redpanda (Kafka API)", tech="노드 하나 · 파티션 하나", box="redpanda",
            lines=["plant.tag · plant.wave · plant.status · feat.1s", "alerts · action.cmd · audit (칸마다 보관 기간)", "키 = 설비 · 값 JSON", "볼륨 redpanda-data"]),
 "tinit": dict(layer="L3", col=5, title="토픽 만들기", tech="topic-init · rpk · 기동 때 한 번", kind="once", lines=["토픽 + 보관 기간"]),
 "cons": dict(layer="L3", col=6, title="Redpanda Console (선택)", tech="tools 프로필", box="redpanda-console", kind="opt", lines=["토픽 · 메시지 보기 · 인증 없음"]),
 # ── L2 ──
 "daq": dict(layer="L2", col=1, title="DAQ 필터 (수집 프로필)", tech="plant-sim 안 · lite / full", box="plant-sim 안",
             lines=["lite: 핵심 값만 매번 · 나머지는 바뀌면", "full: 전부 + 파형"]),
 "edge": dict(layer="L2", col=2, title="엣지 발행 · 수신 (EdgeX 역할)", tech="paho MQTT", box="plant-sim 안",
              lines=["태그 · 파형 · 상태(retain) 발행", "cmd/auto · cmd/manual · mode 구독", "출처는 토픽으로(HITL / FUXA)"]),
 "emqx": dict(layer="L2", col=3, title="EMQX (MQTT 브로커)", tech="EMQX 5.8 · 인증 · ACL 없음", box="emqx",
              lines=["깨끗한 세션 · 상태 · 경보 retain", "관리 대시보드"]),
 "mqttt": dict(layer="L2", col=4, span=2, title="MQTT 토픽", kind="info",
               lines=["plant/{k}/tag/{이름} ↑ QoS0 · plant/{k}/wave/{센서} ↑ QoS0", "plant/{k}/status ↑ QoS1 retain (ACK 포함)",
                      "plant/{k}/cmd/auto ↓ QoS1 · cmd/manual ↓ · mode ↓", "plant/{k}/alert ↓ QoS1 retain · {k} = 설비"]),
 # ── L1 ──
 "sensors": dict(layer="L1", col=0, title="센서 채널", kind="info",
                 lines=["온도 · 압력 · 전력 · 유량 · 진동", "가상: 냉각 효율 · 냉각 능력 · 시스템 효율", "팬 · 부하 설정값"]),
 "unit": dict(layer="L1", col=1, title="유압설비 HYD-01~03", tech="열 평형 모델 · 시간 배율", box="plant-sim",
              lines=["펌프 A / B · 모터 · 쿨러 + 팬 · 탱크", "숨은 값: 쿨러 상태 · 누설 · 베어링"]),
 "plc": dict(layer="L1", col=2, title="soft-PLC (검사 2)", tech="같은 프로그램 안", box="plant-sim 안",
             lines=["인터록: 과열 · 저압 · 고진동", "출처 · 모드 · 만료 · 중복 · 범위 · 트립", "운전 · 보호 정지 · 계획 정지 · 결과 → status"]),
 "fault": dict(layer="L1", col=3, title="고장 주입 · 강의 API", tech="FastAPI · 인증 없음", box="plant-sim",
               lines=["쿨러 오염 · 펌프 누설 · 팬 베어링 · 복구", "모드 · 수동 · 배율 · 초기화"]),
}

# (from, to, 종류, 라벨, 상세)   종류: data · alert · cmd · ok · api · mon · once · human · file
ARROWS = [
 ("unit", "plc", "data", "함수 호출", "소구간마다 고장 램프 → 열 모델 한 걸음 → 인터록 검사 (같은 잠금 안)"),
 ("plc", "unit", "cmd", "구동 쓰기", "팬 · 부하 · 펌프 선택 · 정지 · 리셋을 설비 상태에 적용"),
 ("fault", "unit", "cmd", "고장 램프", "강의 API로 받은 고장: 숨은 값(쿨러 상태 · 누설 · 베어링 마모)을 기본 300설비초 동안 선형으로"),
 ("unit", "daq", "data", "태그 값", "1초 루프가 19태그(반올림)를 DAQ 필터에 넘김(함수 호출)"),
 ("daq", "edge", "data", "보낼 태그", "lite: 6태그 매초 · 데드밴드 · 10/30초 하트비트, full: 전부 + 파형(PS1 · EPS1 100 Hz, FS1 10 Hz)"),
 ("edge", "emqx", "data", "MQTT pub tag · status", "plant/{k}/tag/{이름} QoS0 {t, v, q} · status QoS1 retain(매초) · wave QoS0(full) · 클라이언트 plant-sim-edge"),
 ("emqx", "edge", "cmd", "cmd/auto · manual · mode", "구독 QoS1: cmd/auto(출처 HITL) · cmd/manual(출처 FUXA) · mode(0/1/2)"),
 ("edge", "plc", "cmd", "함수 호출", "명령 → PLC 검사(출처 · 만료 · 중복 32 · 범위 · 트립), 처리 뒤 status 즉시 발행"),
 ("emqx", "ing", "data", "MQTT 구독", "plant/+/tag/+ QoS0 · plant/+/wave/+ QoS0 · plant/+/status QoS1 · clean session · 발행 코드 없음"),
 ("ing", "rp", "data", "Kafka plant.*", "plant.tag {asset, name, t, v, q} · plant.wave · plant.status(원문 + asset) · 키 = 설비 · 메모리 대기열 2만 건"),
 ("rp", "pattern", "data", "plant.tag · wave · status", "그룹 detector · 최신부터 · 레코드마다 수동 커밋 · SQLite로 재처리 건너뜀"),
 ("feat", "rp", "data", "feat.1s", "{asset, t, sensor, mean, rms, slope, score} · TS1 틱마다 · 전달 확인 없음"),
 ("pattern", "rp", "alert", "alerts", "{alertId, asset, pattern, severity, state RAISE/CLEAR, t, evidence} · outbox 뒤 확인 받고 지움"),
 ("pattern", "store", "file", "SQLite", "레코드마다 상태 + 오프셋 + 경보 outbox를 한 트랜잭션에"),
 ("pattern", "neo", "api", "Bolt 패턴 정의", "held 탐지 정의 + 검사 조건 · 해제식 · 유지 시간 · 기동 때 + 15초마다 · 읽기 5초", {"g": 2}),
 ("rp", "sink", "data", "여섯 토픽", "plant.tag · feat.1s · alerts · action.cmd · plant.status · audit · 그룹 connect-sink · 처음부터 · 수동 커밋"),
 ("sink", "tsdb", "data", "SQL INSERT · upsert", "tag_1s · feat_1s INSERT, alerts · actions upsert, audit INSERT, sink_offsets 갱신 — 한 트랜잭션"),
 ("tsdb", "graf", "api", "SQL (grafana)", "추세 · 경보 이력 · 조치 · 감사 · 주석 3종(경보 발생 · 해제 · 명령 발행)"),
 ("rp", "gw", "cmd", "action.cmd · alerts", "그룹 cmd-gateway · 최신부터 · 자동 커밋"),
 ("gw", "emqx", "cmd", "MQTT cmd/auto", "검사 1 통과분만 {cmdId, source:HITL, expiresAt, writes[{res, v}]} QoS1 retain 금지"),
 ("gw", "emqx", "alert", "MQTT alert", "plant/{k}/alert QoS1 retain {alertId, pattern, severity, state, level 2/0, display_text}"),
 ("emqx", "gw", "data", "status 구독", "plant/+/status → 설비별 PLC 모드 기억(검사 ⑤)"),
 ("gw", "rp", "data", "audit", "CMD_FORWARDED · CMD_REJECTED(검사 이름 · 이유) · 키 = 설비"),
 ("emqx", "fuxa", "data", "MQTT 구독 · 조작", "값 8 · 상태 문구 · 경보 표시 구독 / cmd/manual · mode 발행 · 클라이언트 fuxa-ot", {"g": 0}),
 ("finit", "fuxa", "once", "한 번", "프로젝트(태그 54 · 화면 1 · 알람 6) 업로드 · 확인"),
 ("rp", "pipe", "alert", "alerts RAISE (legacy)", "그룹 agent · 최신부터 · instance 방식이면 자동 파이프라인 정지", {"g": 7}),
 ("pipe", "guard", "api", "카드 검사", "LLM 요약 뒤 가드레일 통과해야 제출(요약 글은 검사 안 함)"),
 ("pipe", "tools", "api", "함수 호출", "같은 프로그램 안의 도구 함수"),
 ("tools", "neo", "api", "Bolt 템플릿 질의", "허용된 템플릿만 · 읽기 5초 · 공급사 승인도 여기서"),
 ("tools", "tsdb", "api", "SQL 증거 (읽기 전용)", "계정 hyd_timeseries_reader · tag_1s · feat_1s · tag_1m · 5초 · 신선도(최신 TS1 60초)", {"g": 6}),
 ("tools", "ent", "api", "HTTP GET", "MES 오더 · ERP 계약 · QMS 로트 · CMMS 이력(예비 펌프)"),
 ("tools", "ing", "mon", "HTTP healthz", "connect-ingest 상태 — 신선도 판정의 한 조건"),
 ("pipe", "decide", "api", "카드 순위", "규칙 · 예측 · BSC 득실 · 선례 · 납기 · 품질로 조치 카드 순위"),
 ("pipe", "llm", "api", "HTTPS 요약", "카드 일부 → 한국어 3문장 · 8초 · 600토큰 · 재시도 없음 · 실패 시 정해진 문장"),
 ("pipe", "legacy", "ok", "HTTP 카드 · 판단 제출", "카드 · 판단 제출 · 경보 정책 조회 · 설비 상태 조회"),
 ("legacy", "rp", "cmd", "action.cmd · audit", "{cmdId, asset, incident, source:HITL, actions[], approvedBy, expiresAt(+120초)} · 감사 이벤트", {"g": 7}),
 ("rp", "legacy", "alert", "alerts · plant.status", "RAISE/CLEAR · ACK(cmdId · result) 대조 · 그룹 process", {"g": 7}),
 ("legacy", "tsdb", "api", "SQL 회복 판정", "tag_1s 최신 회복 태그(TS1 · PS1 · VS1)", {"g": 6}),
 ("legacy", "entx", "ok", "HTTP 업무 실행", "작업지시(CMMS) · 구매요청(ERP) · 멱등 키 · 거래 기록"),
 ("proj", "neo", "api", "Bolt 투영 · 지식", "사건(단계마다) · 판단 사례(승인 때) 투영 · SQLite 대기열 · 판 번호 울타리"),
 ("inst", "supa", "ok", "SQL 인스턴스 · Task", "정의 · 인스턴스 · 할 일 · 이벤트 (접수함 · 승인 전달 · 효과 영수증은 ② 버팀 장치 표)"),
 ("bridge", "pipe", "api", "HTTP evaluate", "AI 다리 legacy(기본): 조사관 결과로 AI Task 4개를 채움 · 90초 · 2 MB · 120초 임대"),
 ("worker", "supa", "ok", "SQL 점유 · 저장", "할 일 점유 · 임대 연장(30초) · 조건부 저장 · 이벤트 기록"),
 ("worker", "mcps", "api", "MCP", "hyd-dmn · enterprise(HTTP) · neo4j(stdio, CLI의 자식)"),
 ("worker", "llm", "api", "HTTPS Claude Code", "작업 지시 · 도구 결과를 주고받으며 Task 수행 · 1,800초"),
 ("mcps", "neo", "api", "Bolt 읽기", "dmn-mcp 지식 조회(판단 엔진과 같은 템플릿) · Neo4j MCP는 104번"),
 ("mcpent", "supaent", "api", "SQL ent 읽기", "enterprise-mcp · 계정 hyd_enterprise_reader · SELECT만 200행 · 5초"),
 ("mcps", "legacy", "ok", "판단 제출 · 설비 상태", "dmn-mcp → 판단 제출(유일한 쓰기) · 최신 설비 상태 읽기"),
 ("ent", "supaent", "data", "SQL ent", "ENTERPRISE_BACKEND=supabase일 때 ent 읽기 · 실행 · 보상"),
 ("people", "portal", "human", "브라우저", "화면 파일(HTML · JS)"),
 ("phitl", "legacy", "human", "HTTP 직접 호출", "사건 · 승인 · 판단 · 스킬 · 매뉴얼 · DDL, 같은 방식으로 agent · detector · gateway · enterprise"),
 ("people", "fuxa", "human", "브라우저 FUXA", "운전원 화면 · 수동 조작", {"g": 0}),
 ("seed", "neo", "once", "Bolt 한 번", "제약 → 인스턴스 → 전문가 답 보강 (탐지 정의는 넣지 않음)"),
 ("manual", "neo", "ok", "Bolt 적재", "검토 확정분을 한 트랜잭션으로 · 전후 기록 · 최신 묶음부터 되돌리기"),
 ("tinit", "rp", "once", "한 번", "rpk topic create · 보존 기간 설정"),
 ("cons", "rp", "api", "Kafka", "토픽 · 메시지 보기 · 손으로 넣기"),
 ("prom", "sink", "mon", "HTTP 지표 긁기", "ingest · gateway · detector · sink · agent · process를 10초마다 긁음", {"g": 6}),
 # ── 58~76 덧붙임(2026-10-07 감사 반영) ──
 ("portal", "fault", "cmd", "HTTP 강의 API", "결함 시뮬레이션: 고장 넣기 · 모드 · 수동 쓰기 · 초기화 · 배율 — 명령 게이트웨이를 거치지 않음"),
 ("legacy", "apprA", "api", "HTTP 승인 재평가", "승인 순간 지금 사실로 다시 평가 · 변경안 미리보기 · 20초 · 응답 없으면 승인 거절"),
 ("appr", "apprA", "api", "HTTP 재평가 · 검토본", "승인 전달 직전 · 명령 직전 재평가, 사람이 바꾼 값의 검토본 계산 · 20초"),
 ("tools", "supaent", "api", "SQL 물리 입력", "DDL로 연결한 입력 데이터 · ent 읽기 전용 계정 · 3초 · 설비당 한 행"),
 ("mcps", "tsdb", "api", "SQL 시계열 읽기", "dmn-mcp · 시계열 읽기 전용 계정"),
 ("mcps", "prom", "api", "HTTP PromQL", "dmn-mcp · 지표 목록 · 계열 · 질의"),
 ("mcps", "ent", "api", "HTTP 업무 조회", "dmn-mcp · 회사 시스템 목업의 납기 · 보상 · 로트 · 예비 펌프"),
 ("mcps", "ing", "mon", "HTTP healthz", "dmn-mcp · 수집 다리 상태(신선도)"),
 ("rp", "inbox", "alert", "접수함 alerts · status", "instance 방식: 접수함에 먼저 저장한 뒤 오프셋 커밋 · 최대 50건 · 실패 시 30초까지 물러섬"),
 ("proj", "neo", "api", "Bolt 실행 투영", "판본 · 흐름 노드 · 순서 흐름 · 인스턴스 · 작업과 관계 · 판 번호 · 지문 울타리"),
 ("inst", "entx", "ok", "HTTP 작업지시 · 보상", "작업지시 · 구매요청 · 보상 거래 · 원장 조회"),
 ("pinst", "inst", "human", "HTTP · SSE 인스턴스", "인스턴스 · 할 일 · 승인 전달 · 재작업 · 효과 · 이벤트 흐름(0.7초)"),
 ("portal", "graf", "human", "iframe 패널", "실시간 모니터링 화면 · 설비 선택 · 10분 · 5초"),
 ("inst", "worker", "mon", "HTTP 워커 상태", "작업자 생존 · 하는 일(포털 표시용)"),
 ("kedit", "neo", "ok", "Bolt 지식 편집", "스킬 · 점수식 · BSC 조건 편집 영수증 · DDL 입력 데이터 등록"),
 ("ksync", "supaent", "api", "SQL 주기 동기화", "등록한 표 · 칸 변화 비교 · SCM 공급사 (같은 주기로 할 일 표의 묶인 임대 정리)"),
 ("people", "neo", "human", "Neo4j Browser", "지식 그래프 직접 보기"),
 ("people", "emqx", "human", "EMQX 대시보드", "게시판 연결 · 토픽 보기"),
 ("people", "graf", "human", "브라우저 직접", "대시보드 직접 열기"),
 # ── 77~ 덧붙임(2026-10-08 위층 구조 펼침) ──
 ("phitl", "runs", "api", "HTTP 실행 기록", "이상 확인 화면: 조사관 실행 기록 · 단계별 근거"),
 ("pkg", "runs", "api", "HTTP 지식 지도", "지식 지도 그래프 · 질의 템플릿 보기 · 역할 · 패턴 목록"),
 ("pkg", "apprA", "api", "HTTP 가정 실험", "조치 판단 규칙 화면: 사실을 바꿔 넣고 제출 없이 판단"),
 ("pkg", "kedit", "human", "HTTP 스킬 · DDL", "스킬 고치기 · 새 스킬 · DDL 미리보기와 등록 · 묶음 되돌리기"),
 ("pkg", "manual", "human", "HTTP 매뉴얼", "올리기 · 추출 · 검토 · 확정 · 되돌리기 · 원문 내려받기"),
 ("phitl", "entx", "api", "HTTP 기업 보드", "업무 프로세스 화면: 시스템별 상태 · 거래 이력"),
 ("inbox", "inst", "alert", "접수 행 처리", "설비별 임대로 처리 → 인스턴스 시작 · 사건 결과 · 해제 반영"),
 ("inst", "legacy", "ok", "사건 열기 · 서비스 작업", "인스턴스를 열 때 PLC 경로용 사건을 함께 엶 · 명령 발행 · 재관측 작업을 사건에 맡김"),
 ("legacy", "inst", "ok", "사건 단계 → 작업 완료", "사건 상태 변화로 서비스 작업 제출 · 회복 여부 값"),
 ("inst", "appr", "ok", "카드 선택 → 승인 의도", "사람 작업 제출 순간의 카드 사본을 전달 대기로"),
 ("appr", "legacy", "ok", "전달된 승인", "재검사 통과 뒤 사건의 판단 승인 → 명령 · 작업지시 요청 결정"),
 ("rework", "inst", "ok", "새 세대", "영향 행 취소 · 새 행 · 변수 되돌림 · 사건 다시 승인 대기"),
 ("legacy", "proj", "file", "사건 · 사례 원본", "SQLite 사건 저장소와 투영 대기열을 한 커밋에"),
 ("inbox", "supainf", "ok", "SQL 접수 행", "원문 · 지문 · 장부 위치 · 고정된 경보 정책 · 설비별 최신 상태"),
 ("appr", "supainf", "ok", "SQL 승인 전달 행", "대기 · 전달됨 · 실패 · 폐기, 판단당 하나"),
 ("rework", "supainf", "ok", "SQL 영수증", "재작업 요청 · 결과, 보상 · 확인 영수증(지우지 않음)"),
 ("proj", "supainf", "api", "SQL 투영 대기열", "실행 투영 대기열 읽기 · 수리 기록"),
 ("bridge", "supa", "ok", "SQL 임대 · 결과 보관", "할 일 행에 임대 · 조사관 결과 묶음을 먼저 저장한 뒤 게시"),
 ("entx", "supaent", "data", "SQL 거래 · 원장", "supabase일 때: 거래 · 보상을 잠금 아래 실행, 원장에 전후 상태"),
 ("decide", "tools", "api", "사실 모으기", "입력 데이터 출처대로 기록 DB · 설비 상태 · 회사 시스템 · 공급사 · 선례"),
 ("decide", "guard", "api", "카드 검사", "규칙 인용 · 권고 카드 규정 · 승인 역할 · SOP 단계"),
 ("apprA", "decide", "api", "같은 엔진 재계산", "승인 재평가 · 변경안 미리보기 · 가정 실험 모두 같은 판단 엔진"),
 ("pipe", "runs", "file", "실행 · 판단 기록", "경보마다 실행 하나 · 단계별 입력과 결과 · 메모리"),
 ("worker", "wsp", "file", "작업 공간", "할 일마다 폴더: 지시 · 할 일 · 결과 · 대화 기록 · 연결 설정"),
 ("worker", "outc", "api", "결과 판정", "마지막 응답을 폼 계약에 대어 판정 · 질문 · 보류"),
 ("worker", "mcpent", "api", "MCP HTTP", "회사 데이터 서버 도구"),
 ("worker", "mcpneo", "api", "MCP stdio", "CLI의 자식 프로그램으로 띄움"),
 ("mcpneo", "neo", "api", "Bolt 읽기 전용", "스키마 · 읽기 질의 두 도구"),
 ("manual", "inst", "ok", "추출 인스턴스", "정의 「매뉴얼 원천 추출」 할 일 → AI 직원"),
 ("schema", "seed", "file", "제약 조건 파일", "스키마 정의 → 제약 · OWL · AI 설명문 생성"),
 ("ksync", "neo", "ok", "Bolt 원천 상태 · 공급사", "입력 데이터 원천 상태 표시 · 공급사 승인 · 견적 관계"),
 ("schema", "worker", "file", "AI 설명문", "스키마 설명문을 AI 직원 이미지 · 지시에"),
 ("ext", "val", "api", "INFLUENCES", "외부 변수 → 성과 지표 · 상태 변수 (조건부 포함)"),
 ("skl", "val", "api", "AFFECTS → INFLUENCES", "스킬이 움직이는 변수에서 영향 관계를 따라 지표 득실"),
 ("dia", "skl", "api", "MITIGATED_BY · REMEDIED_BY", "고장 유형 → 즉시 완화 · 근본 조치, ADDRESSES 원인 한정"),
 ("dia", "res", "api", "OCCURS_IN · OBSERVED_BY", "고장 → 구성품, 증상 → 센서, 원인 → 부품 · 외란 변수"),
 ("prc", "res", "api", "PERFORMED_BY", "흐름 노드 → 역할 · 시스템"),
 ("rec", "prc", "api", "INSTANCE_OF · MAPS_TO", "실행 층 인스턴스 → 프로세스, 판본 노드 → 의미 노드"),
 ("prc", "skl", "api", "INVOKES · READS", "판단 작업 → 판단 정의 · 입력 데이터"),
 ("rec", "skl", "api", "CHOSE · INSTANCE_OF", "판단 사례 → 고른 스킬 · 우선순위 판단(선례)"),
 ("skl", "res", "api", "APPROVED_BY", "스킬 → 승인 역할, 원자 조치 → 구동기 · 시스템"),
 ("prc", "val", "api", "ACHIEVES", "프로세스 → 전략 목표"),
 ("rec", "dia", "api", "RAISED_BY · DIAGNOSED_AS", "사건 → 이상 패턴 · 판정 원인"),
]
